import type { ActivityController, ActivityEvaluation, ActivityHost } from '../../domain/activity-runtime';
import { localizedNodes, setPending, showEvaluation, statusRegion } from '../activity-kit/shared';
import { renderInspectableSourceVisual } from '../source-visual';
import type { HolidayItinerarySourceVisual, HolidayItineraryTapeModel, HolidayItineraryTapeResponse } from './manifest';

export function renderHolidayItineraryTape(model: HolidayItineraryTapeModel, host: ActivityHost, submit: (response: HolidayItineraryTapeResponse) => Promise<ActivityEvaluation>): ActivityController {
    const lifecycle = new AbortController(); const root = document.createElement('section'); root.className = 'academy-activity academy-holiday-itinerary-tape'; root.dataset.activityId = model.id;
    const heading = document.createElement('h2'); heading.id = `${model.id}-prompt`; heading.tabIndex = -1; heading.append(...localizedNodes(model.prompt));
    const teaching = document.createElement('section'); teaching.className = 'academy-holiday-tape-teaching'; teaching.dataset.lessonPhase = 'teaching';
    model.payload.teaching.forEach(step => { const card = document.createElement('article'); const title = document.createElement('h3'); title.append(...localizedNodes(step.title)); const pattern = document.createElement('p'); pattern.className = 'academy-holiday-tape-pattern academy-japanese'; pattern.lang = 'ja'; pattern.textContent = step.pattern; const instruction = document.createElement('p'); instruction.append(...localizedNodes(step.instruction)); card.append(title, pattern, instruction); teaching.append(card); });
    const sources = document.createElement('section'); sources.className = 'academy-holiday-tape-sources'; sources.append(renderVisual(model.provenance.moodle.vocabularySheet, host.language), renderVisual(model.provenance.moodle.grammarSheet, host.language));
    const audio = document.createElement('audio'); audio.className = 'academy-holiday-tape-audio'; audio.controls = true; audio.preload = 'metadata'; audio.src = model.provenance.moodle.audio.url; audio.dataset.sourceSha256 = model.provenance.moodle.audio.payloadSha256; audio.setAttribute('aria-label', host.language === 'ja' ? 'Moodle B-22 原音声' : 'Original Moodle B-22 audio');
    const form = document.createElement('form'); form.className = 'academy-holiday-tape-form'; form.setAttribute('aria-labelledby', heading.id); const board = document.createElement('ol'); board.className = 'academy-holiday-tape-board'; model.payload.pins.forEach(pin => board.append(renderPin(model, pin, host.language))); const check = document.createElement('button'); check.type = 'submit'; check.className = 'academy-button academy-button-primary academy-holiday-tape-check'; check.textContent = host.language === 'ja' ? '四つのピンを確認する' : 'Check the four pins'; form.append(board, check);
    const key = renderAnswerKey(model, host.language); const status = statusRegion('academy-kit-feedback academy-holiday-tape-feedback'); root.append(heading, teaching, sources, audio, form, key, status); host.replace(root);
    form.addEventListener('submit', event => { event.preventDefault(); const response = responseFromForm(model, form); if (!response) { const message = host.language === 'ja' ? '四つのピンすべてを話し手AかBの棚に置いてください。' : 'Place all four pins on either speaker shelf A or B.'; status.textContent = message; host.announce(message); return; } setPending(root, true); void submit(response).then(evaluation => { root.dataset.outcome = evaluation.result.outcome; key.hidden = false; showEvaluation(status, evaluation, host); if (evaluation.result.outcome === 'lapse') setPending(root, false); }).catch(error => { setPending(root, false); status.textContent = error instanceof Error ? error.message : String(error); }); }, { signal: lifecycle.signal });
    return { focus() { form.querySelector<HTMLInputElement>('input')?.focus(); }, dispose() { lifecycle.abort(); root.remove(); } };
}

function renderVisual(visual: HolidayItinerarySourceVisual, language: 'ja' | 'en' | undefined): HTMLElement { return renderInspectableSourceVisual(visual, language, 'academy-holiday-tape-source'); }
function renderPin(model: HolidayItineraryTapeModel, pin: HolidayItineraryTapeModel['payload']['pins'][number], language: 'ja' | 'en' | undefined): HTMLElement { const item = document.createElement('li'); item.className = 'academy-holiday-tape-pin'; item.dataset.sourceQuestionId = pin.sourceQuestionId; const fieldset = document.createElement('fieldset'); const legend = document.createElement('legend'); legend.textContent = language === 'ja' ? `音声ピン ${pin.sourceOrder}` : `Audio pin ${pin.sourceOrder}`; fieldset.append(legend); (['speaker-a', 'speaker-b'] as const).forEach(speakerId => { const label = document.createElement('label'); const input = document.createElement('input'); input.type = 'radio'; input.name = `${model.id}:${pin.id}`; input.value = speakerId; input.required = true; const shelf = document.createElement('span'); shelf.className = 'academy-holiday-tape-shelf'; shelf.textContent = speakerId === 'speaker-a' ? (language === 'ja' ? '話し手 A' : 'Speaker A') : (language === 'ja' ? '話し手 B' : 'Speaker B'); label.append(input, shelf); fieldset.append(label); }); item.append(fieldset); return item; }
function renderAnswerKey(model: HolidayItineraryTapeModel, language: 'ja' | 'en' | undefined): HTMLElement { const section = document.createElement('section'); section.className = 'academy-holiday-tape-key'; section.dataset.answerVisibility = 'after-attempt'; section.hidden = true; const heading = document.createElement('h3'); heading.textContent = language === 'ja' ? '試したあとの B-22 の聞き取り' : 'B-22 listening notes after your attempt'; const answers = document.createElement('ol'); model.payload.pins.forEach(pin => { const item = document.createElement('li'); item.textContent = `${pin.sourceOrder}. ${pin.reviewExpression}`; answers.append(item); }); const transcript = document.createElement('ol'); transcript.className = 'academy-holiday-tape-transcript'; model.payload.transcript.forEach(line => { const item = document.createElement('li'); item.textContent = `${line.speaker}: ${line.text}`; transcript.append(item); }); section.append(heading, answers, transcript); return section; }
function responseFromForm(model: HolidayItineraryTapeModel, form: HTMLFormElement): HolidayItineraryTapeResponse | null { const answers = model.payload.pins.map(pin => { const value = new FormData(form).get(`${model.id}:${pin.id}`); return typeof value === 'string' && ['speaker-a', 'speaker-b'].includes(value) ? { pinId: pin.id, speakerId: value as 'speaker-a' | 'speaker-b' } : null; }); return answers.every((answer): answer is HolidayItineraryTapeResponse['answers'][number] => answer !== null) ? { answers } : null; }
