import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import {
    hostedAppSitemapRoutes,
    internalDocsExcludeGlobs,
    isInternalDocPath,
    navigationRoutes,
    sitemapItemsForRoutes,
    sitemapRouteKey,
    withHostedAppSitemapItems,
} from '../../config/docs/published-pages';
import {
    heroStudyLanguages,
    measuredDefinitionLanguageCount,
} from '../../config/docs/product-claims';
import {
    LEGACY_DOC_HASH_REDIRECTS,
    LEGACY_DOC_REDIRECTS,
} from '../../config/docs/legacy-redirects';
import {
    MEMBERSHIP_NAV,
    docsNav,
    hostedShellNavMarkup,
    hostedShellNavRoutes,
    siteNavRoutes,
} from '../../src/reader/app/site-nav';
import { LEARNING_TARGET_ROSTER } from '../../src/reader/languages/roster';
import { learningTargetModuleFor } from '../../src/reader/languages/registry';

const ROOT = process.cwd();
const DOCS = path.join(ROOT, 'docs');

// Every page yomureader.com is meant to publish, as VitePress sitemap urls
// (docs-relative, cleanUrls applied). Anything else under docs/ is a working
// note that must stay in the repo and off the site.
const ACTIVE_PUBLIC_ROUTES = [
    '',
    'api/',
    'changelog',
    'faq',
    'learn/',
    'learn/approach',
    'learn/building-a-core',
    'learn/keeping-words',
    'learn/manga-and-games',
    'learn/reading',
    'learn/reference',
    'learn/staying-with-it',
    'learn/watching',
    'learn/week-one',
    'learn/your-own-setup',
    'local-audio',
    'membership',
    'privacy/',
    // Generated by scripts/settings-reference.mjs; kept honest by
    // tests/reader/settings-reference-page.test.ts.
    'reference/settings',
    'support',
];

const LEGACY_REDIRECT_ROUTES = Object.keys(LEGACY_DOC_REDIRECTS)
    .map(routeFor)
    .sort();

// Static app routes are copied from docs/public rather than routed by
// VitePress. Keep both PDF URL shapes explicit: a reported bare-route 404 must
// not return while the index.html link continues to look healthy.
const PUBLIC_STATIC_ROUTES = [
    { route: '/pdf-reader/', file: 'docs/public/pdf-reader/index.html' },
    { route: '/pdf-reader/index.html', file: 'docs/public/pdf-reader/index.html' },
] as const;

function readProjectFile(file: string): string {
    return readFileSync(path.join(ROOT, file), 'utf8');
}

function docsMarkdownFiles(directory = DOCS): string[] {
    return readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
        const entryPath = path.join(directory, entry.name);
        if (entry.isDirectory()) {
            return entry.name === '.vitepress' ? [] : docsMarkdownFiles(entryPath);
        }
        if (!entry.isFile() || path.extname(entry.name) !== '.md') return [];
        return [path.relative(DOCS, entryPath).split(path.sep).join('/')];
    });
}

function routeFor(relativePath: string): string {
    return relativePath.replace(/(^|\/)index\.md$/, '$1').replace(/\.md$/, '');
}

describe('published docs pages', () => {
    it('publishes both PDF reader URL shapes', () => {
        expect(PUBLIC_STATIC_ROUTES.map(entry => entry.route)).toEqual([
            '/pdf-reader/',
            '/pdf-reader/index.html',
        ]);
        for (const entry of PUBLIC_STATIC_ROUTES) {
            expect(existsSync(path.join(ROOT, entry.file)), `${entry.route} is missing ${entry.file}`).toBe(true);
        }
    });

    it('routes only the user-facing pages', () => {
        const published = docsMarkdownFiles()
            .filter(file => !isInternalDocPath(file))
            .map(routeFor)
            .sort();

        expect(published).toEqual([...ACTIVE_PUBLIC_ROUTES, ...LEGACY_REDIRECT_ROUTES].sort());
    });

    it('keeps engineering notes, QA probes, and reviewer notes off the site', () => {
        const internal = [
            'academy/STATUS.md',
            'academy/shared-study-srs.md',
            'academy/story/dossiers/rie.md',
            'carryover-workstream-2026-07-18.md',
            'dev/browser-store-automation.md',
            'dev/check-exit-code-incident-2026-07-18.md',
            'dev/check-performance.md',
            'multilingual/README.md',
            'multilingual/roster-source.md',
            'nuclear-backlog-2026-07-16.md',
            'operations/cloudflare-data-recovery.md',
            'operations/cloudflare-data-recovery-drill-2026-07-29.md',
            'public/academy/vendor/kanjivg/ATTRIBUTION.md',
            'qa/ANNOTATION-FIX-PROBE-20260715.md',
            'store-review-notes.md',
        ];

        for (const file of internal) {
            expect(isInternalDocPath(file), file).toBe(true);
        }
        for (const file of ['index.md', 'features.md', 'guides/study-setup.md', 'tools/japanese-ocr.md']) {
            expect(isInternalDocPath(file), file).toBe(false);
        }
    });

    it('links every published page from the site navigation', () => {
        // The nav lives in src/reader/app/site-nav.ts so the docs pages and all
        // three hosted shells render one list instead of four that drift.
        // Search both: config.mts still holds the sidebar, and a page reachable
        // from either counts as linked.
        const sources = [
            readProjectFile('docs/.vitepress/config.mts'),
            readProjectFile('src/reader/app/site-nav.ts'),
        ].join('\n');

        for (const route of ACTIVE_PUBLIC_ROUTES) {
            const bare = sitemapRouteKey(route);
            const linked = sources.includes(`link: '/${bare}'`) || sources.includes(`link: '/${bare}/'`);
            expect(linked, `/${bare} is published but nothing links to it`).toBe(true);
        }
    });

    it('keeps every old feature and guide URL as a redirect into the learning path', () => {
        const config = readProjectFile('docs/.vitepress/config.mts');
        expect(config).toContain('legacyDocsRedirect(pageData.relativePath)');
        expect(config).toContain('legacyDocsHashRedirects(pageData.relativePath)');
        expect(config).toContain("'http-equiv': 'refresh'");
        expect(config).toContain('location.replace(target)');

        for (const [file, target] of Object.entries(LEGACY_DOC_REDIRECTS)) {
            expect(existsSync(path.join(DOCS, file)), file).toBe(true);
            expect(sitemapRouteKey(target)).toMatch(/^learn(?:\/|$)/);
            expect(ACTIVE_PUBLIC_ROUTES.map(sitemapRouteKey)).toContain(sitemapRouteKey(target));
        }

        expect(LEGACY_DOC_HASH_REDIRECTS['getting-started.md'])
            .toHaveProperty(
                '#use-desktop-anki-from-a-phone-ipad-or-android',
                '/learn/your-own-setup#use-desktop-anki-from-a-phone-ipad-or-android',
            );
    });

    it('wires the exclusion list and the sitemap filter into the VitePress config', () => {
        const config = readProjectFile('docs/.vitepress/config.mts');

        expect(config).toContain('srcExclude: internalDocsExcludeGlobs');
        expect(config).toContain('sitemapItemsForRoutes(items, linkedRoutes)');
        expect(internalDocsExcludeGlobs).toContain('academy/**/*.md');
    });
});

describe('published product claims', () => {
    it('drives the homepage hero exactly from the shipped term-lookup capability', () => {
        const homepage = readProjectFile('docs/index.md');
        const config = readProjectFile('docs/.vitepress/config.mts');
        const theme = readProjectFile('docs/.vitepress/theme/index.ts');
        const lookupCapableTargetIds = LEARNING_TARGET_ROSTER
            .filter(language => learningTargetModuleFor(language.runtimeLocale)?.capabilities['term-lookup'])
            .map(language => language.id);
        const heroLanguages = heroStudyLanguages();

        expect(homepage).toContain('<YomuLanguageRotator />');
        expect(config).toContain('const hostedHeroStudyLanguages = heroStudyLanguages();');
        expect(config).toContain('__YOMU_HERO_LANGUAGES__: JSON.stringify(hostedHeroStudyLanguages)');
        expect(theme).toContain('const languages = __YOMU_HERO_LANGUAGES__;');
        expect(heroLanguages.map(language => language.id)).toEqual(lookupCapableTargetIds);
        for (const language of heroLanguages) {
            expect(
                learningTargetModuleFor(language.locale)?.capabilities['term-lookup'],
                `homepage claims ${language.id}, but its target Module cannot open term lookups`,
            ).toBe(true);
        }
    });

    it('keeps every lookup-capable picker target backed by published dictionary supply', () => {
        const catalogue = JSON.parse(
            readProjectFile('config/dictionaries/published/v1/catalog.json'),
        ) as {
            entries?: Array<{
                headwordLanguages?: string[];
                distribution?: { state?: string };
            }>;
        };
        const suppliedHeadwordLanguages = new Set(
            (catalogue.entries ?? [])
                .filter(entry => entry.distribution?.state === 'published' || entry.distribution?.state === 'upstream')
                .flatMap(entry => entry.headwordLanguages ?? [])
                .map(language => language.toLowerCase().replace(/_/gu, '-').split('-')[0]),
        );
        const lookupCapableTargets = LEARNING_TARGET_ROSTER
            .filter(language => learningTargetModuleFor(language.runtimeLocale)?.capabilities['term-lookup']);

        expect(lookupCapableTargets.map(language => language.id)).not.toContain('my');
        for (const target of lookupCapableTargets) {
            expect(
                suppliedHeadwordLanguages.has(target.id),
                `${target.id} has term lookup in the picker but zero published dictionary entries`,
            ).toBe(true);
        }
    });

    it('keeps every published "N languages" claim at the measured definition-language count', () => {
        const measuredCount = measuredDefinitionLanguageCount();
        const claims = docsMarkdownFiles()
            .filter(file => !isInternalDocPath(file))
            .flatMap(file => {
                const source = readProjectFile(`docs/${file}`);
                return [...source.matchAll(/\b(\d+)\s+languages?\b/gi)].map(match => ({
                    file,
                    count: Number(match[1]),
                    text: match[0],
                }));
            });

        expect(claims.length).toBeGreaterThan(0);
        for (const claim of claims) {
            expect(
                claim.count,
                `${claim.file} claims "${claim.text}", but ${measuredCount} published learner-language shelves contain a matching definition language`,
            ).toBe(measuredCount);
        }
    });
});

describe('one navbar everywhere', () => {
    const SHELLS = ['docs/public/pdf-reader/index.html', 'docs/public/video-player/index.html'];

    it('stamps the same site nav into every standalone hosted shell', () => {
        // The two static shells are served outside the VitePress theme, so their
        // menus are stamped from the canonical list at build time. A list edit
        // without a rebuild leaves them behind, which is how they ended up
        // pointing Study and Stats at the retired /newtab/ route.
        const expected = hostedShellNavMarkup('../', ' '.repeat(12));

        for (const shell of SHELLS) {
            const source = readProjectFile(shell);
            const start = source.indexOf('<!-- yomu:site-nav:start -->');
            const end = source.indexOf('<!-- yomu:site-nav:end -->');
            expect(start, `${shell} has no site-nav markers`).toBeGreaterThan(0);
            expect(end).toBeGreaterThan(start);
            const stamped = source.slice(start + '<!-- yomu:site-nav:start -->'.length, end).trim();
            expect(stamped, `${shell} is stamped from a stale nav — run scripts/sync-docs-userscript.cjs`)
                .toBe(expected.trim());
        }
    });

    it('keeps Membership carrying target="_self" on every surface', () => {
        // VitePress's router claims in-site link clicks on window and skips any
        // anchor with a target, which is the only reason the membership popover
        // gets to open instead of the router navigating away.
        expect(MEMBERSHIP_NAV.target).toBe('_self');
        expect(docsNav()).toContainEqual({ text: 'Membership', link: '/membership', target: '_self' });

        const membership = hostedShellNavRoutes('/').find(link => link.text === 'Membership');
        expect(membership?.target).toBe('_self');
        for (const shell of SHELLS) {
            expect(readProjectFile(shell)).toContain('<a href="../membership" target="_self" data-site-nav-item');
        }
    });

    it('keeps every nav label\'s Japanese in step with the docs copy map', () => {
        // The static shells read data-nav-ja in applyInterfaceLanguage; Study's
        // renderSiteNavLink chooses route.ja while rendering. The theme's map
        // stays a flat object literal for its own i18n guards to parse, so this
        // assertion stops either mechanism drifting from the docs navbar.
        const themeSource = readProjectFile('docs/.vitepress/theme/index.ts');

        for (const route of siteNavRoutes()) {
            expect(themeSource, `${route.text} has no ja entry in the theme copy map`)
                .toContain(`'${route.text}': '${route.ja}',`);
        }
    });
});

describe('sitemap filtering', () => {
    it('collects same-site routes from nested navigation and ignores externals', () => {
        const routes = navigationRoutes([
            { text: 'Install', link: '/getting-started' },
            { text: 'Stats', link: '/study/?mode=stats' },
            { text: 'Source', link: 'https://github.com/example/repo' },
            { text: 'More', items: [{ text: 'Privacy', link: '/privacy' }] },
        ]);

        expect([...routes].sort()).toEqual(['getting-started', 'privacy', 'study']);
    });

    it('keeps linked pages and drops unlinked ones, index and directory urls alike', () => {
        const routes = navigationRoutes([
            { text: 'Overview', link: '/' },
            { text: 'Privacy', link: '/privacy' },
            { text: 'Apps', link: '/tools/' },
        ]);
        const items = [
            { url: '' },
            { url: 'privacy/' },
            { url: 'tools/' },
            { url: 'nuclear-backlog-2026-07-16' },
        ];

        expect(sitemapItemsForRoutes(items, routes)).toEqual([
            { url: '' },
            { url: 'privacy/' },
            { url: 'tools/' },
        ]);
    });

    // The hosted apps are static files in docs/public, so VitePress never routes
    // them and `transformItems` never sees them: all three were missing from the
    // live sitemap (20 <loc> entries, measured 2026-07-30) while being indexable
    // 200 pages the home page leads with.
    it('adds the hosted app surfaces the sitemap can never discover', () => {
        expect(withHostedAppSitemapItems([{ url: 'faq' }], url => ({ url }))).toEqual([
            { url: 'faq' },
            { url: 'study/' },
            { url: 'video-player/' },
            { url: 'pdf-reader/' },
        ]);
    });

    it('does not duplicate a hosted route that VitePress already published', () => {
        const items = [{ url: 'study' }];
        expect(withHostedAppSitemapItems(items, url => ({ url }))).toEqual([
            { url: 'study' },
            { url: 'video-player/' },
            { url: 'pdf-reader/' },
        ]);
    });

    // Both URL shapes serve, but the index.html form declares the directory form
    // canonical. Linking it told crawlers every internal path was a duplicate.
    it('links hosted apps at the URL they declare canonical, never index.html', () => {
        const linkSources = [
            'docs/index.md',
            'docs/faq.md',
            'docs/support.md',
            'docs/learn/index.md',
            'docs/learn/reading.md',
            'docs/learn/watching.md',
            'docs/learn/reference.md',
            'docs/public/manifest.webmanifest',
        ];
        for (const file of linkSources) {
            expect(readProjectFile(file), `${file} links a self-declared duplicate`)
                .not.toMatch(/(?:pdf-reader|video-player)\/index\.html/);
        }
    });

    it('keeps academy out of the sitemap while it cannot be played', () => {
        expect(hostedAppSitemapRoutes).not.toContain('academy/');
    });
});

// Each hosted shell is hand-maintained HTML rather than a VitePress page, so
// transformHead's per-page metadata never reaches them and they drift one at a
// time. Measured 2026-07-30: /study/ and /video-player/ carried the full set,
// /pdf-reader/ was missing its description and both twitter text fields, and
// /academy/ — the link supporters are sent — had no canonical and no social
// metadata at all, so it unfurled as a bare URL. Parity, not four fixes.
describe('hosted app shell metadata', () => {
    // academy is read from its template: docs/public/academy/index.html is
    // generated from this by scripts/sync-academy.cjs, so the template is where
    // a fix has to land to survive the next sync.
    const SHELL_SOURCES = [
        'docs/public/study/index.html',
        'docs/public/video-player/index.html',
        'docs/public/pdf-reader/index.html',
        'public/academy/index.html',
    ] as const;
    const REQUIRED_PROPERTIES = ['og:type', 'og:site_name', 'og:title', 'og:description', 'og:url', 'og:image'] as const;
    const REQUIRED_NAMES = ['description', 'twitter:card', 'twitter:title', 'twitter:description', 'twitter:image'] as const;

    function metaContent(source: string, attribute: 'name' | 'property', key: string): string | undefined {
        const pattern = new RegExp(`<meta\\s+${attribute}=["']${key.replace(':', '\\:')}["']\\s+content=["']([^"']*)["']`, 'i');
        return source.match(pattern)?.[1];
    }

    for (const shell of SHELL_SOURCES) {
        it(`${shell} declares a canonical URL and the full social set`, () => {
            const source = readProjectFile(shell);
            expect(source, 'no canonical URL').toMatch(/<link\s+rel=["']canonical["']\s+href=["']https:\/\/yomureader\.com\//i);
            for (const key of REQUIRED_PROPERTIES) {
                expect(metaContent(source, 'property', key), `${key} is missing or empty`).toBeTruthy();
            }
            for (const key of REQUIRED_NAMES) {
                expect(metaContent(source, 'name', key), `${key} is missing or empty`).toBeTruthy();
            }
        });

        // /pdf-reader/ shipped <title>Yomu PDF</title> against og:title "Yomu PDF
        // Reader", so the tab and the shared card disagreed about the product name.
        it(`${shell} uses one title in the tab, the card and the tweet`, () => {
            const source = readProjectFile(shell);
            const title = source.match(/<title>([^<]*)<\/title>/i)?.[1]?.trim();
            expect(title, 'no <title>').toBeTruthy();
            expect(metaContent(source, 'property', 'og:title')).toBe(title);
            expect(metaContent(source, 'name', 'twitter:title')).toBe(title);
        });
    }

    // Requested unconditionally by browsers and unfurlers whatever <link
    // rel="icon"> says. It 404ed and served an 11,989-byte HTML error page.
    it('serves a real multi-size favicon.ico at the root', () => {
        const ico = readFileSync(path.join(ROOT, 'docs/public/favicon.ico'));
        expect(ico.readUInt16LE(0), 'not an ICO: reserved field').toBe(0);
        expect(ico.readUInt16LE(2), 'not an ICO: type field').toBe(1);
        expect(ico.readUInt16LE(4), 'expected the 16px and 32px entries').toBe(2);
        // Each directory entry must point at a payload inside the file, or the
        // icon parses as valid and renders blank.
        for (let index = 0; index < 2; index += 1) {
            const entry = 6 + index * 16;
            const length = ico.readUInt32LE(entry + 8);
            const offset = ico.readUInt32LE(entry + 12);
            expect(length).toBeGreaterThan(0);
            expect(offset + length).toBeLessThanOrEqual(ico.length);
        }
    });
});
