import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import {
    internalDocsExcludeGlobs,
    isInternalDocPath,
    navigationRoutes,
    sitemapItemsForRoutes,
    sitemapRouteKey,
} from '../../config/docs/published-pages';
import {
    heroStudyLanguages,
    measuredDefinitionLanguageCount,
} from '../../config/docs/product-claims';
import {
    MEMBERSHIP_NAV,
    docsNav,
    hostedShellNavMarkup,
    hostedShellNavRoutes,
    siteNavRoutes,
} from '../../src/reader/app/site-nav';
import { LEARNING_TARGET_ROSTER } from '../../src/reader/languages/roster';

const ROOT = process.cwd();
const DOCS = path.join(ROOT, 'docs');

// Every page yomureader.com is meant to publish, as VitePress sitemap urls
// (docs-relative, cleanUrls applied). Anything else under docs/ is a working
// note that must stay in the repo and off the site.
const PUBLIC_ROUTES = [
    '',
    'api/',
    'changelog',
    'faq',
    'features',
    'getting-started',
    'guides/',
    'guides/comprehensible-input-youtube',
    'guides/mine-sentences-to-anki',
    'guides/read-manga-in-japanese',
    'guides/study-setup',
    'local-audio',
    'membership',
    'privacy/',
    // Generated by scripts/settings-reference.mjs; kept honest by
    // tests/reader/settings-reference-page.test.ts.
    'reference/settings',
    'support',
    'tools/',
    'tools/furigana-reader',
    'tools/japanese-ocr',
    'tools/japanese-subtitle-reader',
    'tools/kanji-stroke-order',
    'tools/study-page',
    'tools/yomu-gaming',
    'tools/youtube-japanese',
];

// Static app routes are copied from docs/public rather than routed by
// VitePress. Keep both PDF URL shapes explicit: a reported bare-route 404 must
// not return while the index.html link continues to look healthy.
const PUBLIC_STATIC_ROUTES = [
    { route: '/pdf-reader/', file: 'docs/public/pdf-reader/index.html' },
    { route: '/pdf-reader/index.html', file: 'docs/public/pdf-reader/index.html' },
] as const;

function readProjectFile(file: string): string {
    return readFileSync(path.join(ROOT, file), 'utf8');
}

function docsMarkdownFiles(directory = DOCS): string[] {
    return readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
        const entryPath = path.join(directory, entry.name);
        if (entry.isDirectory()) {
            return entry.name === '.vitepress' ? [] : docsMarkdownFiles(entryPath);
        }
        if (!entry.isFile() || path.extname(entry.name) !== '.md') return [];
        return [path.relative(DOCS, entryPath).split(path.sep).join('/')];
    });
}

function routeFor(relativePath: string): string {
    return relativePath.replace(/(^|\/)index\.md$/, '$1').replace(/\.md$/, '');
}

describe('published docs pages', () => {
    it('publishes both PDF reader URL shapes', () => {
        expect(PUBLIC_STATIC_ROUTES.map(entry => entry.route)).toEqual([
            '/pdf-reader/',
            '/pdf-reader/index.html',
        ]);
        for (const entry of PUBLIC_STATIC_ROUTES) {
            expect(existsSync(path.join(ROOT, entry.file)), `${entry.route} is missing ${entry.file}`).toBe(true);
        }
    });

    it('routes only the user-facing pages', () => {
        const published = docsMarkdownFiles()
            .filter(file => !isInternalDocPath(file))
            .map(routeFor)
            .sort();

        expect(published).toEqual(PUBLIC_ROUTES);
    });

    it('keeps engineering notes, QA probes, and reviewer notes off the site', () => {
        const internal = [
            'academy/STATUS.md',
            'academy/shared-study-srs.md',
            'academy/story/dossiers/rie.md',
            'carryover-workstream-2026-07-18.md',
            'dev/browser-store-automation.md',
            'dev/check-exit-code-incident-2026-07-18.md',
            'dev/check-performance.md',
            'multilingual/README.md',
            'multilingual/roster-source.md',
            'nuclear-backlog-2026-07-16.md',
            'public/academy/vendor/kanjivg/ATTRIBUTION.md',
            'qa/ANNOTATION-FIX-PROBE-20260715.md',
            'store-review-notes.md',
        ];

        for (const file of internal) {
            expect(isInternalDocPath(file), file).toBe(true);
        }
        for (const file of ['index.md', 'features.md', 'guides/study-setup.md', 'tools/japanese-ocr.md']) {
            expect(isInternalDocPath(file), file).toBe(false);
        }
    });

    it('links every published page from the site navigation', () => {
        // The nav lives in src/reader/app/site-nav.ts so the docs pages and all
        // three hosted shells render one list instead of four that drift.
        // Search both: config.mts still holds the sidebar, and a page reachable
        // from either counts as linked.
        const sources = [
            readProjectFile('docs/.vitepress/config.mts'),
            readProjectFile('src/reader/app/site-nav.ts'),
        ].join('\n');

        for (const route of PUBLIC_ROUTES) {
            const bare = sitemapRouteKey(route);
            const linked = sources.includes(`link: '/${bare}'`) || sources.includes(`link: '/${bare}/'`);
            expect(linked, `/${bare} is published but nothing links to it`).toBe(true);
        }
    });

    it('wires the exclusion list and the sitemap filter into the VitePress config', () => {
        const config = readProjectFile('docs/.vitepress/config.mts');

        expect(config).toContain('srcExclude: internalDocsExcludeGlobs');
        expect(config).toContain('sitemapItemsForRoutes(items, linkedRoutes)');
        expect(internalDocsExcludeGlobs).toContain('academy/**/*.md');
    });
});

describe('published product claims', () => {
    it('keeps every homepage hero language inside the shipped target roster', () => {
        const homepage = readProjectFile('docs/index.md');
        const config = readProjectFile('docs/.vitepress/config.mts');
        const theme = readProjectFile('docs/.vitepress/theme/index.ts');
        const shippedTargetIds = new Set<string>(LEARNING_TARGET_ROSTER.map(language => language.id));
        const heroLanguages = heroStudyLanguages();
        const unsupported = heroLanguages
            .map(language => language.id)
            .filter(language => !shippedTargetIds.has(language));

        expect(homepage).toContain('<YomuLanguageRotator />');
        expect(config).toContain('const hostedHeroStudyLanguages = heroStudyLanguages();');
        expect(config).toContain('__YOMU_HERO_LANGUAGES__: JSON.stringify(hostedHeroStudyLanguages)');
        expect(theme).toContain('const languages = __YOMU_HERO_LANGUAGES__;');
        expect(
            unsupported,
            `homepage claims unsupported study target(s): ${unsupported.join(', ')}`,
        ).toEqual([]);
    });

    it('keeps every published "N languages" claim at the measured definition-language count', () => {
        const measuredCount = measuredDefinitionLanguageCount();
        const claims = docsMarkdownFiles()
            .filter(file => !isInternalDocPath(file))
            .flatMap(file => {
                const source = readProjectFile(`docs/${file}`);
                return [...source.matchAll(/\b(\d+)\s+languages?\b/gi)].map(match => ({
                    file,
                    count: Number(match[1]),
                    text: match[0],
                }));
            });

        expect(claims.length).toBeGreaterThan(0);
        for (const claim of claims) {
            expect(
                claim.count,
                `${claim.file} claims "${claim.text}", but ${measuredCount} published learner-language shelves contain a matching definition language`,
            ).toBe(measuredCount);
        }
    });
});

describe('one navbar everywhere', () => {
    const SHELLS = ['docs/public/pdf-reader/index.html', 'docs/public/video-player/index.html'];

    it('stamps the same site nav into every standalone hosted shell', () => {
        // The two static shells are served outside the VitePress theme, so their
        // menus are stamped from the canonical list at build time. A list edit
        // without a rebuild leaves them behind, which is how they ended up
        // pointing Study and Stats at the retired /newtab/ route.
        const expected = hostedShellNavMarkup('../', ' '.repeat(12));

        for (const shell of SHELLS) {
            const source = readProjectFile(shell);
            const start = source.indexOf('<!-- yomu:site-nav:start -->');
            const end = source.indexOf('<!-- yomu:site-nav:end -->');
            expect(start, `${shell} has no site-nav markers`).toBeGreaterThan(0);
            expect(end).toBeGreaterThan(start);
            const stamped = source.slice(start + '<!-- yomu:site-nav:start -->'.length, end).trim();
            expect(stamped, `${shell} is stamped from a stale nav — run scripts/sync-docs-userscript.cjs`)
                .toBe(expected.trim());
        }
    });

    it('keeps Membership carrying target="_self" on every surface', () => {
        // VitePress's router claims in-site link clicks on window and skips any
        // anchor with a target, which is the only reason the membership popover
        // gets to open instead of the router navigating away.
        expect(MEMBERSHIP_NAV.target).toBe('_self');
        expect(docsNav()).toContainEqual({ text: 'Membership', link: '/membership', target: '_self' });

        const membership = hostedShellNavRoutes('/').find(link => link.text === 'Membership');
        expect(membership?.target).toBe('_self');
        for (const shell of SHELLS) {
            expect(readProjectFile(shell)).toContain('<a href="../membership" target="_self" data-site-nav-item');
        }
    });

    it('keeps every nav label\'s Japanese in step with the docs copy map', () => {
        // The static shells read data-nav-ja in applyInterfaceLanguage; Study's
        // renderSiteNavLink chooses route.ja while rendering. The theme's map
        // stays a flat object literal for its own i18n guards to parse, so this
        // assertion stops either mechanism drifting from the docs navbar.
        const themeSource = readProjectFile('docs/.vitepress/theme/index.ts');

        for (const route of siteNavRoutes()) {
            expect(themeSource, `${route.text} has no ja entry in the theme copy map`)
                .toContain(`'${route.text}': '${route.ja}',`);
        }
    });
});

describe('sitemap filtering', () => {
    it('collects same-site routes from nested navigation and ignores externals', () => {
        const routes = navigationRoutes([
            { text: 'Install', link: '/getting-started' },
            { text: 'Stats', link: '/study/?mode=stats' },
            { text: 'Source', link: 'https://github.com/example/repo' },
            { text: 'More', items: [{ text: 'Privacy', link: '/privacy' }] },
        ]);

        expect([...routes].sort()).toEqual(['getting-started', 'privacy', 'study']);
    });

    it('keeps linked pages and drops unlinked ones, index and directory urls alike', () => {
        const routes = navigationRoutes([
            { text: 'Overview', link: '/' },
            { text: 'Privacy', link: '/privacy' },
            { text: 'Apps', link: '/tools/' },
        ]);
        const items = [
            { url: '' },
            { url: 'privacy/' },
            { url: 'tools/' },
            { url: 'nuclear-backlog-2026-07-16' },
        ];

        expect(sitemapItemsForRoutes(items, routes)).toEqual([
            { url: '' },
            { url: 'privacy/' },
            { url: 'tools/' },
        ]);
    });
});
