import { afterEach, expect, it, vi } from 'vitest';
import { observePageAnnotationContrast } from '../../src/reader/dom/page-annotation-contrast-observer';
import { refreshReaderWordContrast } from '../../src/reader/dom/word-contrast';

vi.mock('../../src/reader/dom/word-contrast', () => ({ refreshReaderWordContrast: vi.fn() }));
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.clearAllMocks(); });

it('batches page theme changes, ignores word styles and stops on abort', async () => {
    let queued: FrameRequestCallback | undefined;
    vi.stubGlobal('requestAnimationFrame', vi.fn((callback: FrameRequestCallback) => { queued = callback; return 1; }));
    const cancel = vi.fn();
    vi.stubGlobal('cancelAnimationFrame', cancel);
    const media = new EventTarget();
    vi.stubGlobal('matchMedia', () => media);
    const controller = new AbortController();
    observePageAnnotationContrast(controller.signal);
    document.documentElement.classList.toggle('test-night');
    document.body.style.backgroundColor = '#101418';
    await Promise.resolve();
    media.dispatchEvent(new Event('change'));
    expect(requestAnimationFrame).toHaveBeenCalledTimes(1);
    queued!(0);
    expect(refreshReaderWordContrast).toHaveBeenCalledTimes(1);
    const word = document.createElement('span');
    document.body.append(word);
    word.style.color = 'white';
    await Promise.resolve();
    expect(requestAnimationFrame).toHaveBeenCalledTimes(1);
    const oldBody = document.body;
    const replacement = document.createElement('body');
    oldBody.replaceWith(replacement);
    await Promise.resolve();
    queued!(0);
    expect(refreshReaderWordContrast).toHaveBeenCalledTimes(2);
    replacement.style.color = 'white';
    await Promise.resolve();
    controller.abort();
    expect(cancel).toHaveBeenCalledWith(1);
    queued!(0);
    media.dispatchEvent(new Event('change'));
    document.body.style.backgroundColor = 'white';
    await Promise.resolve();
    expect(refreshReaderWordContrast).toHaveBeenCalledTimes(2);
    expect(requestAnimationFrame).toHaveBeenCalledTimes(3);
    replacement.replaceWith(oldBody);
    word.remove();
    document.body.removeAttribute('style');
    document.documentElement.classList.remove('test-night');
});
