import type { ActivityController, ActivityEvaluation, ActivityHost } from '../../domain/activity-runtime';
import { localizedNodes, setPending, showEvaluation, statusRegion } from '../activity-kit/shared';
import { renderInspectableSourceVisual } from '../source-visual';
import type { ListeningHingeModel, ListeningHingeResponse, ListeningHingeSourceVisual } from './manifest';

export function renderListeningHinge(model: ListeningHingeModel, host: ActivityHost, submit: (response: ListeningHingeResponse) => Promise<ActivityEvaluation>): ActivityController {
    const lifecycle = new AbortController(); const root = document.createElement('section'); root.className = 'academy-activity academy-listening-hinge'; root.dataset.activityId = model.id;
    const heading = document.createElement('h2'); heading.id = `${model.id}-prompt`; heading.tabIndex = -1; heading.append(...localizedNodes(model.prompt));
    const teaching = document.createElement('section'); teaching.className = 'academy-listening-hinge-teaching'; teaching.dataset.lessonPhase = 'teaching'; model.payload.teaching.forEach(step => { const card = document.createElement('article'); const title = document.createElement('h3'); title.append(...localizedNodes(step.title)); const pattern = document.createElement('p'); pattern.className = 'academy-listening-hinge-pattern academy-japanese'; pattern.lang = 'ja'; pattern.textContent = step.pattern; const instruction = document.createElement('p'); instruction.append(...localizedNodes(step.instruction)); card.append(title, pattern, instruction); teaching.append(card); });
    const sources = document.createElement('section'); sources.className = 'academy-listening-hinge-sources'; sources.dataset.lessonPhase = 'source-reference'; sources.append(renderVisual(model.provenance.moodle.vocabularySheet, host.language), renderVisual(model.provenance.moodle.listeningSheet, host.language));
    const audio = document.createElement('audio'); audio.className = 'academy-listening-hinge-audio'; audio.controls = true; audio.preload = 'metadata'; audio.src = model.provenance.moodle.audio.url; audio.dataset.sourceSha256 = model.provenance.moodle.audio.payloadSha256; audio.setAttribute('aria-label', host.language === 'ja' ? 'Moodle B-24 原音声' : 'Original Moodle B-24 audio');
    const form = document.createElement('form'); form.className = 'academy-listening-hinge-form'; form.setAttribute('aria-labelledby', heading.id); const board = document.createElement('ol'); board.className = 'academy-listening-hinge-board'; model.payload.prompts.forEach(prompt => board.append(renderHinge(model, prompt, host.language))); const check = document.createElement('button'); check.type = 'submit'; check.className = 'academy-button academy-button-primary academy-listening-hinge-check'; check.textContent = host.language === 'ja' ? '三つのヒンジを確認する' : 'Check the three hinges'; form.append(board, check);
    const key = renderAnswerKey(model, host.language); const status = statusRegion('academy-kit-feedback academy-listening-hinge-feedback'); root.append(heading, teaching, sources, audio, form, key, status); host.replace(root);
    form.addEventListener('submit', event => { event.preventDefault(); const response = responseFromForm(model, form); if (!response) { const message = host.language === 'ja' ? '三つのヒンジすべてを左右どちらかにしてください。' : 'Set all three hinges to either left or right.'; status.textContent = message; host.announce(message); return; } setPending(root, true); void submit(response).then(evaluation => { root.dataset.outcome = evaluation.result.outcome; key.hidden = false; showEvaluation(status, evaluation, host); if (evaluation.result.outcome === 'lapse') setPending(root, false); }).catch(error => { setPending(root, false); status.textContent = error instanceof Error ? error.message : String(error); }); }, { signal: lifecycle.signal });
    return { focus() { form.querySelector<HTMLInputElement>('input')?.focus(); }, dispose() { lifecycle.abort(); root.remove(); } };
}
function renderVisual(visual: ListeningHingeSourceVisual, language: 'ja' | 'en' | undefined): HTMLElement { return renderInspectableSourceVisual(visual, language, 'academy-listening-hinge-source'); }
function renderHinge(model: ListeningHingeModel, prompt: ListeningHingeModel['payload']['prompts'][number], language: 'ja' | 'en' | undefined): HTMLElement { const item = document.createElement('li'); item.className = 'academy-listening-hinge-item'; item.dataset.sourceQuestionId = prompt.sourceQuestionId; const fieldset = document.createElement('fieldset'); const legend = document.createElement('legend'); legend.textContent = language === 'ja' ? `B-24 ヒンジ ${prompt.sourceOrder}` : `B-24 hinge ${prompt.sourceOrder}`; fieldset.append(legend); (['left', 'right'] as const).forEach(optionId => { const label = document.createElement('label'); const input = document.createElement('input'); input.type = 'radio'; input.name = `${model.id}:${prompt.id}`; input.value = optionId; input.required = true; const side = document.createElement('span'); side.textContent = optionId === 'left' ? (language === 'ja' ? '左' : 'Left') : (language === 'ja' ? '右' : 'Right'); label.append(input, side); fieldset.append(label); }); item.append(fieldset); return item; }
function renderAnswerKey(model: ListeningHingeModel, language: 'ja' | 'en' | undefined): HTMLElement { const section = document.createElement('section'); section.className = 'academy-listening-hinge-key'; section.dataset.answerVisibility = 'after-attempt'; section.hidden = true; const heading = document.createElement('h3'); heading.textContent = language === 'ja' ? '試したあとの B-24 の聞き取り' : 'B-24 listening notes after your attempt'; const answers = document.createElement('ol'); model.payload.prompts.forEach(prompt => { const item = document.createElement('li'); item.textContent = `${prompt.sourceOrder}. ${prompt.reviewExpression}`; answers.append(item); }); section.append(heading, answers); return section; }
function responseFromForm(model: ListeningHingeModel, form: HTMLFormElement): ListeningHingeResponse | null { const answers = model.payload.prompts.map(prompt => { const value = new FormData(form).get(`${model.id}:${prompt.id}`); return typeof value === 'string' && ['left', 'right'].includes(value) ? { promptId: prompt.id, optionId: value as 'left' | 'right' } : null; }); return answers.every((answer): answer is ListeningHingeResponse['answers'][number] => answer !== null) ? { answers } : null; }
