import { isAcademyCastMemberId, type AcademyCastMemberId } from './cast-registry';

export const ACADEMY_CAST_HOUSE_STYLE = {
    anchor: 'rie',
    summary: 'Warm hand-drawn animation with graphic visual-novel clarity.',
    line: 'Clean tapered ink lines with confident silhouettes and simplified interior detail.',
    colour: 'Warm natural skin, deep navy, moss, coral, paper cream, teal, and restrained gold.',
    rendering: 'Two-dimensional painted colour planes, soft texture, expressive adult faces, and no photographic skin detail.',
    staging: 'Transparent full or three-quarter body cutout with readable hands, face, and one purposeful action.',
    reject: [
        'photorealism or uncanny skin texture',
        '3D-rendered lighting',
        'generic fashion-catalogue posing',
        'baked checkerboard or background plate',
        'cropped hands or feet when the pose needs them',
        'text, labels, signatures, or watermarks',
    ],
} as const;

export const REQUIRED_CAST_PERFORMANCES = [
    'neutral',
    'encouraging-listening',
    'happy',
    'thoughtful',
    'determined',
    'surprised-shocked',
    'sad-vulnerable',
] as const;

export type AcademyCastPerformance = typeof REQUIRED_CAST_PERFORMANCES[number];

export interface AcademyCastIdentityLock {
    readonly identityKey: string;
    readonly displayName: string;
    readonly assetFolder: AcademyCastMemberId;
    readonly visualLock: string;
    readonly wardrobeLock: string;
    readonly reject: readonly string[];
    readonly source: 'owner-approved-anchor' | 'established-cast-design' | 'original-yomu-design';
    readonly disposition: 'retain-anchor' | 'regenerate-house-style';
    readonly requiredPerformances: readonly AcademyCastPerformance[];
}

const performances = REQUIRED_CAST_PERFORMANCES;

/**
 * Learner-facing cast identity authority.
 *
 * Internal IDs remain stable for saves (`angel` is Onke), while every asset
 * must resolve through this table before it can appear in the People journal,
 * a story scene, or a lesson. No directory scan or filename similarity is an
 * acceptable substitute for this mapping.
 */
export const ACADEMY_CAST_IDENTITY_LOCKS = {
    rie: {
        identityKey: 'rie-sensei-navy-cream',
        displayName: 'Rie',
        assetFolder: 'rie',
        visualLock: 'Japanese woman with a soft dark bun, warm tired-bright eyes, fine glasses, and a composed teacher presence.',
        wardrobeLock: 'Navy blouse and trousers, cream long cardigan, blue lanyard, small jewellery, and a practical notebook.',
        reject: ['loose long hair', 'school uniform', 'photographic face', 'different glasses'],
        source: 'owner-approved-anchor',
        disposition: 'retain-anchor',
        requiredPerformances: performances,
    },
    henry: {
        identityKey: 'henry-messy-brown-indigo',
        displayName: 'Henry',
        assetFolder: 'henry',
        visualLock: 'White man with messy short brown hair, a slightly sleepless face, and an alert technical energy.',
        wardrobeLock: 'Casual indigo layers with a practical laptop bag or notebook only when the scene calls for it.',
        reject: ['photographic face', 'formal suit', 'slick hair', 'generic heroic physique'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    aakash: {
        identityKey: 'aakash-short-black-hair-beard-indigo',
        displayName: 'Aakash',
        assetFolder: 'aakash',
        visualLock: 'South Asian man with short black hair, a neat beard, warm eyes, and a friendly broad smile.',
        wardrobeLock: 'Burgundy hoodie under a dark indigo denim jacket; hat-free default; small cat pin may recur.',
        reject: ['photographic skin', 'baseball cap by default', 'clean-shaven face', 'different face shape'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    alex: {
        identityKey: 'alex-short-brown-understated',
        displayName: 'Alex',
        assetFolder: 'alex',
        visualLock: 'White man with short brown hair, an understated expression, and an ordinary adult build.',
        wardrobeLock: 'Quiet practical layers in navy, grey, and muted green.',
        reject: ['flashy fashion', 'beard unless present in the locked neutral', 'teenage proportions'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    tom: {
        identityKey: 'tom-blond-fuller-clean-shaven',
        displayName: 'Tom',
        assetFolder: 'tom',
        visualLock: 'White man with clearly blond hair, a fuller friendly face, and no beard.',
        wardrobeLock: 'Relaxed casual layers with subtle game-fan detail only when story-backed.',
        reject: ['dark hair', 'beard', 'photographic face', 'narrow angular face'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    sam: {
        identityKey: 'sam-close-cropped-chestnut-athletic',
        displayName: 'Sam',
        assetFolder: 'sam',
        visualLock: 'Relaxed athletic White man with a very close-cropped chestnut crew cut and minimal crown or side volume.',
        wardrobeLock: 'Clean casual sportswear or a simple overshirt in moss, navy, and cream.',
        reject: ['long or swept hair', 'high-volume crown', 'beard', 'photographic face'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    francis: {
        identityKey: 'francis-soft-sand-hair-no-glasses',
        displayName: 'Francis',
        assetFolder: 'francis',
        visualLock: 'Gentle White man with soft sand-brown hair, a calm rounded face, and no glasses.',
        wardrobeLock: 'Soft knit layers in tea, sage, and navy tones.',
        reject: ['Tom identity', 'glasses', 'hard angular face', 'photographic face'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    shin: {
        identityKey: 'shin-short-black-round-glasses',
        displayName: 'Shin',
        assetFolder: 'shin',
        visualLock: 'East Asian man with short black hair, round glasses, and a precise but approachable expression.',
        wardrobeLock: 'Simple smart-casual layers with a small menu or kanji notebook only when story-backed.',
        reject: ['no glasses', 'long hair', 'caricatured features'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    jodi: {
        identityKey: 'jodi-silver-streaked-bob',
        displayName: 'Jodi',
        assetFolder: 'jodi',
        visualLock: 'Older White woman with a silver-streaked bob, visible age, and a kind observant face.',
        wardrobeLock: 'Elegant practical cardigan and scarf combinations in ink, plum, and cream.',
        reject: ['de-aged face', 'teenage proportions', 'long dark hair'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    christian: {
        identityKey: 'christian-black-ponytail-athletic',
        displayName: 'Christian',
        assetFolder: 'christian',
        visualLock: 'Black man with tied-back hair, an athletic presence, and an easy expressive face.',
        wardrobeLock: 'Practical athletic layers; recorder or small desk fan only in their specific scenes.',
        reject: ['short blond hair', 'different ethnicity', 'photographic face', 'formal suit'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    jenny: {
        identityKey: 'jenny-round-face-brown-hair',
        displayName: 'Jenny',
        assetFolder: 'jenny',
        visualLock: 'Slim woman with brown hair, a noticeably round warm face, and a composed observant presence.',
        wardrobeLock: 'Soft textured layers in indigo, berry, and cream; knitting only when the scene uses it.',
        reject: ['narrow pointed face', 'broad or heavy-set body', 'blond or black hair', 'photographic face', 'shoujo-child proportions'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    robert: {
        identityKey: 'robert-brown-side-part-square-glasses',
        displayName: 'Robert',
        assetFolder: 'robert',
        visualLock: 'White man with side-parted brown hair, square glasses, and a hospitable adult presence.',
        wardrobeLock: 'Smart-casual restaurant-ready layers without looking corporate.',
        reject: ['round glasses', 'wild hair', 'photographic face', 'caricature'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    mika: {
        identityKey: 'mika-blond-male-headphones',
        displayName: 'Mika',
        assetFolder: 'mika',
        visualLock: 'Blond White/European man with a shy thoughtful expression; unmistakably male.',
        wardrobeLock: 'Dark overshirt over a moss knit, black over-ear headphones around his neck.',
        reject: ['female presentation', 'dark hair', 'Mira umbrella outfit', 'photographic face'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    sophie: {
        identityKey: 'sophie-long-dark-hair-no-glasses',
        displayName: 'Sophie',
        assetFolder: 'sophie',
        visualLock: 'Chinese/Hong Kong woman with long dark hair, no glasses, and an intelligent self-possessed expression.',
        wardrobeLock: 'Crisp layered outfit in ink blue, cream, and a restrained coral accent; book or notes only when needed.',
        reject: ['glasses', 'short blond hair', 'photographic face'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    xingyu: {
        identityKey: 'xingyu-short-hair-round-glasses',
        displayName: 'Xingyu',
        assetFolder: 'xingyu',
        visualLock: 'East Asian woman with short hair or a neat undercut, round glasses, and joyful singing energy.',
        wardrobeLock: 'Graphic but practical music-loving layers; microphone only in performance scenes.',
        reject: ['male presentation', 'long blond hair', 'Mika headphones identity', 'photographic face'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    angel: {
        identityKey: 'onke-long-dark-hair-organised',
        displayName: 'Onke',
        assetFolder: 'angel',
        visualLock: 'East or Southeast Asian woman with long straight dark hair and an organised, generous presence.',
        wardrobeLock: 'Clean practical layers with a project notebook or tablet only in planning scenes.',
        reject: ['learner-facing name Angel', 'short blond hair', 'photographic face'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    stasi: {
        identityKey: 'stasi-auburn-waves-round-glasses',
        displayName: 'Stasi',
        assetFolder: 'stasi',
        visualLock: 'Woman with red or auburn wavy hair, round glasses, and a visually expressive adult face.',
        wardrobeLock: 'Artful layered outfit in rust, teal, charcoal, and cream.',
        reject: ['straight black hair', 'no glasses', 'photographic face', 'caricature proportions'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    ruparna: {
        identityKey: 'ruparna-long-dark-hair-thoughtful',
        displayName: 'Ruparna',
        assetFolder: 'ruparna',
        visualLock: 'South Asian woman with long dark hair and a thoughtful, perceptive presence.',
        wardrobeLock: 'Elegant practical layers in plum, ink, and warm cream.',
        reject: ['stale v1 caricature', 'short blond hair', 'photographic face'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    rose: {
        identityKey: 'rose-auburn-headband-pink-cardigan',
        displayName: 'Rose',
        assetFolder: 'rose',
        visualLock: 'Woman with warm auburn-brown hair, a simple headband, and the grounded friendly face of the original Rose design.',
        wardrobeLock: 'Pink cardigan over practical cream and earth-toned layers.',
        reject: ['holding a rose as an identity prop', 'silver-haired replacement', 'Nanako identity', 'photographic face'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    peter: {
        identityKey: 'peter-quiet-observer',
        displayName: 'Peter',
        assetFolder: 'peter',
        visualLock: 'Quiet adult male classmate with an observant, understated face and an unshowy silhouette.',
        wardrobeLock: 'Simple well-kept layers in charcoal, moss, and blue.',
        reject: ['hero pose', 'photographic face', 'exaggerated emotion'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    felix: {
        identityKey: 'felix-curly-dark-blond-glasses',
        displayName: 'Felix',
        assetFolder: 'felix',
        visualLock: 'White man with glasses and longer curly dark-blond to light-brown hair.',
        wardrobeLock: 'Relaxed layered outfit with a small cat detail only when appropriate.',
        reject: ['short straight black hair', 'no glasses', 'photographic face'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    shaun: {
        identityKey: 'shaun-established-neutral',
        displayName: 'Shaun',
        assetFolder: 'shaun',
        visualLock: 'Adult male classmate whose current approved identity silhouette remains the anchor while the rendering is harmonised.',
        wardrobeLock: 'Unshowy modern casual layers in ink, slate, and cream.',
        reject: ['pixel filter', 'photographic face', 'identity drift from the locked neutral'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    tom2: {
        identityKey: 'second-tom-tall-dark-brown-reserved',
        displayName: 'Tom',
        assetFolder: 'tom2',
        visualLock: 'The second Tom: tall adult White man with dark-brown hair, average build, and a reserved, slightly mysterious expression.',
        wardrobeLock: 'Dark practical layers and a black notebook; visually distinct from blond Tom.',
        reject: ['blond Tom identity', 'photographic face', 'generic model pose', 'beard unless locked later'],
        source: 'original-yomu-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    steve: {
        identityKey: 'steve-older-family-writer',
        displayName: 'Steve',
        assetFolder: 'steve',
        visualLock: 'Older man with a warm family-minded presence and a face that reads clearly as older than the core class.',
        wardrobeLock: 'Comfortable smart-casual layers suitable for everyday family life.',
        reject: ['de-aged face', 'teenage proportions', 'photographic face'],
        source: 'established-cast-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    nanako: {
        identityKey: 'nanako-warm-native-speaker',
        displayName: 'Nanako',
        assetFolder: 'nanako',
        visualLock: 'Japanese woman with concise warmth, gentle humour, and a clearly distinct identity from Rose and Mira.',
        wardrobeLock: 'Relaxed contemporary layers suitable for travel, reading, and group-chat reunion scenes.',
        reject: ['Rose headband identity', 'Mira cap and umbrella', 'duplicate face fragment', 'photographic face'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    mira: {
        identityKey: 'mira-blond-cap-blue-hoodie-umbrella',
        displayName: 'Mira',
        assetFolder: 'mira',
        visualLock: 'Fair-skinned adult woman with shoulder-length warm-blond hair, a black cap, and a direct playful expression.',
        wardrobeLock: 'Oversized blue hoodie, cream wide-leg trousers, pale trainers, and a clear folded umbrella.',
        reject: ['Miller identity', 'Mika male headphones identity', 'Rose identity', 'photographic face'],
        source: 'owner-approved-anchor',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    miller: {
        identityKey: 'miller-textbook-legend-kobe',
        displayName: 'Miller',
        assetFolder: 'miller',
        visualLock: 'Original Yomu adult office-worker interpretation, immediately distinct from Mira and the real class.',
        wardrobeLock: 'Practical business-casual travel clothes with a small Kobe-bound bag only in the recurring gag.',
        reject: ['Mira cap and umbrella identity', 'copied textbook illustration', 'photographic face'],
        source: 'original-yomu-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    tawapon: {
        identityKey: 'tawapon-eternal-student',
        displayName: 'Tawapon',
        assetFolder: 'tawapon',
        visualLock: 'Original Yomu adult student who treats improbable exercises as ordinary life.',
        wardrobeLock: 'Cheerful practical campus layers with a well-used workbook.',
        reject: ['copied textbook illustration', 'child proportions', 'photographic face'],
        source: 'original-yomu-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    mary: {
        identityKey: 'mary-textbook-legend',
        displayName: 'Mary',
        assetFolder: 'mary',
        visualLock: 'Original Yomu adult exchange-student interpretation with bright, grounded confidence.',
        wardrobeLock: 'Contemporary campus layers in cream, coral, navy, and moss.',
        reject: ['copied textbook illustration', 'schoolchild proportions', 'photographic face'],
        source: 'original-yomu-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
    takeshi: {
        identityKey: 'takeshi-textbook-legend',
        displayName: 'Takeshi',
        assetFolder: 'takeshi',
        visualLock: 'Original Yomu adult student interpretation with friendly, lightly comic confidence.',
        wardrobeLock: 'Contemporary everyday Japanese campus layers.',
        reject: ['copied textbook illustration', 'child proportions', 'photographic face'],
        source: 'original-yomu-design',
        disposition: 'regenerate-house-style',
        requiredPerformances: performances,
    },
} as const satisfies Readonly<Record<AcademyCastMemberId, AcademyCastIdentityLock>>;

export function getAcademyCastIdentityLock(id: string): AcademyCastIdentityLock {
    if (!isAcademyCastMemberId(id)) throw new TypeError(`Unknown Academy cast identity lock: ${id}.`);
    return ACADEMY_CAST_IDENTITY_LOCKS[id];
}
