// Generated by scripts/academy-learning-art-usage.mjs. Do not edit by hand.
export const ACADEMY_LEARNING_ART_RUNTIME_ASSETS = {
    "learning.hiragana-anchor.a": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-a.webp"
        }
    },
    "learning.hiragana-anchor.chi": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-chi.webp"
        }
    },
    "learning.hiragana-anchor.e": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-e.webp"
        }
    },
    "learning.hiragana-anchor.fu": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-fu.webp"
        }
    },
    "learning.hiragana-anchor.ha": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ha.webp"
        }
    },
    "learning.hiragana-anchor.he": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-he.webp"
        }
    },
    "learning.hiragana-anchor.hi": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-hi.webp"
        }
    },
    "learning.hiragana-anchor.ho": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ho.webp"
        }
    },
    "learning.hiragana-anchor.i": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-i.webp"
        }
    },
    "learning.hiragana-anchor.ka": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ka.webp"
        }
    },
    "learning.hiragana-anchor.ke": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ke.webp"
        }
    },
    "learning.hiragana-anchor.ki": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ki.webp"
        }
    },
    "learning.hiragana-anchor.ko": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ko.webp"
        }
    },
    "learning.hiragana-anchor.ku": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ku.webp"
        }
    },
    "learning.hiragana-anchor.ma": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ma.webp"
        }
    },
    "learning.hiragana-anchor.me": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-me.webp"
        }
    },
    "learning.hiragana-anchor.mi": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-mi.webp"
        }
    },
    "learning.hiragana-anchor.mo": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-mo.webp"
        }
    },
    "learning.hiragana-anchor.mu": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-mu.webp"
        }
    },
    "learning.hiragana-anchor.n": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-n.webp"
        }
    },
    "learning.hiragana-anchor.na": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-na.webp"
        }
    },
    "learning.hiragana-anchor.ne": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ne.webp"
        }
    },
    "learning.hiragana-anchor.ni": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ni.webp"
        }
    },
    "learning.hiragana-anchor.no": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-no.webp"
        }
    },
    "learning.hiragana-anchor.nu": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-nu.webp"
        }
    },
    "learning.hiragana-anchor.o": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-o.webp"
        }
    },
    "learning.hiragana-anchor.ra": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ra.webp"
        }
    },
    "learning.hiragana-anchor.re": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-re.webp"
        }
    },
    "learning.hiragana-anchor.ri": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ri.webp"
        }
    },
    "learning.hiragana-anchor.ro": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ro.webp"
        }
    },
    "learning.hiragana-anchor.ru": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ru.webp"
        }
    },
    "learning.hiragana-anchor.sa": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-sa.webp"
        }
    },
    "learning.hiragana-anchor.se": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-se.webp"
        }
    },
    "learning.hiragana-anchor.shi": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-shi.webp"
        }
    },
    "learning.hiragana-anchor.so": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-so.webp"
        }
    },
    "learning.hiragana-anchor.su": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-su.webp"
        }
    },
    "learning.hiragana-anchor.ta": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ta.webp"
        }
    },
    "learning.hiragana-anchor.te": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-te.webp"
        }
    },
    "learning.hiragana-anchor.to": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-to.webp"
        }
    },
    "learning.hiragana-anchor.tsu": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-tsu.webp"
        }
    },
    "learning.hiragana-anchor.u": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-u.webp"
        }
    },
    "learning.hiragana-anchor.wa": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-wa.webp"
        }
    },
    "learning.hiragana-anchor.wo": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-wo.webp"
        }
    },
    "learning.hiragana-anchor.ya": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-ya.webp"
        }
    },
    "learning.hiragana-anchor.yo": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-yo.webp"
        }
    },
    "learning.hiragana-anchor.yu": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson-zero:kana-practice",
            "lesson-zero:hiragana-visual-anchor"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/lesson-zero/hiragana-anchors/hira-yu.webp"
        }
    },
    "learning.vocabulary-pictograph.class": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson:l1-l01:vocabulary-pictographs",
            "lesson-zero:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/vocabulary-pictographs/class.webp"
        }
    },
    "learning.vocabulary-pictograph.company-employee": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson:l1-l01:vocabulary-pictographs",
            "lesson-zero:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/vocabulary-pictographs/company-employee.webp"
        }
    },
    "learning.vocabulary-pictograph.country": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson:l1-l01:vocabulary-pictographs",
            "lesson-zero:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/vocabulary-pictographs/country.webp"
        }
    },
    "learning.vocabulary-pictograph.name": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson:l1-l01:vocabulary-pictographs",
            "lesson-zero:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/vocabulary-pictographs/name.webp"
        }
    },
    "learning.vocabulary-pictograph.person": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson:l1-l01:vocabulary-pictographs",
            "lesson-zero:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/vocabulary-pictographs/person.webp"
        }
    },
    "learning.vocabulary-pictograph.student": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson:l1-l01:vocabulary-pictographs",
            "lesson-zero:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/vocabulary-pictographs/student.webp"
        }
    },
    "learning.vocabulary-pictograph.teacher": {
        "kind": "learning-visual",
        "status": "approved",
        "runtimeHomes": [
            "lesson:l1-l01:vocabulary-pictographs",
            "lesson-zero:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "default": "/academy/art/vocabulary-pictographs/teacher.webp"
        }
    }
} as const;
