export interface AcademyStoryArtBinding {
    readonly assetId: string;
    readonly sceneId: string;
    readonly nodeId: string;
    readonly cueId: string;
    readonly wide: `/academy/art/events/${string}.webp`;
    readonly mobile: `/academy/art/events/${string}.webp`;
}

/**
 * Generated by npm run academy:art:story:promote. Every entry has passed
 * viewport QA and resolves to an authored story node before reaching runtime.
 */
export const ACADEMY_STORY_ART_BY_NODE = {
    "node:blank-atlas:covered-table": {
        "assetId": "event.story.blank-atlas-arrival.covered-atlas",
        "sceneId": "scene:blank-atlas:arrival-greetings",
        "nodeId": "node:blank-atlas:covered-table",
        "cueId": "cue:covered-atlas-open-chair",
        "wide": "/academy/art/events/blank-atlas-arrival__covered-atlas-open-chair__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-arrival__covered-atlas-open-chair__mobile__v001.webp"
    },
    "node:blank-atlas:first-uncover": {
        "assetId": "event.story.blank-atlas-arrival.atlas-uncovered",
        "sceneId": "scene:blank-atlas:arrival-greetings",
        "nodeId": "node:blank-atlas:first-uncover",
        "cueId": "cue:atlas-uncovered-unlit",
        "wide": "/academy/art/events/blank-atlas-arrival__atlas-uncovered-unlit__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-arrival__atlas-uncovered-unlit__mobile__v001.webp"
    },
    "node:blank-atlas:vowel-slots": {
        "assetId": "event.story.blank-atlas-sound-script-map.five-empty-slots",
        "sceneId": "scene:blank-atlas:sound-script-map",
        "nodeId": "node:blank-atlas:vowel-slots",
        "cueId": "cue:five-empty-atlas-slots",
        "wide": "/academy/art/events/blank-atlas-sound-script-map__five-empty-slots__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-sound-script-map__five-empty-slots__mobile__v001.webp"
    },
    "node:blank-atlas:first-line": {
        "assetId": "event.story.blank-atlas-sound-script-map.first-route-line",
        "sceneId": "scene:blank-atlas:sound-script-map",
        "nodeId": "node:blank-atlas:first-line",
        "cueId": "cue:first-route-line-visible",
        "wide": "/academy/art/events/blank-atlas-sound-script-map__first-route-line__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-sound-script-map__first-route-line__mobile__v001.webp"
    },
    "node:blank-atlas:handout-arrives": {
        "assetId": "event.story.blank-atlas-classroom-survival.handout-arrives",
        "sceneId": "scene:blank-atlas:classroom-survival",
        "nodeId": "node:blank-atlas:handout-arrives",
        "cueId": "cue:classroom-handout-on-desk",
        "wide": "/academy/art/events/blank-atlas-classroom-survival__handout-arrives__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-classroom-survival__handout-arrives__mobile__v001.webp"
    },
    "node:blank-atlas:handout-flower": {
        "assetId": "event.story.blank-atlas-classroom-survival.rie-flower-mark",
        "sceneId": "scene:blank-atlas:classroom-survival",
        "nodeId": "node:blank-atlas:handout-flower",
        "cueId": "cue:rie-flower-mark",
        "wide": "/academy/art/events/blank-atlas-classroom-survival__rie-flower-mark__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-classroom-survival__rie-flower-mark__mobile__v001.webp"
    },
    "node:blank-atlas:false-label": {
        "assetId": "event.story.blank-atlas-sentence-frames.two-room-labels",
        "sceneId": "scene:blank-atlas:sentence-frames",
        "nodeId": "node:blank-atlas:false-label",
        "cueId": "cue:atlas-classroom-library-labels",
        "wide": "/academy/art/events/blank-atlas-sentence-frames__two-room-labels__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-sentence-frames__two-room-labels__mobile__v001.webp"
    },
    "node:blank-atlas:label-fixed": {
        "assetId": "event.story.blank-atlas-sentence-frames.classroom-label-fixed",
        "sceneId": "scene:blank-atlas:sentence-frames",
        "nodeId": "node:blank-atlas:label-fixed",
        "cueId": "cue:atlas-classroom-label-fixed",
        "wide": "/academy/art/events/blank-atlas-sentence-frames__classroom-label-fixed__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-sentence-frames__classroom-label-fixed__mobile__v001.webp"
    },
    "node:blank-atlas:name-line": {
        "assetId": "event.story.blank-atlas-useful-vocabulary.name-line",
        "sceneId": "scene:blank-atlas:useful-vocabulary",
        "nodeId": "node:blank-atlas:name-line",
        "cueId": "cue:blank-name-card-and-atlas-line",
        "wide": "/academy/art/events/blank-atlas-useful-vocabulary__name-line__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-useful-vocabulary__name-line__mobile__v001.webp"
    },
    "node:blank-atlas:name-card-repair": {
        "assetId": "event.story.blank-atlas-useful-vocabulary.name-card-repair",
        "sceneId": "scene:blank-atlas:useful-vocabulary",
        "nodeId": "node:blank-atlas:name-card-repair",
        "cueId": "cue:name-card-one-rubric",
        "wide": "/academy/art/events/blank-atlas-useful-vocabulary__name-card-repair__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-useful-vocabulary__name-card-repair__mobile__v001.webp"
    },
    "node:blank-atlas:sound-nameplates": {
        "assetId": "event.story.blank-atlas-mission-sound.two-blank-name-tabs",
        "sceneId": "scene:blank-atlas:mission-sound",
        "nodeId": "node:blank-atlas:sound-nameplates",
        "cueId": "cue:sound-route-nameplates-only",
        "wide": "/academy/art/events/blank-atlas-mission-sound__two-blank-name-tabs__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-mission-sound__two-blank-name-tabs__mobile__v001.webp"
    },
    "node:blank-atlas:sound-input-repair": {
        "assetId": "event.story.blank-atlas-mission-sound.replay-one-voice",
        "sceneId": "scene:blank-atlas:mission-sound",
        "nodeId": "node:blank-atlas:sound-input-repair",
        "cueId": "cue:sound-route-replay-one-speaker",
        "wide": "/academy/art/events/blank-atlas-mission-sound__replay-one-voice__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-mission-sound__replay-one-voice__mobile__v001.webp"
    },
    "node:blank-atlas:text-note": {
        "assetId": "event.story.blank-atlas-mission-text.two-gaps",
        "sceneId": "scene:blank-atlas:mission-text",
        "nodeId": "node:blank-atlas:text-note",
        "cueId": "cue:text-route-note-nameplates",
        "wide": "/academy/art/events/blank-atlas-mission-text__two-gaps__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-mission-text__two-gaps__mobile__v001.webp"
    },
    "node:blank-atlas:text-input-repair": {
        "assetId": "event.story.blank-atlas-mission-text.one-gap-repair",
        "sceneId": "scene:blank-atlas:mission-text",
        "nodeId": "node:blank-atlas:text-input-repair",
        "cueId": "cue:text-route-evidence-lines",
        "wide": "/academy/art/events/blank-atlas-mission-text__one-gap-repair__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-mission-text__one-gap-repair__mobile__v001.webp"
    },
    "node:blank-atlas:speaking-door": {
        "assetId": "event.story.blank-atlas-mission-speaking.door-waiting",
        "sceneId": "scene:blank-atlas:mission-speaking",
        "nodeId": "node:blank-atlas:speaking-door",
        "cueId": "cue:speaking-route-open-door-nameplates",
        "wide": "/academy/art/events/blank-atlas-mission-speaking__door-waiting__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-mission-speaking__door-waiting__mobile__v001.webp"
    },
    "node:blank-atlas:speaking-input-repair": {
        "assetId": "event.story.blank-atlas-mission-speaking.door-open-repair",
        "sceneId": "scene:blank-atlas:mission-speaking",
        "nodeId": "node:blank-atlas:speaking-input-repair",
        "cueId": "cue:speaking-route-one-turn",
        "wide": "/academy/art/events/blank-atlas-mission-speaking__door-open-repair__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-mission-speaking__door-open-repair__mobile__v001.webp"
    },
    "node:blank-atlas:cards-return": {
        "assetId": "event.story.blank-atlas-reading-writing.cards-return",
        "sceneId": "scene:blank-atlas:reading-writing",
        "nodeId": "node:blank-atlas:cards-return",
        "cueId": "cue:route-cards-around-atlas",
        "wide": "/academy/art/events/blank-atlas-reading-writing__cards-return__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-reading-writing__cards-return__mobile__v001.webp"
    },
    "node:blank-atlas:card-turns-over": {
        "assetId": "event.story.blank-atlas-reading-writing.learner-card-route-label",
        "sceneId": "scene:blank-atlas:reading-writing",
        "nodeId": "node:blank-atlas:card-turns-over",
        "cueId": "cue:learner-card-route-label",
        "wide": "/academy/art/events/blank-atlas-reading-writing__learner-card-route-label__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-reading-writing__learner-card-route-label__mobile__v001.webp"
    },
    "node:blank-atlas:source-clears": {
        "assetId": "event.story.blank-atlas-transfer.support-clears",
        "sceneId": "scene:blank-atlas:transfer",
        "nodeId": "node:blank-atlas:source-clears",
        "cueId": "cue:teaching-surfaces-clear",
        "wide": "/academy/art/events/blank-atlas-transfer__support-clears__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-transfer__support-clears__mobile__v001.webp"
    },
    "node:blank-atlas:first-lantern": {
        "assetId": "event.story.blank-atlas-transfer.first-lantern",
        "sceneId": "scene:blank-atlas:transfer",
        "nodeId": "node:blank-atlas:first-lantern",
        "cueId": "cue:first-atlas-lantern-lit",
        "wide": "/academy/art/events/blank-atlas-transfer__first-lantern__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-transfer__first-lantern__mobile__v001.webp"
    },
    "node:blank-atlas:one-light-room": {
        "assetId": "event.story.blank-atlas-close.one-light-room",
        "sceneId": "scene:blank-atlas:close",
        "nodeId": "node:blank-atlas:one-light-room",
        "cueId": "cue:one-lantern-reflected-on-desks",
        "wide": "/academy/art/events/blank-atlas-close__one-light-room__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-close__one-light-room__mobile__v001.webp"
    },
    "node:blank-atlas:close-room-repair": {
        "assetId": "event.story.blank-atlas-close.finish-break-context",
        "sceneId": "scene:blank-atlas:close",
        "nodeId": "node:blank-atlas:close-room-repair",
        "cueId": "cue:finish-break-context",
        "wide": "/academy/art/events/blank-atlas-close__finish-break-context__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-close__finish-break-context__mobile__v001.webp"
    }
} as const satisfies Readonly<Record<string, AcademyStoryArtBinding>>;

export const ACADEMY_STORY_ART_RUNTIME_ASSETS = {
    "event.story.blank-atlas-arrival.covered-atlas": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:covered-table",
            "scene:blank-atlas:arrival-greetings"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-arrival__covered-atlas-open-chair__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-arrival__covered-atlas-open-chair__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-arrival.atlas-uncovered": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:first-uncover",
            "scene:blank-atlas:arrival-greetings"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-arrival__atlas-uncovered-unlit__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-arrival__atlas-uncovered-unlit__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-sound-script-map.five-empty-slots": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:vowel-slots",
            "scene:blank-atlas:sound-script-map"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-sound-script-map__five-empty-slots__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-sound-script-map__five-empty-slots__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-sound-script-map.first-route-line": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:first-line",
            "scene:blank-atlas:sound-script-map"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-sound-script-map__first-route-line__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-sound-script-map__first-route-line__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-classroom-survival.handout-arrives": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:handout-arrives",
            "scene:blank-atlas:classroom-survival"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-classroom-survival__handout-arrives__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-classroom-survival__handout-arrives__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-classroom-survival.rie-flower-mark": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:handout-flower",
            "scene:blank-atlas:classroom-survival"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-classroom-survival__rie-flower-mark__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-classroom-survival__rie-flower-mark__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-sentence-frames.two-room-labels": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:false-label",
            "scene:blank-atlas:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-sentence-frames__two-room-labels__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-sentence-frames__two-room-labels__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-sentence-frames.classroom-label-fixed": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:label-fixed",
            "scene:blank-atlas:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-sentence-frames__classroom-label-fixed__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-sentence-frames__classroom-label-fixed__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-useful-vocabulary.name-line": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:name-line",
            "scene:blank-atlas:useful-vocabulary"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-useful-vocabulary__name-line__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-useful-vocabulary__name-line__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-useful-vocabulary.name-card-repair": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:name-card-repair",
            "scene:blank-atlas:useful-vocabulary"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-useful-vocabulary__name-card-repair__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-useful-vocabulary__name-card-repair__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-mission-sound.two-blank-name-tabs": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:sound-nameplates",
            "scene:blank-atlas:mission-sound"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-mission-sound__two-blank-name-tabs__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-mission-sound__two-blank-name-tabs__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-mission-sound.replay-one-voice": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:sound-input-repair",
            "scene:blank-atlas:mission-sound"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-mission-sound__replay-one-voice__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-mission-sound__replay-one-voice__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-mission-text.two-gaps": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:text-note",
            "scene:blank-atlas:mission-text"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-mission-text__two-gaps__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-mission-text__two-gaps__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-mission-text.one-gap-repair": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:text-input-repair",
            "scene:blank-atlas:mission-text"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-mission-text__one-gap-repair__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-mission-text__one-gap-repair__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-mission-speaking.door-waiting": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:speaking-door",
            "scene:blank-atlas:mission-speaking"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-mission-speaking__door-waiting__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-mission-speaking__door-waiting__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-mission-speaking.door-open-repair": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:speaking-input-repair",
            "scene:blank-atlas:mission-speaking"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-mission-speaking__door-open-repair__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-mission-speaking__door-open-repair__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-reading-writing.cards-return": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:cards-return",
            "scene:blank-atlas:reading-writing"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-reading-writing__cards-return__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-reading-writing__cards-return__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-reading-writing.learner-card-route-label": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:card-turns-over",
            "scene:blank-atlas:reading-writing"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-reading-writing__learner-card-route-label__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-reading-writing__learner-card-route-label__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-transfer.support-clears": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:source-clears",
            "scene:blank-atlas:transfer"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-transfer__support-clears__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-transfer__support-clears__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-transfer.first-lantern": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:first-lantern",
            "scene:blank-atlas:transfer"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-transfer__first-lantern__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-transfer__first-lantern__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-close.one-light-room": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:one-light-room",
            "scene:blank-atlas:close"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-close__one-light-room__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-close__one-light-room__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-close.finish-break-context": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:close-room-repair",
            "scene:blank-atlas:close"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-close__finish-break-context__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-close__finish-break-context__mobile__v001.webp"
        }
    }
} as const;

export const ACADEMY_STORY_ART_COVERAGE = {
    "event.story.blank-atlas-arrival.covered-atlas": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:covered-table"
    },
    "event.story.blank-atlas-arrival.atlas-uncovered": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:first-uncover"
    },
    "event.story.blank-atlas-sound-script-map.five-empty-slots": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:vowel-slots"
    },
    "event.story.blank-atlas-sound-script-map.first-route-line": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:first-line"
    },
    "event.story.blank-atlas-classroom-survival.handout-arrives": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:handout-arrives"
    },
    "event.story.blank-atlas-classroom-survival.rie-flower-mark": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:handout-flower"
    },
    "event.story.blank-atlas-sentence-frames.two-room-labels": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:false-label"
    },
    "event.story.blank-atlas-sentence-frames.classroom-label-fixed": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:label-fixed"
    },
    "event.story.blank-atlas-useful-vocabulary.name-line": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:name-line"
    },
    "event.story.blank-atlas-useful-vocabulary.name-card-repair": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:name-card-repair"
    },
    "event.story.blank-atlas-mission-sound.two-blank-name-tabs": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:sound-nameplates"
    },
    "event.story.blank-atlas-mission-sound.replay-one-voice": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:sound-input-repair"
    },
    "event.story.blank-atlas-mission-text.two-gaps": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:text-note"
    },
    "event.story.blank-atlas-mission-text.one-gap-repair": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:text-input-repair"
    },
    "event.story.blank-atlas-mission-speaking.door-waiting": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:speaking-door"
    },
    "event.story.blank-atlas-mission-speaking.door-open-repair": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:speaking-input-repair"
    },
    "event.story.blank-atlas-reading-writing.cards-return": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:cards-return"
    },
    "event.story.blank-atlas-reading-writing.learner-card-route-label": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:card-turns-over"
    },
    "event.story.blank-atlas-transfer.support-clears": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:source-clears"
    },
    "event.story.blank-atlas-transfer.first-lantern": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:first-lantern"
    },
    "event.story.blank-atlas-close.one-light-room": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:one-light-room"
    },
    "event.story.blank-atlas-close.finish-break-context": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:close-room-repair"
    }
} as const;
