export interface AcademyStoryArtBinding {
    readonly assetId: string;
    readonly sceneId: string;
    readonly nodeId: string;
    readonly cueId: string;
    readonly wide: `/academy/art/events/${string}.webp`;
    readonly mobile: `/academy/art/events/${string}.webp`;
}

/**
 * Generated by npm run academy:art:story:promote. Every entry has passed
 * viewport QA and resolves to an authored story node before reaching runtime.
 */
export const ACADEMY_STORY_ART_BY_NODE = {
    "node:blank-atlas:covered-table": {
        "assetId": "event.story.blank-atlas-arrival.covered-atlas",
        "sceneId": "scene:blank-atlas:arrival-greetings",
        "nodeId": "node:blank-atlas:covered-table",
        "cueId": "cue:covered-atlas-open-chair",
        "wide": "/academy/art/events/blank-atlas-arrival__covered-atlas-open-chair__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-arrival__covered-atlas-open-chair__mobile__v001.webp"
    },
    "node:blank-atlas:first-uncover": {
        "assetId": "event.story.blank-atlas-arrival.atlas-uncovered",
        "sceneId": "scene:blank-atlas:arrival-greetings",
        "nodeId": "node:blank-atlas:first-uncover",
        "cueId": "cue:atlas-uncovered-unlit",
        "wide": "/academy/art/events/blank-atlas-arrival__atlas-uncovered-unlit__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-arrival__atlas-uncovered-unlit__mobile__v001.webp"
    },
    "node:blank-atlas:vowel-slots": {
        "assetId": "event.story.blank-atlas-sound-script-map.five-empty-slots",
        "sceneId": "scene:blank-atlas:sound-script-map",
        "nodeId": "node:blank-atlas:vowel-slots",
        "cueId": "cue:five-empty-atlas-slots",
        "wide": "/academy/art/events/blank-atlas-sound-script-map__five-empty-slots__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-sound-script-map__five-empty-slots__mobile__v001.webp"
    },
    "node:blank-atlas:first-line": {
        "assetId": "event.story.blank-atlas-sound-script-map.first-route-line",
        "sceneId": "scene:blank-atlas:sound-script-map",
        "nodeId": "node:blank-atlas:first-line",
        "cueId": "cue:first-route-line-visible",
        "wide": "/academy/art/events/blank-atlas-sound-script-map__first-route-line__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-sound-script-map__first-route-line__mobile__v001.webp"
    },
    "node:blank-atlas:handout-arrives": {
        "assetId": "event.story.blank-atlas-classroom-survival.handout-arrives",
        "sceneId": "scene:blank-atlas:classroom-survival",
        "nodeId": "node:blank-atlas:handout-arrives",
        "cueId": "cue:classroom-handout-on-desk",
        "wide": "/academy/art/events/blank-atlas-classroom-survival__handout-arrives__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-classroom-survival__handout-arrives__mobile__v001.webp"
    },
    "node:blank-atlas:handout-flower": {
        "assetId": "event.story.blank-atlas-classroom-survival.rie-flower-mark",
        "sceneId": "scene:blank-atlas:classroom-survival",
        "nodeId": "node:blank-atlas:handout-flower",
        "cueId": "cue:rie-flower-mark",
        "wide": "/academy/art/events/blank-atlas-classroom-survival__rie-flower-mark__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-classroom-survival__rie-flower-mark__mobile__v001.webp"
    },
    "node:blank-atlas:false-label": {
        "assetId": "event.story.blank-atlas-sentence-frames.two-room-labels",
        "sceneId": "scene:blank-atlas:sentence-frames",
        "nodeId": "node:blank-atlas:false-label",
        "cueId": "cue:atlas-classroom-library-labels",
        "wide": "/academy/art/events/blank-atlas-sentence-frames__two-room-labels__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-sentence-frames__two-room-labels__mobile__v001.webp"
    },
    "node:blank-atlas:label-fixed": {
        "assetId": "event.story.blank-atlas-sentence-frames.classroom-label-fixed",
        "sceneId": "scene:blank-atlas:sentence-frames",
        "nodeId": "node:blank-atlas:label-fixed",
        "cueId": "cue:atlas-classroom-label-fixed",
        "wide": "/academy/art/events/blank-atlas-sentence-frames__classroom-label-fixed__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-sentence-frames__classroom-label-fixed__mobile__v001.webp"
    },
    "node:blank-atlas:name-line": {
        "assetId": "event.story.blank-atlas-useful-vocabulary.name-line",
        "sceneId": "scene:blank-atlas:useful-vocabulary",
        "nodeId": "node:blank-atlas:name-line",
        "cueId": "cue:blank-name-card-and-atlas-line",
        "wide": "/academy/art/events/blank-atlas-useful-vocabulary__name-line__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-useful-vocabulary__name-line__mobile__v001.webp"
    },
    "node:blank-atlas:name-card-repair": {
        "assetId": "event.story.blank-atlas-useful-vocabulary.name-card-repair",
        "sceneId": "scene:blank-atlas:useful-vocabulary",
        "nodeId": "node:blank-atlas:name-card-repair",
        "cueId": "cue:name-card-one-rubric",
        "wide": "/academy/art/events/blank-atlas-useful-vocabulary__name-card-repair__wide__v001.webp",
        "mobile": "/academy/art/events/blank-atlas-useful-vocabulary__name-card-repair__mobile__v001.webp"
    }
} as const satisfies Readonly<Record<string, AcademyStoryArtBinding>>;

export const ACADEMY_STORY_ART_RUNTIME_ASSETS = {
    "event.story.blank-atlas-arrival.covered-atlas": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:covered-table",
            "scene:blank-atlas:arrival-greetings"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-arrival__covered-atlas-open-chair__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-arrival__covered-atlas-open-chair__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-arrival.atlas-uncovered": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:first-uncover",
            "scene:blank-atlas:arrival-greetings"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-arrival__atlas-uncovered-unlit__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-arrival__atlas-uncovered-unlit__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-sound-script-map.five-empty-slots": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:vowel-slots",
            "scene:blank-atlas:sound-script-map"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-sound-script-map__five-empty-slots__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-sound-script-map__five-empty-slots__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-sound-script-map.first-route-line": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:first-line",
            "scene:blank-atlas:sound-script-map"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-sound-script-map__first-route-line__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-sound-script-map__first-route-line__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-classroom-survival.handout-arrives": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:handout-arrives",
            "scene:blank-atlas:classroom-survival"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-classroom-survival__handout-arrives__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-classroom-survival__handout-arrives__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-classroom-survival.rie-flower-mark": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:handout-flower",
            "scene:blank-atlas:classroom-survival"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-classroom-survival__rie-flower-mark__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-classroom-survival__rie-flower-mark__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-sentence-frames.two-room-labels": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:false-label",
            "scene:blank-atlas:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-sentence-frames__two-room-labels__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-sentence-frames__two-room-labels__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-sentence-frames.classroom-label-fixed": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:label-fixed",
            "scene:blank-atlas:sentence-frames"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-sentence-frames__classroom-label-fixed__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-sentence-frames__classroom-label-fixed__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-useful-vocabulary.name-line": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:name-line",
            "scene:blank-atlas:useful-vocabulary"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-useful-vocabulary__name-line__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-useful-vocabulary__name-line__mobile__v001.webp"
        }
    },
    "event.story.blank-atlas-useful-vocabulary.name-card-repair": {
        "kind": "event-art",
        "status": "approved",
        "runtimeHomes": [
            "node:blank-atlas:name-card-repair",
            "scene:blank-atlas:useful-vocabulary"
        ],
        "provenance": "regenerated-house-style",
        "files": {
            "wide": "/academy/art/events/blank-atlas-useful-vocabulary__name-card-repair__wide__v001.webp",
            "mobile": "/academy/art/events/blank-atlas-useful-vocabulary__name-card-repair__mobile__v001.webp"
        }
    }
} as const;

export const ACADEMY_STORY_ART_COVERAGE = {
    "event.story.blank-atlas-arrival.covered-atlas": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:covered-table"
    },
    "event.story.blank-atlas-arrival.atlas-uncovered": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:first-uncover"
    },
    "event.story.blank-atlas-sound-script-map.five-empty-slots": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:vowel-slots"
    },
    "event.story.blank-atlas-sound-script-map.first-route-line": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:first-line"
    },
    "event.story.blank-atlas-classroom-survival.handout-arrives": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:handout-arrives"
    },
    "event.story.blank-atlas-classroom-survival.rie-flower-mark": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:handout-flower"
    },
    "event.story.blank-atlas-sentence-frames.two-room-labels": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:false-label"
    },
    "event.story.blank-atlas-sentence-frames.classroom-label-fixed": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:label-fixed"
    },
    "event.story.blank-atlas-useful-vocabulary.name-line": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:name-line"
    },
    "event.story.blank-atlas-useful-vocabulary.name-card-repair": {
        "purpose": "story-event",
        "primaryUse": "node:blank-atlas:name-card-repair"
    }
} as const;
