export type AcademyLanguage = 'en' | 'ja';

const EN = {
    academyName: 'よむ Academy',
    languageToggle: '日本語',
    loading: 'Opening the academy…',
    retry: 'Try again',
    continue: 'Continue',
    back: 'Back',
    accessEyebrow: 'A rainy London evening',
    accessTitle: 'The academy doors are open.',
    accessBody: 'Enter your class or invitation code. Your learning record will be available offline on this device.',
    accessCodeLabel: 'Class code',
    accessCodePlaceholder: 'Enter code',
    accessSubmit: 'Open the doors',
    accessChecking: 'Checking your invitation…',
    accessInvalid: 'That invitation is not valid. Check the code and try again.',
    accessUnavailable: 'The invitation service is unavailable. A previously opened session still works offline.',
    localQaSession: 'Local QA session',
    rieGreeting: 'こんばんは。雨の中、来てくれてありがとうございます。',
    rieGreetingSupport: 'Good evening. Thank you for coming through the rain.',
    fictionNote: 'Before we begin: this is an AI-created fictional story. Its plot and dialogue are invented and do not describe real events or make claims about real people. Now then—what should I call you, and why are you learning Japanese?',
    profileNameLabel: 'What should Rie call you?',
    profileNamePlaceholder: 'Your name',
    profileReasonLabel: 'Why are you learning Japanese?',
    profileReasonPlaceholder: 'A private note for your journal',
    profilePortraitLegend: 'Choose how you appear in the story',
    portraitCamera: 'A learner carrying a camera and folded map',
    portraitPlanner: 'A learner carrying a planner and study cards',
    portraitCards: 'A learner offering a card',
    portraitNotebook: 'A learner with a pencil and notebook',
    profileSubmit: 'Tell Rie',
    rieUnlockEyebrow: 'Character unlocked',
    rieUnlockTitle: 'Rie-sensei',
    rieUnlockBody: '“One open chair is enough. We can begin.” Her first page is now replayable in the class journal.',
    rieUnlockContinue: 'Choose where to begin',
    bondFirstStar: 'Bond ★☆☆',
    startEyebrow: 'Choose your first door',
    startTitle: 'Where should we begin?',
    startBody: 'This is a starting point, not a permanent track. Lesson 0 and every earlier memory stay available.',
    startLessonZero: 'Begin with Lesson 0',
    startLessonZeroBody: 'Start from the first sounds, classroom phrases, and kana.',
    startManual: 'Choose a JLPT band',
    startManualBody: 'Pick a provisional N5–N1 entry and adjust it whenever you like.',
    startMock: 'Take a short placement mock',
    startMockBody: 'Get separate language, reading, and listening evidence before choosing.',
    manualTitle: 'Choose a provisional band',
    manualBody: 'You can begin earlier, change route later, or return to Lesson 0 at any time.',
    bandN5: 'N5 · first useful Japanese',
    bandN4: 'N4 · plans and connected sentences',
    bandN3: 'N3 · everyday native input and nuance',
    bandN2: 'N2 · evidence, stance, and formal language',
    bandN1: 'N1 · ambiguity, synthesis, and adaptation',
    mockTitle: 'A short orientation mock',
    mockBody: 'This vertical-slice form demonstrates the evidence model; it is not a calibrated JLPT score.',
    mockTargetLegend: 'Target band',
    mockPlayAudio: 'Play the listening line',
    mockAudioUnavailable: 'Japanese speech is unavailable in this browser. Choose another route or try a supported browser.',
    mockSpeakingConfidence: 'How confident are you speaking without a script?',
    mockWritingConfidence: 'How confident are you writing a short message?',
    mockSubmit: 'See my evidence',
    mockIncomplete: 'Answer each item before continuing.',
    mockResultTitle: 'Rie’s recommendation',
    mockKnowledge: 'Language knowledge',
    mockReading: 'Reading',
    mockListening: 'Listening',
    mockProduction: 'Speaking and writing confidence',
    mockRecommendation: 'Recommended entry',
    mockUseRecommendation: 'Use this recommendation',
    mockChooseMyself: 'Choose another band',
    bridgeEyebrow: 'A playable arrival bridge',
    bridgeTitle: 'The chair is still yours.',
    bridgeBody: 'Rie introduces the present term and opens the journal to earlier memories. Curriculum placement changes what you study first; it does not pretend you lived scenes you have not played.',
    bridgeContinue: 'Enter the classroom',
    bandEntryEyebrow: 'Transfer lesson · selected curriculum',
    bandEntryTitle: 'Start where your Japanese is now.',
    bandEntryBody: 'This is an original, level-matched transfer task. It records learning evidence without marking earlier story scenes as experienced.',
    bandEntryComplete: 'Your transfer task is recorded. Earlier memories remain unplayed and replayable in chronological order.',
    bandEntryContinue: 'Open the campus',
    lessonForkEyebrow: 'Lesson 0 · the first repair',
    lessonForkTitle: 'What should Rie show first?',
    lessonForkBody: 'All three paths teach the same opening concept in a different order.',
    forkSound: 'Sound',
    forkSoundBody: 'Hear, identify, shadow, then reveal the text.',
    forkText: 'Text',
    forkTextBody: 'Read, inspect, reconstruct, then hear the line.',
    forkSpeaking: 'Speaking',
    forkSpeakingBody: 'Rehearse, compare, then read the model in context.',
    sourceEyebrow: 'Source activity · Week 1',
    sourceTitle: 'Ask for one more try',
    sourceBody: 'Rie has spoken too quickly. Choose the classroom phrase that asks her to repeat it.',
    sourceRecordSummary: 'View the immutable source record',
    sourceRecordLine: '2023/24 Level 1 · Lesson 1 · classroom-phrases payload · page 2 · printed item 9',
    sourceComplete: 'The phrase is now in your Yomu review queue.',
    sourceContinue: 'Meet Aakash outside',
    aakashMeetEyebrow: 'Rainy directions · first bond beat',
    aakashMeetTitle: 'A better photo spot.',
    aakashMeetBody: 'Aakash has found the light. The cafe is less cooperative. Help him confirm the last turn.',
    aakashUnlockEyebrow: 'Classmate unlocked',
    aakashUnlockTitle: 'アーカーシュ · Aakash',
    aakashUnlockLine: '“Straight ahead, then right. Great—before the rain changes its mind.”',
    aakashContinue: 'Go to the writing desk',
    aakashMemoryTitle: 'The better photo spot',
    aakashMemoryBody: 'Rain on the map. A red umbrella. Aakash waits until you finish the direction, then points out the perfect light.',
    aakashMemoryReturn: 'Close the memory',
    kanjiDeskEyebrow: 'Writing Studio · two-way practice',
    kanjiDeskTitle: 'See it. Then make it.',
    kanjiDeskBody: 'Recognition and production are separate evidence. First identify 一; then write it with Yomu’s shared Doodle and a KanjiVG trace.',
    kanjiDeskComplete: 'Recognition and handwriting evidence are saved. KanjiVG trace: Ulrich Apel, CC BY-SA 3.0.',
    kanjiDeskContinue: 'Open the campus',
    campusTitle: 'Evening campus',
    campusObjective: 'Next: visit the Library for your first review.',
    campusObjectiveComplete: 'Your evening is open: continue class, listen in the Lab, or meet someone at the Cafe.',
    locationClassroom: 'Classroom',
    locationClassroomBody: 'Continue the class week and source activities.',
    locationLibrary: 'Library',
    locationLibraryBody: 'Review due language and saved lines.',
    locationLab: 'Language Lab',
    locationLabBody: 'Listening, shadowing, pitch, and transcripts.',
    locationCafe: 'Cafe',
    locationCafeBody: 'Conversation, bonds, and transfer missions.',
    locationOpen: 'Enter',
    locationUnavailable: 'Opens after the first review',
    locationReturn: 'Return to the campus',
    labEyebrow: 'Language Lab · listening pair',
    labTitle: 'Hear it before you see it.',
    labBody: 'Audio, one committed answer, transcript reveal, and shadowing stay together as one learning record.',
    labPlay: 'Play / replay the line',
    labTimecode: '00:00–00:02 · browser Japanese voice',
    labTranscriptTitle: 'Transcript after commitment',
    labShadowTitle: 'Shadow the line',
    labShadowPrompt: 'Replay it, repeat aloud once, then compare your timing. This is self-assessment, not a fake pronunciation score.',
    labShadowDone: 'I repeated and compared it',
    labListeningComplete: 'Listening answer committed. The transcript and shadowing step are now open.',
    navCampus: 'Campus',
    navReview: 'Review',
    navJournal: 'Class journal',
    navAudioMuted: 'Sound off',
    navAudioOn: 'Sound on',
    reviewTitle: 'Library review',
    reviewEmpty: 'Nothing is due right now. Your next return will bring scheduled work here.',
    reviewReveal: 'Reveal meaning',
    reviewPrompt: 'Do you remember this phrase?',
    reviewAgain: 'Again',
    reviewHard: 'Hard',
    reviewGood: 'Good',
    reviewEasy: 'Easy',
    reviewComplete: 'Review recorded in Yomu.',
    reviewReturn: 'Return to the campus',
    journalTitle: 'Class journal',
    journalRie: 'Rie-sensei',
    journalRieLine: '“One open chair is enough. We can begin.”',
    journalAakash: 'Aakash',
    journalAakashLine: '“Straight ahead, then right. Great.”',
    journalBond: 'Bond',
    journalReplay: 'Replay the opening memory',
    journalReplayAakash: 'Replay rainy directions',
    journalReason: 'Reason for learning',
    memoryTitle: 'The open chair',
    memoryBody: 'Rain on the windows. Rie balancing tea and a stack of papers. One chair left open for you.',
    memoryReturn: 'Close the memory',
    journalLocked: 'Meet someone in the story to unlock their page.',
    offlineReady: 'Ready offline',
    offlineNow: 'Offline · progress will sync later',
    onlineNow: 'Online',
} as const;

export type AcademyCopyKey = keyof typeof EN;

const JA: Record<AcademyCopyKey, string> = {
    academyName: 'よむアカデミー',
    languageToggle: 'English',
    loading: 'アカデミーの扉を開いています…',
    retry: 'もう一度',
    continue: '続ける',
    back: '戻る',
    accessEyebrow: '雨のロンドン、夜の教室',
    accessTitle: 'アカデミーの扉が開いています。',
    accessBody: 'クラスコードまたは招待コードを入力してください。この端末では学習記録をオフラインでも利用できます。',
    accessCodeLabel: 'クラスコード',
    accessCodePlaceholder: 'コードを入力',
    accessSubmit: '扉を開く',
    accessChecking: '招待を確認しています…',
    accessInvalid: 'この招待は有効ではありません。コードを確認して、もう一度お試しください。',
    accessUnavailable: '招待サービスを利用できません。以前に開いたセッションはオフラインでも続けられます。',
    localQaSession: 'ローカルQAセッション',
    rieGreeting: 'こんばんは。雨の中、来てくれてありがとうございます。',
    rieGreetingSupport: 'こんばんは。雨の中を来てくださって、ありがとうございます。',
    fictionNote: '始める前に：これはAIが作ったフィクションです。物語と会話は創作であり、実際の出来事を描写したり、実在の人物について主張したりするものではありません。では、あなたのお名前と、日本語を学ぶ理由を教えてください。',
    profileNameLabel: 'りえ先生になんと呼んでほしいですか。',
    profileNamePlaceholder: 'お名前',
    profileReasonLabel: 'なぜ日本語を勉強していますか。',
    profileReasonPlaceholder: '日記に残す自分だけのメモ',
    profilePortraitLegend: '物語の中の姿を選んでください',
    portraitCamera: 'カメラと折りたたみ地図を持つ学習者',
    portraitPlanner: '手帳と学習カードを持つ学習者',
    portraitCards: 'カードを差し出す学習者',
    portraitNotebook: '鉛筆とノートを持つ学習者',
    profileSubmit: 'りえ先生に伝える',
    rieUnlockEyebrow: 'キャラクター解放',
    rieUnlockTitle: 'りえ先生',
    rieUnlockBody: '「椅子が一つ空いていれば十分。始めましょう。」最初のページをクラス日記から再生できるようになりました。',
    rieUnlockContinue: '始める場所を選ぶ',
    bondFirstStar: '絆 ★☆☆',
    startEyebrow: '最初の扉を選ぶ',
    startTitle: 'どこから始めましょうか。',
    startBody: 'これは出発点で、固定されたコースではありません。レッスン0と以前の思い出はいつでも開けます。',
    startLessonZero: 'レッスン0から始める',
    startLessonZeroBody: '最初の音、教室表現、かなから始めます。',
    startManual: 'JLPTレベルを選ぶ',
    startManualBody: 'N5〜N1の仮の出発点を選び、いつでも調整できます。',
    startMock: '短いプレイスメント模試を受ける',
    startMockBody: '言語知識・読解・聴解の根拠を別々に確認してから選びます。',
    manualTitle: '仮のレベルを選んでください',
    manualBody: 'いつでも前の内容から始めたり、ルートを変えたり、レッスン0に戻ったりできます。',
    bandN5: 'N5・最初の役立つ日本語',
    bandN4: 'N4・計画とつながった文',
    bandN3: 'N3・日常の生きた日本語とニュアンス',
    bandN2: 'N2・根拠、立場、フォーマルな表現',
    bandN1: 'N1・曖昧さ、統合、適応',
    mockTitle: '短いオリエンテーション模試',
    mockBody: 'この縦切り版は根拠モデルの実演です。校正済みのJLPTスコアではありません。',
    mockTargetLegend: '目標レベル',
    mockPlayAudio: '聴解の文を再生',
    mockAudioUnavailable: 'このブラウザでは日本語音声を再生できません。別のルートを選ぶか、対応ブラウザでお試しください。',
    mockSpeakingConfidence: '台本なしで話す自信はどのくらいありますか。',
    mockWritingConfidence: '短いメッセージを書く自信はどのくらいありますか。',
    mockSubmit: '結果を見る',
    mockIncomplete: '続ける前に、すべての問題に答えてください。',
    mockResultTitle: 'りえ先生のおすすめ',
    mockKnowledge: '言語知識',
    mockReading: '読解',
    mockListening: '聴解',
    mockProduction: '会話・作文の自信',
    mockRecommendation: 'おすすめの出発点',
    mockUseRecommendation: 'このおすすめを使う',
    mockChooseMyself: '別のレベルを選ぶ',
    bridgeEyebrow: '遊べる途中参加エピソード',
    bridgeTitle: 'あなたの椅子は、まだ空いています。',
    bridgeBody: 'りえ先生が今学期を紹介し、日記から以前の思い出を開けるようにします。プレイスメントで最初の学習内容は変わりますが、未体験の物語を体験済みにはしません。',
    bridgeContinue: '教室に入る',
    bandEntryEyebrow: '途中参加レッスン・選んだカリキュラム',
    bandEntryTitle: '今の日本語力から始めましょう。',
    bandEntryBody: '選んだレベルに合わせた、よむオリジナルの途中参加課題です。学習の根拠を記録しても、以前の物語を体験済みにはしません。',
    bandEntryComplete: '途中参加課題を記録しました。以前の思い出は未体験のまま、日記から時系列で再生できます。',
    bandEntryContinue: 'キャンパスを開く',
    lessonForkEyebrow: 'レッスン0・最初の聞き返し',
    lessonForkTitle: 'りえ先生に、まず何を見せてもらいますか。',
    lessonForkBody: '三つのルートは、同じ最初の概念を違う順番で学びます。',
    forkSound: '音',
    forkSoundBody: '聞く、意味を選ぶ、シャドーイングする、文字を見る。',
    forkText: '文字',
    forkTextBody: '読む、言葉を調べる、文を組み立てる、音を聞く。',
    forkSpeaking: '話す',
    forkSpeakingBody: '練習する、比べる、場面の中で例文を読む。',
    sourceEyebrow: '原資料アクティビティ・第1週',
    sourceTitle: 'もう一度お願いする',
    sourceBody: 'りえ先生の話す速さが少し速すぎました。繰り返しを頼む教室表現を選んでください。',
    sourceRecordSummary: '変更されない原資料レコードを見る',
    sourceRecordLine: '2023/24 レベル1・レッスン1・教室表現ペイロード・2ページ・印刷番号9',
    sourceComplete: 'この表現をよむの復習キューに追加しました。',
    sourceContinue: '外でアーカーシュに会う',
    aakashMeetEyebrow: '雨の道案内・最初の絆エピソード',
    aakashMeetTitle: 'もっといい撮影場所',
    aakashMeetBody: 'アーカーシュはいい光を見つけました。でも、カフェまでの最後の曲がり角が分かりません。道順を確かめるのを手伝ってください。',
    aakashUnlockEyebrow: 'クラスメート解放',
    aakashUnlockTitle: 'アーカーシュ・Aakash',
    aakashUnlockLine: '「まっすぐ行って、右。よし、雨の気が変わる前に行こう。」',
    aakashContinue: '書く練習の机へ行く',
    aakashMemoryTitle: 'もっといい撮影場所',
    aakashMemoryBody: '地図に落ちる雨。赤い傘。あなたが道順を言い終わるまで待ってから、完璧な光を指すアーカーシュ。',
    aakashMemoryReturn: '思い出を閉じる',
    kanjiDeskEyebrow: 'ライティングスタジオ・双方向練習',
    kanjiDeskTitle: '見分けて、書く。',
    kanjiDeskBody: '認識と産出は別々の学習記録になります。まず「一」を見分け、よむ共通のDoodleとKanjiVGの見本で書きましょう。',
    kanjiDeskComplete: '認識と手書きの学習記録を保存しました。KanjiVG見本：Ulrich Apel、CC BY-SA 3.0。',
    kanjiDeskContinue: 'キャンパスを開く',
    campusTitle: '夜のキャンパス',
    campusObjective: '次：図書館で最初の復習をしましょう。',
    campusObjectiveComplete: '今夜は自由です。授業を続ける、ラボで聞く、カフェで誰かに会う。',
    locationClassroom: '教室',
    locationClassroomBody: '授業週と原資料アクティビティを続けます。',
    locationLibrary: '図書館',
    locationLibraryBody: '期限の来た表現と保存した文を復習します。',
    locationLab: 'ランゲージラボ',
    locationLabBody: '聴解、シャドーイング、ピッチ、文字起こし。',
    locationCafe: 'カフェ',
    locationCafeBody: '会話、絆、応用ミッション。',
    locationOpen: '入る',
    locationUnavailable: '最初の復習後に開きます',
    locationReturn: 'キャンパスに戻る',
    labEyebrow: 'ランゲージラボ・聴解ペア',
    labTitle: '見る前に、聞く。',
    labBody: '音声、回答、回答後の文字起こし、シャドーイングを一つの学習記録として扱います。',
    labPlay: '音声を再生・もう一度再生',
    labTimecode: '00:00〜00:02・ブラウザの日本語音声',
    labTranscriptTitle: '回答後の文字起こし',
    labShadowTitle: '文をシャドーイングする',
    labShadowPrompt: 'もう一度再生し、一回声に出して、タイミングを比べてください。これは自己評価で、発音を装った点数にはしません。',
    labShadowDone: '繰り返して比べました',
    labListeningComplete: '聴解の回答を記録しました。文字起こしとシャドーイングを開きました。',
    navCampus: 'キャンパス',
    navReview: '復習',
    navJournal: 'クラス日記',
    navAudioMuted: '音声オフ',
    navAudioOn: '音声オン',
    reviewTitle: '図書館の復習',
    reviewEmpty: '今、期限の来た項目はありません。次に戻るとき、予定された復習がここに届きます。',
    reviewReveal: '意味を見る',
    reviewPrompt: 'この表現を覚えていますか。',
    reviewAgain: 'もう一度',
    reviewHard: '難しい',
    reviewGood: 'できた',
    reviewEasy: '簡単',
    reviewComplete: 'よむに復習を記録しました。',
    reviewReturn: 'キャンパスに戻る',
    journalTitle: 'クラス日記',
    journalRie: 'りえ先生',
    journalRieLine: '「椅子が一つ空いていれば十分。始めましょう。」',
    journalAakash: 'アーカーシュ',
    journalAakashLine: '「まっすぐ行って、右。よし。」',
    journalBond: '絆',
    journalReplay: '最初の思い出をもう一度見る',
    journalReplayAakash: '雨の道案内をもう一度見る',
    journalReason: '日本語を学ぶ理由',
    memoryTitle: '空いていた椅子',
    memoryBody: '窓をたたく雨。お茶とプリントの山を抱えるりえ先生。あなたのために空いた椅子が一つ。',
    memoryReturn: '思い出を閉じる',
    journalLocked: '物語で誰かに会うと、その人のページが開きます。',
    offlineReady: 'オフライン準備完了',
    offlineNow: 'オフライン・進捗はあとで同期します',
    onlineNow: 'オンライン',
};

export function academyText(language: AcademyLanguage, key: AcademyCopyKey): string {
    return language === 'ja' ? JA[key] : EN[key];
}

export function academyCopyHasMissingJapanese(): boolean {
    return (Object.keys(EN) as AcademyCopyKey[]).some(key => !JA[key].trim() || JA[key] === '未翻訳');
}
