export type AcademyLanguage = 'en' | 'ja';

const EN = {
    academyName: 'よむ Academy',
    languageToggle: '日本語',
    utilityMenu: 'Menu',
    loading: 'One moment…',
    retry: 'Try again',
    continue: 'Continue',
    back: 'Back',
    accessBody: 'A playable Japanese course from first kana to N1.',
    accessCodeLabel: 'Class code',
    accessCodePlaceholder: 'Enter code',
    accessSubmit: 'Open the doors',
    accessGetCode: 'Get a class code',
    accessChecking: 'One moment…',
    accessInvalid: 'Check the code and try again.',
    accessUnavailable: 'Couldn’t check that code. Try again.',
    donationTitle: 'One-time support',
    donationChooseAmount: 'Choose an amount',
    donationOther: 'Other',
    donationOtherAmount: 'Amount in pounds',
    donationDescription: 'Your class code is generated after secure checkout.',
    donationContinue: 'Continue to checkout',
    donationCancel: 'Not now',
    donationClose: 'Close',
    donationStarting: 'Opening secure checkout…',
    donationInvalidAmount: 'Choose an amount from £2 to £500.',
    donationUnavailable: 'Checkout could not be started. Try again.',
    donationClaimChecking: 'Finding your class code…',
    donationClaimPending: 'Payment is still settling.',
    donationClaimUnavailable: 'Couldn’t retrieve the code.',
    donationClaimReady: 'Your class code is ready.',
    donationClaimRetry: 'Try again',
    donationClaimCopy: 'Copy code',
    donationClaimCopied: 'Copied',
    localQaSession: 'Local QA session',
    rieGreeting: 'こんばんは。雨の中、来てくれてありがとうございます。',
    rieGreetingSupport: 'Good evening. Thank you for coming through the rain.',
    fictionNote: 'This is an AI-created fiction, not an account of real people or events.',
    profileNameLabel: 'What should Rie call you?',
    profileNamePlaceholder: 'Your name',
    profileReasonLabel: 'Why are you learning Japanese?',
    profileReasonPlaceholder: 'A private note for your journal',
    profilePortraitLegend: 'Choose how you appear in the story',
    portraitCamera: 'A learner carrying a camera and folded map',
    portraitPlanner: 'A learner carrying a planner and study cards',
    portraitCards: 'A learner offering a card',
    portraitNotebook: 'A learner with a pencil and notebook',
    profileSubmit: 'Tell Rie',
    rieUnlockEyebrow: 'Your teacher',
    rieUnlockTitle: 'Rie-sensei',
    rieUnlockBody: '“One open chair is enough. We can begin.”',
    rieUnlockContinue: 'Choose where to begin',
    bondFirstStar: 'First journal page',
    relationshipFirstPage: 'First journal page opened',
    relationshipJournalProgress: 'Relationship journal',
    relationshipStage1: 'Introduction',
    relationshipStage2: 'Familiarity',
    relationshipStage3: 'Shared joke',
    relationshipStage4: 'Trust',
    relationshipStage5: 'Friction',
    relationshipStage6: 'Repair',
    relationshipStage7: 'Reciprocity',
    relationshipStage8: 'Support',
    relationshipStage9: 'Shared memory',
    relationshipStage10: 'Enduring bond',
    startEyebrow: 'Your starting point',
    startTitle: 'Where should we begin?',
    startBody: 'You can change this later.',
    startLessonZero: 'Begin with Lesson 0',
    startLessonZeroBody: 'Sounds, classroom phrases, and kana.',
    startManual: 'Choose a JLPT band',
    startManualBody: 'Choose N5–N1 yourself.',
    startMock: 'Take a short placement mock',
    startMockBody: 'A quick check of language, reading, and listening.',
    manualTitle: 'Choose a provisional band',
    manualBody: 'You can change this later.',
    bandN5: 'N5 · first useful Japanese',
    bandN4: 'N4 · plans and connected sentences',
    bandN3: 'N3 · everyday native input and nuance',
    bandN2: 'N2 · evidence, stance, and formal language',
    bandN1: 'N1 · ambiguity, synthesis, and adaptation',
    mockTitle: 'A short placement check',
    mockBody: 'A guide to where to begin, not a JLPT score.',
    mockTargetLegend: 'Target band',
    mockPlayAudio: 'Play the listening line',
    mockAudioUnavailable: 'Japanese speech is unavailable in this browser. Choose another route or try a supported browser.',
    mockSpeakingConfidence: 'How confident are you speaking without a script?',
    mockWritingConfidence: 'How confident are you writing a short message?',
    mockSubmit: 'See my evidence',
    mockIncomplete: 'Answer each item before continuing.',
    mockResultTitle: 'Rie’s recommendation',
    mockKnowledge: 'Language knowledge',
    mockReading: 'Reading',
    mockListening: 'Listening',
    mockProduction: 'Speaking and writing confidence',
    mockRecommendation: 'Recommended entry',
    mockUseRecommendation: 'Use this recommendation',
    mockChooseMyself: 'Choose another band',
    bridgeEyebrow: 'Joining the class',
    bridgeTitle: 'Meet the class',
    bridgeBody: 'Rie introduces the class and the current term.',
    bridgeContinue: 'Continue',
    bandEntryEyebrow: 'Your first class',
    bandEntryTitle: 'Start where your Japanese is now.',
    bandEntryBody: 'Try a short task at your chosen level.',
    bandEntryComplete: 'Done. Earlier memories are waiting in your journal.',
    bandEntryContinue: 'Open the campus',
    lessonForkEyebrow: 'Lesson 0',
    lessonForkTitle: 'What should we start with?',
    lessonForkBody: 'Choose one.',
    forkSound: 'Sound',
    forkSoundBody: 'LL教室 · listen and shadow.',
    forkText: 'Text',
    forkTextBody: '図書館 · read and rebuild the line.',
    forkSpeaking: 'Speaking',
    forkSpeakingBody: '教室前 · rehearse and answer aloud.',
    sourceEyebrow: 'Week 1',
    sourceTitle: 'Ask for one more try',
    sourceBody: 'Rie has spoken too quickly. Choose the classroom phrase that asks her to repeat it.',
    sourceForkSoundIntro: 'Rie is already talking. Listen once.',
    sourceForkSoundPlay: 'Hear Rie',
    sourceForkTextIntro: 'The instruction is already on the board.',
    sourceForkSpeakingIntro: 'Rie has moved on. Try your reply aloud before looking.',
    sourceForkSpeakingTried: 'I tried a reply',
    sourceForkAudioUnavailable: 'Audio didn’t play. Continue with the choices.',
    sourceRecordSummary: 'Source note',
    sourceRecordLine: '2023/24 Level 1 · Lesson 1 · classroom-phrases payload · page 2 · printed item 9',
    sourceComplete: 'Added to your よむ reviews.',
    sourceDirectionsSetup: 'Next: まっすぐ · 右',
    sourceContinue: 'Meet Aakash outside',
    sourceReturn: 'Return to campus',
    aakashMeetEyebrow: 'After class',
    aakashMeetTitle: 'A better photo spot.',
    aakashMeetBody: '“I can see the cafe sign. The door is another matter.”',
    aakashUnlockEyebrow: 'New classmate',
    aakashUnlockTitle: 'Aakash',
    aakashUnlockLine: '“Straight ahead, then right. Great—before the rain changes its mind.”',
    aakashContinue: 'Return to campus',
    aakashMemoryTitle: 'The better photo spot',
    aakashMemoryBody: 'Rain on the map. A red umbrella. Aakash waits until you finish the direction, then points out the perfect light.',
    aakashMemoryReturn: 'Close the memory',
    kanjiDeskEyebrow: 'Writing Studio',
    kanjiDeskTitle: 'Make it. Then read it.',
    kanjiDeskBody: 'Start from いち / one. Write one left-to-right stroke.',
    kanjiDeskComplete: 'Lesson kanji complete.',
    kanjiDeskContinue: 'Open the campus',
    campusTitle: 'Campus',
    campusObjective: 'Next: your first Library review.',
    campusObjectiveComplete: 'Where next?',
    mapLabel: '学内案内',
    mapEntrance: '入口',
    mapChoose: '行き先',
    locationClassroom: '教室',
    locationClassroomBody: 'Continue class.',
    locationLibrary: '図書館',
    locationLibraryBody: 'Review words and saved lines.',
    locationLab: 'LL教室',
    locationLabBody: 'Listen and shadow.',
    locationCafe: 'カフェ',
    locationCafeBody: 'Talk after class.',
    locationOpen: 'Enter',
    locationUnavailable: 'Opens after the first review',
    locationNotOpen: 'Not open yet',
    locationReturn: 'Return to the campus',
    labEyebrow: 'Language Lab',
    labTitle: 'Hear it before you see it.',
    labBody: 'Listen, answer, then reveal the transcript.',
    labPlay: 'Play / replay the line',
    labTimecode: '00:00–00:02',
    labTranscriptTitle: 'Transcript after commitment',
    labShadowTitle: 'Shadow the line',
    labShadowPrompt: 'Replay it, say it once, then compare your timing.',
    labShadowDone: 'I repeated and compared it',
    labListeningComplete: 'Now reveal the transcript and try it aloud.',
    navCampus: 'Campus',
    navClass: 'Class',
    navReview: 'Study',
    navJournal: 'Class journal',
    navClassBoard: 'Class board',
    navClassBoardAccount: 'Class board · account',
    navEndToday: 'End for today',
    navPresentationStory: 'Story view',
    navPresentationCourse: 'Course view',
    navSwitchToStory: 'Switch to story view',
    navSwitchToCourse: 'Switch to course view',
    navSettings: 'Settings',
    navAudioMuted: 'Sound off',
    navAudioOn: 'Sound on',
    readingShow: 'Readings',
    readingHide: 'Hide readings',
    dayEndStageLabel: 'Classroom at the end of the day',
    dayEndRieAlt: 'Rie-sensei saying goodbye in the classroom',
    dayEndLine: '今日はここまでにしましょう。またね。',
    dayEndSupport: 'Let’s stop here for today. See you.',
    dayEndReturn: 'Return to campus',
    reviewTitle: 'Library review',
    reviewEmpty: 'Nothing due yet.',
    reviewReveal: 'Reveal meaning',
    reviewPrompt: 'Do you remember this phrase?',
    reviewAgain: 'Again',
    reviewHard: 'Hard',
    reviewGood: 'Good',
    reviewEasy: 'Easy',
    reviewComplete: 'Saved in よむ.',
    reviewReturn: 'Return to the campus',
    journalTitle: 'Class journal',
    journalRie: 'Rie-sensei',
    journalRieLine: '“One open chair is enough. We can begin.”',
    journalAakash: 'Aakash',
    journalAakashLine: '“Straight ahead, then right. Great.”',
    journalBond: 'Bond',
    journalReplay: 'Replay the opening memory',
    journalReplayAakash: 'Replay rainy directions',
    journalReason: 'Reason for learning',
    memoryTitle: 'The open chair',
    memoryBody: 'Rain on the windows. Rie balancing tea and a stack of papers. One chair left open for you.',
    memoryReturn: 'Close the memory',
    journalLocked: 'Meet someone in the story to unlock their page.',
    lessonOverviewBack: 'Back',
    lessonOverviewGoals: 'By the end',
    lessonOverviewSections: 'Lesson',
    lessonOverviewMaterials: 'On the desk',
    lessonOverviewPeople: 'In class',
    lessonOverviewProgress: 'Progress',
    lessonOverviewStart: 'Start',
    lessonOverviewResume: 'Resume',
    lessonOverviewReview: 'Review',
    lessonOverviewDone: 'Done',
    lessonOverviewInProgress: 'In progress',
    lessonOverviewNotStarted: 'Not started',
    lessonOverviewNeedsReview: 'Review',
    classPathTitle: 'Class',
    classPathWeeks: 'Path',
    classPathPeople: 'People',
    classPathEvents: 'Events',
} as const;

export type AcademyCopyKey = keyof typeof EN;

const JA: Record<AcademyCopyKey, string> = {
    academyName: 'よむアカデミー',
    languageToggle: 'English',
    utilityMenu: 'メニュー',
    loading: '少々お待ちください…',
    retry: 'もう一度',
    continue: '続ける',
    back: '戻る',
    accessBody: '最初のかなからN1まで、物語で遊びながら学ぶ日本語コース。',
    accessCodeLabel: 'クラスコード',
    accessCodePlaceholder: 'コードを入力',
    accessSubmit: '扉を開く',
    accessGetCode: 'クラスコードを入手',
    accessChecking: '確認しています…',
    accessInvalid: 'コードを確認して、もう一度お試しください。',
    accessUnavailable: 'コードを確認できませんでした。もう一度お試しください。',
    donationTitle: '一回だけのサポート',
    donationChooseAmount: '金額を選ぶ',
    donationOther: 'その他',
    donationOtherAmount: '金額（ポンド）',
    donationDescription: '安全な決済が完了すると、クラスコードが発行されます。',
    donationContinue: '決済へ進む',
    donationCancel: '今はしない',
    donationClose: '閉じる',
    donationStarting: '安全な決済を開いています…',
    donationInvalidAmount: '£2から£500までの金額を選んでください。',
    donationUnavailable: '決済を開始できませんでした。もう一度お試しください。',
    donationClaimChecking: 'クラスコードを確認しています…',
    donationClaimPending: '決済を確認しています。',
    donationClaimUnavailable: 'コードを受け取れませんでした。',
    donationClaimReady: 'クラスコードを入力しました。',
    donationClaimRetry: 'もう一度',
    donationClaimCopy: 'コードをコピー',
    donationClaimCopied: 'コピーしました',
    localQaSession: 'ローカルQAセッション',
    rieGreeting: 'こんばんは。雨の中、来てくれてありがとうございます。',
    rieGreetingSupport: 'こんばんは。雨の中を来てくださって、ありがとうございます。',
    fictionNote: 'これはAIが作ったフィクションで、実在の人物や出来事を描いたものではありません。',
    profileNameLabel: 'りえ先生になんと呼んでほしいですか。',
    profileNamePlaceholder: 'お名前',
    profileReasonLabel: 'なぜ日本語を勉強していますか。',
    profileReasonPlaceholder: '日記に残す自分だけのメモ',
    profilePortraitLegend: '物語の中の姿を選んでください',
    portraitCamera: 'カメラと折りたたみ地図を持つ学習者',
    portraitPlanner: '手帳と学習カードを持つ学習者',
    portraitCards: 'カードを差し出す学習者',
    portraitNotebook: '鉛筆とノートを持つ学習者',
    profileSubmit: 'りえ先生に伝える',
    rieUnlockEyebrow: '先生',
    rieUnlockTitle: 'りえ先生',
    rieUnlockBody: '「椅子が一つ空いていれば十分。始めましょう。」',
    rieUnlockContinue: '始める場所を選ぶ',
    bondFirstStar: '日記の最初のページ',
    relationshipFirstPage: '日記の最初のページが開きました',
    relationshipJournalProgress: '関係の日記',
    relationshipStage1: '出会い',
    relationshipStage2: '親しみ',
    relationshipStage3: '共通の笑い',
    relationshipStage4: '信頼',
    relationshipStage5: 'すれ違い',
    relationshipStage6: '仲直り',
    relationshipStage7: '支え合い',
    relationshipStage8: 'サポート',
    relationshipStage9: '共通の思い出',
    relationshipStage10: '続いていく絆',
    startEyebrow: '最初の一歩',
    startTitle: 'どこから始めましょうか。',
    startBody: 'あとで変更できます。',
    startLessonZero: 'レッスン0から始める',
    startLessonZeroBody: '音、教室表現、かな。',
    startManual: 'JLPTレベルを選ぶ',
    startManualBody: 'N5〜N1から自分で選びます。',
    startMock: '短いプレイスメント模試を受ける',
    startMockBody: '言語知識・読解・リスニングを短く確認します。',
    manualTitle: '仮のレベルを選んでください',
    manualBody: 'あとで変更できます。',
    bandN5: 'N5・最初の役立つ日本語',
    bandN4: 'N4・計画とつながった文',
    bandN3: 'N3・日常の生きた日本語とニュアンス',
    bandN2: 'N2・根拠、立場、フォーマルな表現',
    bandN1: 'N1・曖昧さ、統合、適応',
    mockTitle: '短いレベルチェック',
    mockBody: '出発点の目安です。JLPTのスコアではありません。',
    mockTargetLegend: '目標レベル',
    mockPlayAudio: 'リスニングの文を再生',
    mockAudioUnavailable: 'このブラウザでは日本語音声を再生できません。別のルートを選ぶか、対応ブラウザでお試しください。',
    mockSpeakingConfidence: '台本なしで話す自信はどのくらいありますか。',
    mockWritingConfidence: '短いメッセージを書く自信はどのくらいありますか。',
    mockSubmit: '結果を見る',
    mockIncomplete: '続ける前に、すべての問題に答えてください。',
    mockResultTitle: 'りえ先生のおすすめ',
    mockKnowledge: '言語知識',
    mockReading: '読解',
    mockListening: 'リスニング',
    mockProduction: '会話・作文の自信',
    mockRecommendation: 'おすすめの出発点',
    mockUseRecommendation: 'このおすすめを使う',
    mockChooseMyself: '別のレベルを選ぶ',
    bridgeEyebrow: '途中参加',
    bridgeTitle: 'クラスの紹介',
    bridgeBody: 'りえ先生がクラスと今学期について説明します。',
    bridgeContinue: '続ける',
    bandEntryEyebrow: '最初のクラス',
    bandEntryTitle: '今の日本語力から始めましょう。',
    bandEntryBody: '選んだレベルで、短い課題に挑戦しましょう。',
    bandEntryComplete: 'できました。以前の思い出は日記で待っています。',
    bandEntryContinue: 'キャンパスを開く',
    lessonForkEyebrow: 'レッスン0',
    lessonForkTitle: '最初に何から始めますか。',
    lessonForkBody: '一つ選んでください。',
    forkSound: '音',
    forkSoundBody: 'LL教室・聞いてシャドーイング。',
    forkText: '文字',
    forkTextBody: '図書館・読んで文を組み立てる。',
    forkSpeaking: '話す',
    forkSpeakingBody: '教室前・練習して声で答える。',
    sourceEyebrow: '第1週',
    sourceTitle: 'もう一度お願いする',
    sourceBody: 'りえ先生の話す速さが少し速すぎました。繰り返しを頼む教室表現を選んでください。',
    sourceForkSoundIntro: 'りえ先生はもう話しています。一度聞いてみましょう。',
    sourceForkSoundPlay: 'りえ先生を聞く',
    sourceForkTextIntro: '指示はもう黒板にあります。',
    sourceForkSpeakingIntro: 'りえ先生は次へ進みました。選択肢を見る前に、返事を声に出してみましょう。',
    sourceForkSpeakingTried: '返事を言ってみました',
    sourceForkAudioUnavailable: '音声を再生できませんでした。選択肢へ進んでください。',
    sourceRecordSummary: '出典メモ',
    sourceRecordLine: '2023/24 レベル1・レッスン1・教室表現ペイロード・2ページ・印刷番号9',
    sourceComplete: 'よむの復習に追加しました。',
    sourceDirectionsSetup: '次：まっすぐ・右',
    sourceContinue: '外でAakashに会う',
    sourceReturn: 'キャンパスに戻る',
    aakashMeetEyebrow: '放課後',
    aakashMeetTitle: 'もっといい撮影場所',
    aakashMeetBody: '「カフェの看板は見える。でも、入口は別の話だね。」',
    aakashUnlockEyebrow: '新しいクラスメート',
    aakashUnlockTitle: 'Aakash',
    aakashUnlockLine: '「まっすぐ行って、右。よし、雨の気が変わる前に行こう。」',
    aakashContinue: 'キャンパスに戻る',
    aakashMemoryTitle: 'もっといい撮影場所',
    aakashMemoryBody: '地図に落ちる雨。赤い傘。あなたが道順を言い終わるまで待ってから、完璧な光を指すAakash。',
    aakashMemoryReturn: '思い出を閉じる',
    kanjiDeskEyebrow: 'ライティングスタジオ',
    kanjiDeskTitle: '書いて、読む。',
    kanjiDeskBody: '「いち」から始めて、左から右へ一画で書きます。',
    kanjiDeskComplete: 'このレッスンの漢字が終わりました。',
    kanjiDeskContinue: 'キャンパスを開く',
    campusTitle: 'キャンパス',
    campusObjective: '次：図書館で最初の復習。',
    campusObjectiveComplete: '次はどこへ？',
    mapLabel: 'キャンパスマップ',
    mapEntrance: '入口',
    mapChoose: '行き先を選ぶ',
    locationClassroom: '教室',
    locationClassroomBody: '授業を続ける。',
    locationLibrary: '図書館',
    locationLibraryBody: '言葉と保存した文を復習する。',
    locationLab: 'LL教室',
    locationLabBody: '聞いて、声に出す。',
    locationCafe: 'カフェ',
    locationCafeBody: '放課後に話す。',
    locationOpen: '入る',
    locationUnavailable: '最初の復習後に開きます',
    locationNotOpen: 'まだ開いていません',
    locationReturn: 'キャンパスに戻る',
    labEyebrow: 'ランゲージラボ',
    labTitle: '見る前に、聞く。',
    labBody: '聞いて答えたら、文字を見ましょう。',
    labPlay: '音声を再生・もう一度再生',
    labTimecode: '00:00〜00:02',
    labTranscriptTitle: '回答後の文字起こし',
    labShadowTitle: '文をシャドーイングする',
    labShadowPrompt: 'もう一度再生し、一回声に出して、タイミングを比べてください。',
    labShadowDone: '繰り返して比べました',
    labListeningComplete: '文字を見て、声に出してみましょう。',
    navCampus: 'キャンパス',
    navClass: 'クラス',
    navReview: '学習',
    navJournal: 'クラス日記',
    navClassBoard: 'クラス掲示板',
    navClassBoardAccount: 'クラス掲示板・アカウント',
    navEndToday: '今日はここまで',
    navPresentationStory: '物語ビュー',
    navPresentationCourse: 'コースビュー',
    navSwitchToStory: '物語ビューに切り替える',
    navSwitchToCourse: 'コースビューに切り替える',
    navSettings: '設定',
    navAudioMuted: '音声オフ',
    navAudioOn: '音声オン',
    readingShow: '読み方',
    readingHide: '読み方を隠す',
    dayEndStageLabel: '一日の終わりの教室',
    dayEndRieAlt: '教室で別れの挨拶をするりえ先生',
    dayEndLine: '今日はここまでにしましょう。またね。',
    dayEndSupport: '今日はここまでにしましょう。またね。',
    dayEndReturn: 'キャンパスに戻る',
    reviewTitle: '図書館の復習',
    reviewEmpty: 'まだ復習はありません。',
    reviewReveal: '意味を見る',
    reviewPrompt: 'この表現を覚えていますか。',
    reviewAgain: 'もう一度',
    reviewHard: '難しい',
    reviewGood: 'できた',
    reviewEasy: '簡単',
    reviewComplete: 'よむに保存しました。',
    reviewReturn: 'キャンパスに戻る',
    journalTitle: 'クラス日記',
    journalRie: 'りえ先生',
    journalRieLine: '「椅子が一つ空いていれば十分。始めましょう。」',
    journalAakash: 'Aakash',
    journalAakashLine: '「まっすぐ行って、右。よし。」',
    journalBond: '絆',
    journalReplay: '最初の思い出をもう一度見る',
    journalReplayAakash: '雨の道案内をもう一度見る',
    journalReason: '日本語を学ぶ理由',
    memoryTitle: '空いていた椅子',
    memoryBody: '窓をたたく雨。お茶とプリントの山を抱えるりえ先生。あなたのために空いた椅子が一つ。',
    memoryReturn: '思い出を閉じる',
    journalLocked: '物語で誰かに会うと、その人のページが開きます。',
    lessonOverviewBack: '戻る',
    lessonOverviewGoals: '学習目標',
    lessonOverviewSections: 'レッスン',
    lessonOverviewMaterials: '教材',
    lessonOverviewPeople: 'クラスのみなさん',
    lessonOverviewProgress: '進み具合',
    lessonOverviewStart: '始める',
    lessonOverviewResume: '続ける',
    lessonOverviewReview: '復習する',
    lessonOverviewDone: '完了',
    lessonOverviewInProgress: '途中',
    lessonOverviewNotStarted: '未開始',
    lessonOverviewNeedsReview: '要復習',
    classPathTitle: 'クラス',
    classPathWeeks: '道のり',
    classPathPeople: 'みんな',
    classPathEvents: 'イベント',
};

export function academyText(language: AcademyLanguage, key: AcademyCopyKey): string {
    return language === 'ja' ? JA[key] : EN[key];
}

export function academyCopyHasMissingJapanese(): boolean {
    return (Object.keys(EN) as AcademyCopyKey[]).some(key => !JA[key].trim() || JA[key] === '未翻訳');
}
