export type AcademyLanguage = 'en' | 'ja';

const EN = {
    academyName: 'よむ Academy',
    languageToggle: '日本語',
    utilityMenu: 'Menu',
    offlineNoticeTitle: 'Offline',
    offlineNoticeBody: 'Keep learning here. Your progress will sync when you reconnect.',
    loading: 'One moment…',
    retry: 'Try again',
    continue: 'Continue',
    back: 'Back',
    accessBody: 'A playable Japanese course from first kana to N1.',
    accessCodeLabel: 'Class code',
    accessCodePlaceholder: 'Enter code',
    accessSubmit: 'Open the doors',
    accessGetCode: 'Get a class code',
    accessChecking: 'One moment…',
    accessInvalid: 'Check the code and try again.',
    accessUnavailable: 'Couldn’t check that code. Try again.',
    donationTitle: 'One-time support',
    donationChooseAmount: 'Choose an amount',
    donationOther: 'Other',
    donationOtherAmount: 'Amount in pounds',
    donationAmountPlaceholder: 'Your amount',
    donationDescription: 'Your class code is generated after secure checkout.',
    donationContinue: 'Continue to checkout',
    donationCancel: 'Not now',
    donationClose: 'Close',
    donationStarting: 'Opening secure checkout…',
    donationInvalidAmount: 'Choose an amount from £5 to £500.',
    donationUnavailable: 'Checkout could not be started. Try again.',
    donationClaimChecking: 'Finding your class code…',
    donationClaimPending: 'Payment is still settling.',
    donationClaimUnavailable: 'Couldn’t retrieve the code.',
    donationClaimReady: 'Your class code is ready.',
    donationClaimRetry: 'Try again',
    donationClaimCopy: 'Copy code',
    donationClaimCopied: 'Copied',
    localQaSession: 'Local QA session',
    rieGreeting: 'こんばんは。雨の中、\n来てくれてありがとうございます。',
    rieGreetingSupport: 'Good evening. Thank you for coming through the rain.',
    fictionNote: 'This is an AI-created fiction, not an account of real people or events.',
    profileNameLabel: 'What name would you like Rie-sensei to use?',
    profileNamePlaceholder: 'Your name',
    profileNameDialogue: 'こんばんは。雨の中、よく来てくれましたね。なんとお呼びしましょうか。',
    profileNameDialogueSupport: 'Good evening. I’m glad you made it through the rain. What should I call you?',
    profileReasonLabel: 'What would you like to do in Japanese?',
    profileReasonPlaceholder: 'Read manga, talk with family, travel…',
    profileReasonDialogue: '{name}さん、日本語で何ができるようになりたいですか。',
    profileReasonDialogueSupport: '{name}, what would you like to be able to do in Japanese?',
    profilePortraitLegend: 'Choose how you appear in the story',
    profilePortraitDialogue: '最後に、物語の中のあなたを選んでください。',
    profilePortraitDialogueSupport: 'One last thing. Choose how you will appear in our story.',
    profilePlayerFallback: 'You',
    profilePlayerAlt: 'Your character in the story',
    portraitCamera: 'Camera and folded map',
    portraitPlanner: 'Planner and study cards',
    portraitCards: 'Offering a card',
    portraitNotebook: 'Pencil and notebook',
    profileSubmit: 'That’s me',
    rieUnlockEyebrow: 'Teacher profile',
    rieUnlockTitle: 'Rie-sensei',
    rieUnlockBody: '“One open chair is enough. We can begin.”',
    rieUnlockContinue: 'Choose where to begin',
    rieIntroductionStageLabel: 'Your first conversation with Rie-sensei',
    rieIntroductionMemoryLabel: 'Your first conversation with Rie-sensei, from the journal',
    rieIntroductionListen: 'Hear Rie',
    rieIntroductionListening: 'Rie is speaking…',
    rieIntroductionHeard: 'Rie is waiting by the open chair.',
    rieIntroductionAudioUnavailable: 'You can read Rie’s line and continue.',
    rieIntroductionSaveFailed: 'That didn’t save. Try once more.',
    rieIntroductionContinue: 'Come in',
    rieIntroductionReturn: 'Return to the journal',
    bondFirstStar: 'First page',
    relationshipFirstPage: 'Rie joined your journal',
    relationshipJournalProgress: 'Relationship journal',
    relationshipStage1: 'First meeting',
    relationshipStage2: 'Familiar faces',
    relationshipStage3: 'Running joke',
    relationshipStage4: 'A little trust',
    relationshipStage5: 'Things unsaid',
    relationshipStage6: 'Making it right',
    relationshipStage7: 'Your turn, my turn',
    relationshipStage8: 'Showed up',
    relationshipStage9: 'Remember when',
    relationshipStage10: 'Still here',
    startEyebrow: 'Rie-sensei',
    startTitle: 'Where should we start?',
    startBody: 'Pick the one that feels closest. You can change it later.',
    startLessonZero: "I'm brand new",
    startLessonZeroBody: 'Begin with sounds, classroom phrases, and the first kana. No Japanese needed.',
    startManual: 'I know my level',
    startManualBody: 'Choose N5, N4, N3, N2, or N1 yourself.',
    startMock: 'Help me choose',
    startMockBody: 'Try a short listening, reading, and language check.',
    startChoiceError: "That path didn't open. Try again.",
    manualTitle: 'What have you studied?',
    manualBody: 'Choose the closest level. You can move up or down later.',
    manualHint: "Not sure? Go back and choose 'Help me choose'.",
    manualChoiceError: "That level didn't open. Try again.",
    bandN5: 'I know the foundations',
    bandN5Body: 'Kana, greetings, and short everyday sentences.',
    bandN4: 'I can handle daily routines',
    bandN4Body: 'Plans, reasons, past experiences, and connected sentences.',
    bandN3: 'I follow everyday Japanese',
    bandN3Body: 'Longer conversations and native material with some support.',
    bandN2: 'I follow detailed Japanese',
    bandN2Body: 'News, formal writing, and implied meaning.',
    bandN1: 'I handle dense Japanese',
    bandN1Body: 'Fast speech, nuance, ambiguity, and specialist topics.',
    mockTitle: 'Find a comfortable starting point',
    mockBody: 'Choose a familiar level. Rie will show you each task before it counts.',
    mockTargetLegend: 'Which level should we try?',
    mockGuideTitle: 'One example, then one small stretch',
    mockGuideBody: 'Nothing here locks you in. Use Back whenever a level feels too easy or too hard.',
    mockGuideLanguage: 'Language: make the whole sentence work.',
    mockGuideReading: 'Reading: look for who, what changed, and when.',
    mockGuideListening: 'Listening: play the line before choosing. Replay is always allowed.',
    mockChooseAnswer: 'Choose the best answer.',
    mockPlayAudio: 'Play the listening',
    mockAudioUnavailable: 'The audio did not play. Try again or use the text alternative.',
    mockSourceRecordingLabel: 'Play the listening',
    mockSourceRecordingUnavailable: 'The audio did not play. Use the text alternative below.',
    mockListeningRequired: 'Play the line or use the text alternative before continuing.',
    mockTranscriptAlternative: 'Use text instead',
    mockTranscriptNotice: 'This keeps the check accessible, but it will not count as listening evidence.',
    mockProductionTitle: 'Now make the language yours',
    mockProductionBody: 'Try both prompts once, then choose how each attempt felt. Rie uses the attempt, not confidence alone.',
    mockSpeakingConfidence: 'Speaking attempt',
    mockWritingConfidence: 'Writing attempt',
    mockModeAloud: 'Say it aloud',
    mockModeTypeInstead: 'Type instead',
    mockModeTyped: 'Type in Japanese',
    mockModePaper: 'Write it on paper',
    mockTriedAloud: 'I tried the line aloud.',
    mockWroteOnPaper: 'I wrote the line on paper.',
    mockResponsePlaceholder: 'Your Japanese line',
    mockConfidenceLegend: 'How did that attempt feel?',
    mockConfidenceNotYet: 'Not yet',
    mockConfidenceSupported: 'With some effort',
    mockConfidenceIndependent: 'Comfortable on my own',
    mockSubmit: 'See Rie’s suggestion',
    mockIncomplete: 'Answer each item before continuing.',
    mockProductionIncomplete: 'Try both production prompts and choose how each attempt felt.',
    mockSaveError: 'That step did not save. Try once more.',
    mockResultTitle: 'Rie’s recommendation',
    mockResultBody: 'A starting suggestion from this attempt. You still choose where to begin.',
    mockResultEvidence: 'Rie used six short questions and two production self-checks. This is a starting suggestion, not an official score.',
    mockResultTranscriptEvidence: 'Text alternatives stayed available, and those questions were not counted as listening.',
    mockResultContinuity: 'Changing your starting level will not reset or skip the story.',
    mockKnowledge: 'Language knowledge',
    mockReading: 'Reading',
    mockListening: 'Listening',
    mockSpeaking: 'Speaking self-check',
    mockWriting: 'Writing self-check',
    mockRecommendation: 'Recommended entry',
    mockUseRecommendation: 'Use this recommendation',
    mockChooseMyself: 'Choose another band',
    mockReview: 'Review or retake this mock',
    bridgeEyebrow: 'Joining the class',
    bridgeTitle: 'Meet the class',
    bridgeBody: 'Rie catches you up on the story so far, then walks you through the gate toward your class.',
    bridgeContinue: 'Enter the campus',
    bandEntryEyebrow: 'Your first class',
    bandEntryTitle: 'Start where your Japanese is now.',
    bandEntryBody: 'Try a short task at your chosen level.',
    bandEntryComplete: 'Done. Earlier memories are waiting in your journal.',
    bandEntryContinue: 'Enter the campus',
    advancedEntryEyebrow: 'N3 arrival · listening check',
    advancedEntryTitle: 'Listen once before you join the class.',
    advancedEntryBody: 'Rie uses one short listening task to decide how much support to show when class begins.',
    advancedEntryModeGuided: 'Rie will guide this attempt',
    advancedEntryModeTestOut: 'Try it independently',
    advancedEntryModeRepair: 'Focus on the part that needs repair',
    advancedEntryModeIndependent: 'Start without hints',
    advancedEntryTeachingTitle: 'Listen, then decide',
    advancedEntryTeachingBody: 'Each short dialogue ends with a statement. Choose ○ when the statement matches and × when it conflicts. The transcript and answers stay hidden until your first commitment.',
    advancedEntryIndependentBody: 'Your existing evidence supports an independent attempt. The transcript, answers, and repair stay hidden until you commit.',
    advancedEntryContinuity: 'This only changes how much help you see. Nothing in the story is skipped.',
    advancedEntryComplete: 'Done. Rie will use this result to adjust later listening support.',
    advancedEntryContinue: 'Enter the campus',
    lessonForkEyebrow: 'Lesson 0',
    lessonForkTitle: 'What should we start with?',
    lessonForkBody: 'Choose one.',
    forkSound: 'Sound',
    forkSoundBody: '語学ラボ · listen and shadow.',
    forkText: 'Text',
    forkTextBody: '図書館 · read and rebuild the line.',
    forkSpeaking: 'Speaking',
    forkSpeakingBody: '教室前 · rehearse and answer aloud.',
    sourceEyebrow: 'Week 1',
    sourceTitle: 'Ask for one more try',
    sourceBody: 'Rie spoke a little too quickly. Choose the classroom phrase that asks her to repeat it.',
    sourceForkSoundIntro: 'Rie is already talking. Listen once.',
    sourceForkSoundPlay: 'Hear Rie',
    sourceForkTextIntro: 'The instruction is already on the board.',
    sourceForkSpeakingIntro: 'Rie has moved on. Try your reply aloud before looking.',
    sourceForkSpeakingTried: 'I tried a reply',
    sourceForkAudioUnavailable: 'Audio didn’t play. Continue with the choices.',
    sourceRecordSummary: 'Source note',
    sourceRecordLine: '2023/24 Level 1 · Lesson 1 · classroom phrases · page 2 · printed item 9',
    sourceComplete: 'Added to your よむ reviews.',
    sourceDirectionsSetup: 'Next: まっすぐ · 右',
    sourceContinue: 'Meet Aakash outside',
    sourceReturn: 'Return to campus',
    aakashMeetEyebrow: 'After class',
    aakashMeetTitle: 'A better photo spot.',
    aakashMeetBody: '“I can see the cafe sign. The door is another matter.”',
    aakashUnlockEyebrow: 'New classmate',
    aakashUnlockTitle: 'Aakash',
    aakashUnlockLine: '“Straight ahead, then right. Great—before the rain changes its mind.”',
    aakashContinue: 'Return to campus',
    aakashMemoryTitle: 'The better photo spot',
    aakashMemoryBody: 'Rain on the map. A red umbrella. Aakash waits until you finish the direction, then points out the perfect light.',
    aakashMemoryReturn: 'Close the memory',
    kanjiDeskEyebrow: 'Writing Studio',
    kanjiDeskTitle: 'Make it. Then read it.',
    kanjiDeskBody: 'Start from いち / one. Write one left-to-right stroke.',
    kanjiDeskComplete: 'Lesson kanji complete.',
    kanjiDeskContinue: 'Enter the campus',
    campusTitle: 'キャンパス',
    mapLabel: '学内案内',
    mapEntrance: '入口',
    mapChoose: '行き先',
    locationClassroom: '教室',
    locationClassroomBody: 'Go to class.',
    locationLibrary: '図書館',
    locationLibraryBody: 'Review words and saved lines.',
    locationLab: '語学ラボ',
    locationLabBody: 'Listen and shadow.',
    locationCafe: 'カフェ',
    locationCafeBody: 'Talk after class.',
    locationOpen: 'Enter',
    locationUnavailable: 'Opens after the first review',
    locationNotOpen: 'Not open yet',
    locationReturn: 'Return to the campus',
    labEyebrow: '語学ラボ',
    labTitle: 'Hear it before you see it.',
    labBody: 'Listen, answer, then reveal the transcript.',
    labPlay: 'Play / replay the line',
    labTimecode: '00:00–00:02',
    labTranscriptTitle: 'Transcript after commitment',
    labShadowTitle: 'Shadow the line',
    labShadowPrompt: 'Replay it, say it once, then compare your timing.',
    labShadowDone: 'I repeated and compared it',
    labListeningComplete: 'Now reveal the transcript and try it aloud.',
    navCampus: 'Campus',
    navClass: 'Class',
    navReview: 'Study',
    navJournal: 'Class journal',
    navClassBoard: 'Class board',
    navClassBoardAccount: 'Class board · account',
    navEndToday: 'End for today',
    navPresentationStory: 'Story view',
    navPresentationCourse: 'Course view',
    navSwitchToStory: 'Switch to story view',
    navSwitchToCourse: 'Switch to course view',
    navSettings: 'Settings',
    navAudioMuted: 'Sound off',
    navAudioOn: 'Sound on',
    utilityLinkHome: 'Yomu home',
    utilityLinkStudy: 'Study',
    utilityLinkSupport: 'Support',
    utilityLinkDiscord: 'Discord',
    utilityLinkGitHub: 'GitHub',
    readingShow: 'Readings',
    readingHide: 'Hide readings',
    dayEndStageLabel: 'Classroom at the end of the day',
    dayEndRieAlt: 'Rie-sensei saying goodbye in the classroom',
    dayEndLine: '今日はここまでにしましょう。またね。',
    dayEndSupport: 'Let’s stop here for today. See you.',
    dayEndReturn: 'Return to campus',
    reviewTitle: 'Library review',
    reviewEmpty: 'Nothing due yet.',
    reviewReveal: 'Reveal meaning',
    reviewPrompt: 'Do you remember this phrase?',
    reviewAgain: 'Again',
    reviewHard: 'Hard',
    reviewGood: 'Good',
    reviewEasy: 'Easy',
    reviewComplete: 'Saved in よむ.',
    reviewReturn: 'Return to the campus',
    journalTitle: 'Class journal',
    classBoardTitle: 'Class Board',
    journalRie: 'Rie-sensei',
    journalRieLine: '“One open chair is enough. We can begin.”',
    journalAakash: 'Aakash',
    journalAakashLine: '“Straight ahead, then right. Great.”',
    journalPeter: 'Peter',
    journalShaun: 'Shaun',
    journalBond: 'Bond',
    journalReplay: 'Replay the opening memory',
    journalReplayAakash: 'Replay rainy directions',
    journalReason: 'Reason for learning',
    memoryTitle: 'The open chair',
    memoryBody: 'Rain on the windows. Rie balancing a stack of papers, her tea going cold beside them. One chair left open for you.',
    memoryReturn: 'Close the memory',
    journalLocked: 'Meet someone in the story to unlock their page.',
    replayStreamTitle: 'NG+ replay stream',
    replayStreamDaily: 'Today',
    replayStreamWeekly: 'This week',
    replayStreamCanonProgress: 'Canon: {completed} / {total} chapters',
    replayStreamCanonBoundary: 'Replay is a practice memory. It cannot change canon, relationships, or graduation.',
    replayStreamGraduated: 'Graduation is complete. Replay continues as practice memories.',
    replayStreamNoPractice: 'Complete an authored scene and master its language to unlock a higher-language replay.',
    replayStreamDueCallback: 'Due SRS callback',
    replayStreamHigherReplay: 'Higher-language replay',
    replayStreamSliceOfLife: 'Optional slice-of-life practice',
    replayStreamOpenMemory: 'Open memory',
    replayStreamOpenLesson: 'Revisit lesson',
    lessonOverviewBack: 'Back',
    lessonOverviewGoals: 'By the end',
    lessonOverviewSections: 'Lesson',
    lessonOverviewMaterials: 'On the desk',
    lessonOverviewPeople: 'In class',
    lessonOverviewProgress: 'Progress',
    lessonOverviewStart: 'Start',
    lessonOverviewResume: 'Resume',
    lessonOverviewReview: 'Review',
    lessonOverviewDone: 'Done',
    lessonOverviewInProgress: 'In progress',
    lessonOverviewNotStarted: 'Not started',
    lessonOverviewNeedsReview: 'Review',
    classPathTitle: 'Class',
    classPathWeeks: 'Path',
    classPathPeople: 'People',
    classPathEvents: 'Events',
} as const;

export type AcademyCopyKey = keyof typeof EN;

const JA: Record<AcademyCopyKey, string> = {
    academyName: 'よむアカデミー',
    languageToggle: 'English',
    utilityMenu: 'メニュー',
    offlineNoticeTitle: 'オフライン',
    offlineNoticeBody: 'このまま学べます。記録は再接続したときに同期されます。',
    loading: '少々お待ちください…',
    retry: 'もう一度',
    continue: '続ける',
    back: '戻る',
    accessBody: '最初のかなからN1まで、物語で遊びながら学ぶ日本語コース。',
    accessCodeLabel: 'クラスコード',
    accessCodePlaceholder: 'コードを入力',
    accessSubmit: '扉を開く',
    accessGetCode: 'クラスコードを入手',
    accessChecking: '確認しています…',
    accessInvalid: 'コードを確認して、もう一度お試しください。',
    accessUnavailable: 'コードを確認できませんでした。もう一度お試しください。',
    donationTitle: '一回だけのサポート',
    donationChooseAmount: '金額を選ぶ',
    donationOther: 'その他',
    donationOtherAmount: '金額（ポンド）',
    donationAmountPlaceholder: '金額を入力',
    donationDescription: '安全な決済が完了すると、クラスコードが発行されます。',
    donationContinue: '決済へ進む',
    donationCancel: '今はしない',
    donationClose: '閉じる',
    donationStarting: '安全な決済を開いています…',
    donationInvalidAmount: '£5から£500までの金額を選んでください。',
    donationUnavailable: '決済を開始できませんでした。もう一度お試しください。',
    donationClaimChecking: 'クラスコードを確認しています…',
    donationClaimPending: '決済を確認しています。',
    donationClaimUnavailable: 'コードを受け取れませんでした。',
    donationClaimReady: 'クラスコードを入力しました。',
    donationClaimRetry: 'もう一度',
    donationClaimCopy: 'コードをコピー',
    donationClaimCopied: 'コピーしました',
    localQaSession: 'ローカルQAセッション',
    rieGreeting: 'こんばんは。雨の中、\n来てくれてありがとうございます。',
    rieGreetingSupport: 'こんばんは。雨の中を来てくださって、ありがとうございます。',
    fictionNote: 'これはAIが作ったフィクションで、実在の人物や出来事を描いたものではありません。',
    profileNameLabel: 'りえ先生には、なんと呼んでほしいですか。',
    profileNamePlaceholder: 'お名前',
    profileNameDialogue: 'こんばんは。雨の中、よく来てくれましたね。なんとお呼びしましょうか。',
    profileNameDialogueSupport: 'Good evening. I’m glad you made it through the rain. What should I call you?',
    profileReasonLabel: '日本語で、何ができるようになりたいですか。',
    profileReasonPlaceholder: '漫画を読む、家族と話す、旅行する…',
    profileReasonDialogue: '{name}さん、日本語で何ができるようになりたいですか。',
    profileReasonDialogueSupport: '{name}さん、日本語で何ができるようになりたいですか。',
    profilePortraitLegend: '物語の中の姿を選んでください',
    profilePortraitDialogue: '最後に、物語の中のあなたを選んでください。',
    profilePortraitDialogueSupport: '最後に、物語の中のあなたの姿を選んでください。',
    profilePlayerFallback: 'あなた',
    profilePlayerAlt: '物語の中のあなた',
    portraitCamera: 'カメラと地図',
    portraitPlanner: '手帳と学習カード',
    portraitCards: 'カードを渡す',
    portraitNotebook: '鉛筆とノート',
    profileSubmit: 'これが私です',
    rieUnlockEyebrow: '先生プロフィール',
    rieUnlockTitle: 'りえ先生',
    rieUnlockBody: '「椅子が一つ空いていれば十分。始めましょう。」',
    rieUnlockContinue: '始める場所を選ぶ',
    rieIntroductionStageLabel: 'りえ先生との最初の会話',
    rieIntroductionMemoryLabel: '日記で振り返る、りえ先生との最初の会話',
    rieIntroductionListen: 'りえ先生の声を聞く',
    rieIntroductionListening: 'りえ先生が話しています…',
    rieIntroductionHeard: 'りえ先生が空いている席で待っています。',
    rieIntroductionAudioUnavailable: 'りえ先生の言葉を読んで、先へ進めます。',
    rieIntroductionSaveFailed: '保存できませんでした。もう一度お試しください。',
    rieIntroductionContinue: '教室に入る',
    rieIntroductionReturn: '日記に戻る',
    bondFirstStar: '最初のページ',
    relationshipFirstPage: 'りえ先生が日記に加わりました',
    relationshipJournalProgress: '関係の日記',
    relationshipStage1: 'はじめまして',
    relationshipStage2: '顔なじみ',
    relationshipStage3: 'いつもの冗談',
    relationshipStage4: '小さな信頼',
    relationshipStage5: 'すれ違い',
    relationshipStage6: '仲直り',
    relationshipStage7: 'おたがいさま',
    relationshipStage8: 'そばにいる',
    relationshipStage9: '思い出',
    relationshipStage10: 'これからも',
    startEyebrow: 'りえ先生',
    startTitle: 'どこから始めましょうか。',
    startBody: 'いちばん近いものを選んでください。あとで変えられます。',
    startLessonZero: 'はじめてです',
    startLessonZeroBody: '音と教室のことば、最初のかなから始めます。日本語が初めてでも大丈夫です。',
    startManual: 'レベルが分かります',
    startManualBody: 'N5・N4・N3・N2・N1から自分で選びます。',
    startMock: 'いっしょに決めたいです',
    startMockBody: '聞く・読む・ことばの短いチェックで、始める場所を探します。',
    startChoiceError: 'うまく開けませんでした。もう一度試してください。',
    manualTitle: 'どのくらい勉強しましたか。',
    manualBody: 'いちばん近いレベルを選んでください。あとで上げたり下げたりできます。',
    manualHint: '迷ったら、戻って「いっしょに決めたいです」を選べます。',
    manualChoiceError: 'そのレベルを開けませんでした。もう一度試してください。',
    bandN5: '基礎が分かります',
    bandN5Body: 'かな、あいさつ、短い日常の文。',
    bandN4: '日常のやり取りができます',
    bandN4Body: '予定、理由、経験、つながった文。',
    bandN3: '日常の日本語を追えます',
    bandN3Body: '少し助けがあれば、長い会話や生の素材を追えます。',
    bandN2: '詳しい日本語を追えます',
    bandN2Body: 'ニュース、かたい文章、言外の意味。',
    bandN1: '密度の高い日本語を扱えます',
    bandN1Body: '速い会話、ニュアンス、曖昧さ、専門的な話題。',
    mockTitle: '無理のない出発点を見つける',
    mockBody: '分かりそうなレベルを選んでください。採点の前に、りえ先生が進め方を見せます。',
    mockTargetLegend: 'どのレベルを試しますか。',
    mockGuideTitle: 'お手本を一つ見て、少しだけ先へ',
    mockGuideBody: 'ここでは何も固定されません。簡単すぎたり難しすぎたりしたら、いつでも戻れます。',
    mockGuideLanguage: 'ことば：文全体が自然になる形を選びます。',
    mockGuideReading: '読む：だれが、何が変わったか、いつかを探します。',
    mockGuideListening: '聞く：答える前に音声を再生します。何度聞いてもかまいません。',
    mockChooseAnswer: 'もっとも正しい答えを選んでください。',
    mockPlayAudio: 'リスニングを再生',
    mockAudioUnavailable: '音声を再生できませんでした。もう一度試すか、文字の代替を使ってください。',
    mockSourceRecordingLabel: 'リスニングを再生',
    mockSourceRecordingUnavailable: '音声を再生できませんでした。下の文字の代替を使えます。',
    mockListeningRequired: '音声を再生するか、文字で確認してから進んでください。',
    mockTranscriptAlternative: '文字で確認する',
    mockTranscriptNotice: '続けることはできますが、リスニングの結果には数えません。',
    mockProductionTitle: '次は、自分のことばにする',
    mockProductionBody: '二つの課題を一度ずつ試し、それぞれの手応えを選んでください。自信だけではなく、実際の試みを使います。',
    mockSpeakingConfidence: '話す課題',
    mockWritingConfidence: '書く課題',
    mockModeAloud: '声に出す',
    mockModeTypeInstead: '代わりに入力する',
    mockModeTyped: '日本語で入力する',
    mockModePaper: '紙に書く',
    mockTriedAloud: '一度、声に出して言いました。',
    mockWroteOnPaper: '一度、紙に書きました。',
    mockResponsePlaceholder: 'あなたの日本語の文',
    mockConfidenceLegend: '今回の手応えはどうでしたか。',
    mockConfidenceNotYet: 'まだ難しい',
    mockConfidenceSupported: '少し考えればできる',
    mockConfidenceIndependent: '自分で無理なくできる',
    mockSubmit: 'りえ先生のおすすめを見る',
    mockIncomplete: '続ける前に、すべての問題に答えてください。',
    mockProductionIncomplete: '二つの課題を試し、それぞれの手応えを選んでください。',
    mockSaveError: 'この段階を保存できませんでした。もう一度試してください。',
    mockResultTitle: 'りえ先生のおすすめ',
    mockResultBody: '今回の結果から考えた出発点です。最後に決めるのはあなたです。',
    mockResultEvidence: '短い6問と、話す・書く二つの自己確認を使った目安です。公式の試験結果ではありません。',
    mockResultTranscriptEvidence: '文字で確認した問題は、聞く力の結果には数えていません。',
    mockResultContinuity: '出発レベルを変えても、物語の進行は失われません。',
    mockKnowledge: '言語知識',
    mockReading: '読解',
    mockListening: 'リスニング',
    mockSpeaking: '話す自己チェック',
    mockWriting: '書く自己チェック',
    mockRecommendation: 'おすすめの出発点',
    mockUseRecommendation: 'このおすすめを使う',
    mockChooseMyself: '別のレベルを選ぶ',
    mockReview: 'この模試を見直す・受け直す',
    bridgeEyebrow: '途中参加',
    bridgeTitle: 'クラスの紹介',
    bridgeBody: 'りえ先生がここまでの物語を紹介し、キャンパスの入口からあなたのクラスへ案内します。',
    bridgeContinue: 'キャンパスに入る',
    bandEntryEyebrow: '最初のクラス',
    bandEntryTitle: '今の日本語力から始めましょう。',
    bandEntryBody: '選んだレベルで、短い課題に挑戦しましょう。',
    bandEntryComplete: 'できました。以前の思い出は日記で待っています。',
    bandEntryContinue: 'キャンパスに入る',
    advancedEntryEyebrow: 'N3途中参加・聞き取り確認',
    advancedEntryTitle: 'クラスに入る前に、一度聞いてみましょう。',
    advancedEntryBody: 'りえ先生が短い聞き取り課題を使い、授業で表示する助けの量を調整します。',
    advancedEntryModeGuided: 'りえ先生と一緒に取り組みます',
    advancedEntryModeTestOut: '自力で確認します',
    advancedEntryModeRepair: '聞き取りにくいところを直します',
    advancedEntryModeIndependent: 'ヒントなしで始めます',
    advancedEntryTeachingTitle: '聞いて、判断する',
    advancedEntryTeachingBody: '短い会話の最後に文が流れます。会話と同じなら○、違うなら×を選びます。最初に答えるまで、台本と正解は表示されません。',
    advancedEntryIndependentBody: 'これまでの学習記録から、自力で取り組めます。答えるまで、台本・正解・修復支援は表示されません。',
    advancedEntryContinuity: 'ここで変わるのは、表示する助けの量だけです。物語は飛ばされません。',
    advancedEntryComplete: 'できました。りえ先生が、この結果を今後の聞き取り支援に使います。',
    advancedEntryContinue: 'キャンパスに入る',
    lessonForkEyebrow: 'レッスン0',
    lessonForkTitle: '最初に何から始めますか。',
    lessonForkBody: '一つ選んでください。',
    forkSound: '音',
    forkSoundBody: '語学ラボ・聞いてシャドーイング。',
    forkText: '文字',
    forkTextBody: '図書館・読んで文を組み立てる。',
    forkSpeaking: '話す',
    forkSpeakingBody: '教室前・練習して声で答える。',
    sourceEyebrow: '第1週',
    sourceTitle: 'もう一度お願いする',
    sourceBody: 'りえ先生の話が少し速すぎました。繰り返しを頼む教室表現を選んでください。',
    sourceForkSoundIntro: 'りえ先生はもう話しています。一度聞いてみましょう。',
    sourceForkSoundPlay: 'りえ先生を聞く',
    sourceForkTextIntro: '指示はもう黒板にあります。',
    sourceForkSpeakingIntro: 'りえ先生は次へ進みました。選択肢を見る前に、返事を声に出してみましょう。',
    sourceForkSpeakingTried: '返事を言ってみました',
    sourceForkAudioUnavailable: '音声を再生できませんでした。選択肢へ進んでください。',
    sourceRecordSummary: '出典メモ',
    sourceRecordLine: '2023/24 レベル1・レッスン1・教室表現・2ページ・印刷番号9',
    sourceComplete: 'よむの復習に追加しました。',
    sourceDirectionsSetup: '次：まっすぐ・右',
    sourceContinue: '外でAakashに会う',
    sourceReturn: 'キャンパスに戻る',
    aakashMeetEyebrow: '放課後',
    aakashMeetTitle: 'もっといい撮影場所',
    aakashMeetBody: '「カフェの看板は見える。でも、入口は別の話だね。」',
    aakashUnlockEyebrow: '新しいクラスメート',
    aakashUnlockTitle: 'Aakash',
    aakashUnlockLine: '「まっすぐ行って、右。よし、雨の気が変わる前に行こう。」',
    aakashContinue: 'キャンパスに戻る',
    aakashMemoryTitle: 'もっといい撮影場所',
    aakashMemoryBody: '地図に落ちる雨。赤い傘。あなたが道順を言い終わるまで待ってから、完璧な光を指すAakash。',
    aakashMemoryReturn: '思い出を閉じる',
    kanjiDeskEyebrow: 'ライティングスタジオ',
    kanjiDeskTitle: '書いて、読む。',
    kanjiDeskBody: '「いち」から始めて、左から右へ一画で書きます。',
    kanjiDeskComplete: 'このレッスンの漢字が終わりました。',
    kanjiDeskContinue: 'キャンパスに入る',
    campusTitle: 'キャンパス',
    mapLabel: 'キャンパスマップ',
    mapEntrance: '入口',
    mapChoose: '行き先を選ぶ',
    locationClassroom: '教室',
    locationClassroomBody: '授業へ行く。',
    locationLibrary: '図書館',
    locationLibraryBody: '言葉と保存した文を復習する。',
    locationLab: '語学ラボ',
    locationLabBody: '聞いて、声に出す。',
    locationCafe: 'カフェ',
    locationCafeBody: '放課後に話す。',
    locationOpen: '入る',
    locationUnavailable: '最初の復習後に開きます',
    locationNotOpen: 'まだ開いていません',
    locationReturn: 'キャンパスに戻る',
    labEyebrow: '語学ラボ',
    labTitle: '見る前に、聞く。',
    labBody: '聞いて答えたら、文字を見ましょう。',
    labPlay: '音声を再生・もう一度再生',
    labTimecode: '00:00〜00:02',
    labTranscriptTitle: '回答後の文字起こし',
    labShadowTitle: '文をシャドーイングする',
    labShadowPrompt: 'もう一度再生し、一回声に出して、タイミングを比べてください。',
    labShadowDone: '繰り返して比べました',
    labListeningComplete: '文字を見て、声に出してみましょう。',
    navCampus: 'キャンパス',
    navClass: 'クラス',
    navReview: '学習',
    navJournal: 'クラス日記',
    navClassBoard: 'クラス掲示板',
    navClassBoardAccount: 'クラス掲示板・アカウント',
    navEndToday: '今日はここまで',
    navPresentationStory: '物語ビュー',
    navPresentationCourse: 'コースビュー',
    navSwitchToStory: '物語ビューに切り替える',
    navSwitchToCourse: 'コースビューに切り替える',
    navSettings: '設定',
    navAudioMuted: '音声オフ',
    navAudioOn: '音声オン',
    utilityLinkHome: 'よむホーム',
    utilityLinkStudy: '学習',
    utilityLinkSupport: 'サポート',
    utilityLinkDiscord: 'Discord',
    utilityLinkGitHub: 'GitHub',
    readingShow: '読み方',
    readingHide: '読み方を隠す',
    dayEndStageLabel: '一日の終わりの教室',
    dayEndRieAlt: '教室で別れの挨拶をするりえ先生',
    dayEndLine: '今日はここまでにしましょう。またね。',
    dayEndSupport: '今日はここまでにしましょう。またね。',
    dayEndReturn: 'キャンパスに戻る',
    reviewTitle: '図書館の復習',
    reviewEmpty: 'まだ復習はありません。',
    reviewReveal: '意味を見る',
    reviewPrompt: 'この表現を覚えていますか。',
    reviewAgain: 'もう一度',
    reviewHard: '難しい',
    reviewGood: 'できた',
    reviewEasy: '簡単',
    reviewComplete: 'よむに保存しました。',
    reviewReturn: 'キャンパスに戻る',
    journalTitle: 'クラス日記',
    classBoardTitle: 'クラスボード',
    journalRie: 'りえ先生',
    journalRieLine: '「椅子が一つ空いていれば十分。始めましょう。」',
    journalAakash: 'Aakash',
    journalAakashLine: '「まっすぐ行って、右。よし。」',
    journalPeter: 'Peter',
    journalShaun: 'Shaun',
    journalBond: '絆',
    journalReplay: '最初の思い出をもう一度見る',
    journalReplayAakash: '雨の道案内をもう一度見る',
    journalReason: '日本語を学ぶ理由',
    memoryTitle: '空いていた椅子',
    memoryBody: '窓をたたく雨。プリントの山を抱えるりえ先生、傍らで冷めていくお茶。あなたのために空いた椅子が一つ。',
    memoryReturn: '思い出を閉じる',
    journalLocked: '物語で誰かに会うと、その人のページが開きます。',
    replayStreamTitle: 'NG+ リプレイ',
    replayStreamDaily: '今日',
    replayStreamWeekly: '今週',
    replayStreamCanonProgress: '正史: {completed} / {total} 章',
    replayStreamCanonBoundary: 'リプレイは練習の思い出です。正史、関係、卒業は変わりません。',
    replayStreamGraduated: '卒業は完了しました。リプレイは練習の思い出として続きます。',
    replayStreamNoPractice: '作られた場面を完了し、その言葉を身につけると、より高い言語レイヤーのリプレイが開きます。',
    replayStreamDueCallback: '期限のSRSコールバック',
    replayStreamHigherReplay: 'より高い言語レイヤーのリプレイ',
    replayStreamSliceOfLife: '任意の日常練習',
    replayStreamOpenMemory: '思い出を開く',
    replayStreamOpenLesson: 'レッスンを復習する',
    lessonOverviewBack: '戻る',
    lessonOverviewGoals: '学習目標',
    lessonOverviewSections: 'レッスン',
    lessonOverviewMaterials: '教材',
    lessonOverviewPeople: 'クラスのみなさん',
    lessonOverviewProgress: '進み具合',
    lessonOverviewStart: '始める',
    lessonOverviewResume: '続ける',
    lessonOverviewReview: '復習する',
    lessonOverviewDone: '完了',
    lessonOverviewInProgress: '途中',
    lessonOverviewNotStarted: '未開始',
    lessonOverviewNeedsReview: '要復習',
    classPathTitle: 'クラス',
    classPathWeeks: '道のり',
    classPathPeople: 'みんな',
    classPathEvents: 'イベント',
};

export function academyText(language: AcademyLanguage, key: AcademyCopyKey): string {
    return language === 'ja' ? JA[key] : EN[key];
}

export function academyCopyHasMissingJapanese(): boolean {
    return (Object.keys(EN) as AcademyCopyKey[]).some(key => !JA[key].trim() || JA[key] === '未翻訳');
}
