export const PRACTICE_SESSION_COPY = {
    en: {
        practiceTitle: 'Practice',
        practicePurpose: 'Session type',
        practiceRecognition: 'Read words',
        practiceCloze: 'Complete sentences',
        practiceWriting: 'Write words',
        practiceListening: 'Listen',
        practiceSpeaking: 'Speak',
        practiceStart: 'Start session',
        practiceResume: 'Resume',
        practiceSaved: 'Saved sessions',
        practiceCurrentSelection: 'Use current selection',
        practiceScheduleUnchanged: 'Your scheduled reviews stay unchanged.',
        practicePreparing: 'Preparing session…',
        practiceUnavailable: 'This session could not be opened.',
        practiceNoMaterial: 'No selected words are ready for this session type.',
        practiceSaveFailed: 'Progress could not be saved. Try again.',
        practiceConflict: 'This session changed in another window. Copy any unsaved answer before reopening.',
        practiceReopen: 'Reopen saved progress',
        practiceEmptyAnswer: 'Enter an answer.',
        practiceCheck: 'Check',
        practiceCorrect: 'Matches the word',
        practiceAccepted: 'Reading matches',
        practiceDifferent: 'Try again, or compare with the answer.',
        practiceRemembered: 'I remembered',
        practiceNotYet: 'Not yet',
        practiceNext: 'Next',
        practiceSkip: 'Skip',
        practicePause: 'Pause',
        practiceComplete: 'Session complete',
        practiceBack: 'Back to Study',
        practiceNew: 'New session',
        practiceWordsCount: '{count} words',
        practicePosition: '{current} of {total}',
        practiceResponse: 'Your answer',
        practiceAudio: 'Play question audio',
    },
    ja: {
        practiceTitle: '練習',
        practicePurpose: '練習方法',
        practiceRecognition: '単語を読む',
        practiceCloze: '文の空欄を埋める',
        practiceWriting: '単語を書く',
        practiceListening: '聞き取り',
        practiceSpeaking: '発話',
        practiceStart: '練習を開始',
        practiceResume: '再開',
        practiceSaved: '保存した練習',
        practiceCurrentSelection: '現在の選択を使う',
        practiceScheduleUnchanged: '復習予定には影響しません。',
        practicePreparing: '練習を準備中…',
        practiceUnavailable: 'この練習を開けませんでした。',
        practiceNoMaterial: '選択した単語では、この形式の練習を開始できません。',
        practiceSaveFailed: '進捗を保存できませんでした。もう一度お試しください。',
        practiceConflict: '別のウィンドウで進捗が変わりました。未保存の回答をコピーしてから開き直してください。',
        practiceReopen: '保存済みの進捗を開く',
        practiceEmptyAnswer: '回答を入力してください。',
        practiceCheck: '確認',
        practiceCorrect: '表記が一致',
        practiceAccepted: '読みが一致',
        practiceDifferent: 'もう一度試すか、答えを確認してください。',
        practiceRemembered: '思い出せた',
        practiceNotYet: 'まだ覚えていない',
        practiceNext: '次へ',
        practiceSkip: 'スキップ',
        practicePause: '中断',
        practiceComplete: '練習完了',
        practiceBack: '学習に戻る',
        practiceNew: '新しい練習',
        practiceWordsCount: '{count}語',
        practicePosition: '{total}問中{current}問',
        practiceResponse: '回答',
        practiceAudio: '問題の音声を再生',
    },
} as const;
