import {
    assertManagedStateMutationAllowed,
    cacheManagedValueForHostedStartup,
    clearManagedBrowserCaches,
    ensureManagedWebStorageCurrent,
    ensureManagedWebStorageCurrentSync,
    exportManagedStoredValues,
    gmPrivateStorageDelete,
    gmPrivateStorageGet,
    gmPrivateStorageSet,
    gmStorageDelete,
    gmStorageDeleteSync,
    gmStorageGet,
    gmStorageGetForResetEnumeration,
    gmStorageGetSharedSync,
    gmStorageGetSync,
    gmStorageSet,
    gmStorageSetSync,
    hasAsyncGmStorageBackend,
    importStoredValues,
    isHostedYomuOrigin,
    localFallbackStoredValue,
    managedLocalStorage,
    managedSessionStorage,
    storedValueExists,
    subscribeToStoredValueChanges,
    unregisterManagedServiceWorkers,
    withGmStorageLease,
} from './storage';
import { registerStorageRuntimeApi } from './storage-runtime-bridge';

// The aggregate @require runtime executes before the core IIFE and keeps only
// lazy storage delegates. Publish the one authoritative implementation inside
// the userscript sandbox before boot. Never route this through
// __yomuCompanions: that registry may be cloned into the page realm.
registerStorageRuntimeApi({
    managedLocalStorage,
    managedSessionStorage,
    hasAsyncGmStorageBackend,
    assertManagedStateMutationAllowed,
    ensureManagedWebStorageCurrent,
    ensureManagedWebStorageCurrentSync,
    localFallbackStoredValue,
    gmStorageGet,
    gmStorageGetForResetEnumeration,
    gmPrivateStorageGet,
    withGmStorageLease,
    gmStorageGetSync,
    gmStorageGetSharedSync,
    gmStorageSet,
    gmPrivateStorageSet,
    gmStorageSetSync,
    gmStorageDelete,
    gmPrivateStorageDelete,
    gmStorageDeleteSync,
    exportManagedStoredValues,
    importStoredValues,
    clearManagedBrowserCaches,
    unregisterManagedServiceWorkers,
    subscribeToStoredValueChanges,
    storedValueExists,
    cacheManagedValueForHostedStartup,
    isHostedYomuOrigin,
});
