const EN_SUBTITLE_SETTINGS_COPY = {
    subtitlePlayerEnabled: 'Enable video subtitle player',
    subtitleAutoDetect: 'Auto-detect page subtitles',
    subtitleOverlayVisible: 'Show subtitle overlay',
    subtitleSecondaryVisible: 'Show native subtitles',
    subtitleNativeBlurred: 'Blur native subtitles until hover',
    subtitleNativeDisplay: 'Translation',
    subtitleNativeDisplayBlurred: 'Blur until reveal (recommended)',
    subtitleNativeDisplayShown: 'Always show',
    subtitleNativeDisplayHidden: 'Hide completely',
    subtitleNativeBlurStrength: 'Blur strength',
    subtitleKaraokeMode: 'Karaoke word timing',
    subtitleTranscriptVisible: 'Open transcript panel by default',
    subtitlePausePanel: 'Open side panel when paused',
    subtitleShadowAutoPause: 'Auto-pause after each shadow line',
    subtitleTranscriptPlacement: 'Transcript panel position',
    subtitleTranscriptAutoScroll: 'Scroll transcript with playback',
    subtitleTranscriptAutoScrollResumeSeconds: 'Resume auto-scroll delay (s)',
    subtitleAutoCopyLine: 'Auto-copy subtitle lines',
    subtitleMiningPause: 'Pause video on subtitle click',
    subtitleHoverPause: 'Pause video on subtitle hover',
    subtitleControlsMode: 'Subtitle controls',
    subtitleFontSize: 'Subtitle font size (px)',
    subtitleBottomOffset: 'Subtitle bottom offset (%)',
    subtitleTextColor: 'Subtitle color',
    subtitleOutlineColor: 'Subtitle outline',
    subtitleBackgroundColor: 'Subtitle background',
    subtitleBackgroundOpacity: 'Subtitle background opacity',
    subtitleFontFamily: 'Subtitle font family',
    subtitleFontWeight: 'Subtitle font weight',
    subtitleSeekPadding: 'Subtitle seek padding (s)',
    subtitlePreview: 'Live subtitle preview',
} as const;

const JA_SUBTITLE_SETTINGS_COPY = {
    subtitlePlayerEnabled: '動画字幕プレイヤーを有効にする',
    subtitleAutoDetect: 'ページの字幕を自動検出',
    subtitleOverlayVisible: '字幕オーバーレイを表示',
    subtitleSecondaryVisible: '利用可能ならネイティブ字幕を表示',
    subtitleNativeBlurred: 'ホバーするまでネイティブ字幕をぼかす',
    subtitleNativeDisplay: '母語訳',
    subtitleNativeDisplayBlurred: '表示するまでぼかす（おすすめ）',
    subtitleNativeDisplayShown: '常に表示',
    subtitleNativeDisplayHidden: '完全に隠す',
    subtitleNativeBlurStrength: 'ぼかしの強さ',
    subtitleKaraokeMode: 'カラオケ風の単語タイミング',
    subtitleTranscriptVisible: '文字起こしパネルを標準で開く',
    subtitlePausePanel: '一時停止時にサイドパネルを開く',
    subtitleShadowAutoPause: 'シャドー中は各行の後で一時停止',
    subtitleTranscriptPlacement: '文字起こしパネル位置',
    subtitleTranscriptAutoScroll: '再生に合わせて文字起こしをスクロール',
    subtitleTranscriptAutoScrollResumeSeconds: '手動スクロール後の再開 (秒)',
    subtitleAutoCopyLine: '各字幕行を再生時に自動コピー',
    subtitleMiningPause: '字幕クリック時に動画を一時停止',
    subtitleHoverPause: '字幕ホバー時に動画を一時停止',
    subtitleControlsMode: '字幕コントロール',
    subtitleFontSize: '字幕フォントサイズ (px)',
    subtitleBottomOffset: '字幕下端オフセット (%)',
    subtitleTextColor: '字幕の色',
    subtitleOutlineColor: '字幕の縁取り',
    subtitleBackgroundColor: '字幕背景',
    subtitleBackgroundOpacity: '字幕背景の不透明度',
    subtitleFontFamily: '字幕フォントファミリー',
    subtitleFontWeight: '字幕フォントの太さ',
    subtitleSeekPadding: '字幕シーク余白 (s)',
    subtitlePreview: '字幕ライブプレビュー',
} as const satisfies Record<keyof typeof EN_SUBTITLE_SETTINGS_COPY, string>;

export const SUBTITLE_SETTINGS_COPY = {
    en: EN_SUBTITLE_SETTINGS_COPY,
    ja: JA_SUBTITLE_SETTINGS_COPY,
} as const;
