const POS_LABELS: Record<string, string> = {
    abbr: 'abbreviation',
    adj: 'adjective',
    'adj-f': 'pre-noun adjective',
    'adj-i': 'i-adjective',
    'adj-ix': 'yoi/ii adjective',
    'adj-na': 'na-adjective',
    'adj-no': 'no-adjective',
    'adj-pn': 'pre-noun adjectival',
    'adj-t': 'taru adjective',
    adv: 'adverb',
    'adv-to': 'adverb taking to',
    arch: 'archaic',
    ateji: 'phonetic kanji spelling',
    aux: 'auxiliary',
    'aux-adj': 'auxiliary adjective',
    "aux-v": 'auxiliary verb',
    col: 'colloquial',
    conj: 'conjunction',
    cop: 'copula',
    ctr: 'counter',
    dated: 'dated term',
    derog: 'derogatory',
    exp: 'expression',
    fam: 'familiar language',
    fem: 'female language',
    form: 'formal language',
    gikun: 'special kanji reading',
    hon: 'honorific language',
    hum: 'humble language',
    id: 'idiomatic expression',
    ik: 'irregular kana form',
    io: 'irregular okurigana',
    int: 'interjection',
    joc: 'jocular language',
    male: 'male language',
    n: 'noun',
    'n-adv': 'adverbial noun',
    'n-pr': 'proper noun',
    'n-pref': 'noun used as a prefix',
    'n-suf': 'noun used as a suffix',
    'n-t': 'temporal noun',
    'net-sl': 'internet slang',
    num: 'number',
    obs: 'obsolete term',
    obsc: 'obscure term',
    ok: 'outdated kana form',
    'on-mim': 'onomatopoeic or mimetic word',
    pn: 'pronoun',
    poet: 'poetic term',
    pol: 'polite language',
    pref: 'prefix',
    prt: 'particle',
    proverb: 'proverb',
    rare: 'rare term',
    rk: 'rare kana form',
    sens: 'sensitive term',
    sl: 'slang',
    suf: 'suffix',
    unc: 'unclassified',
    uk: 'usually written using kana alone',
    vi: 'intransitive verb',
    vt: 'transitive verb',
    v1: 'ichidan verb',
    v5: 'godan verb',
    v5aru: 'aru ending',
    v5b: 'bu ending',
    v5g: 'gu ending',
    v5k: 'ku ending',
    v5m: 'mu ending',
    v5n: 'nu ending',
    v5r: 'ru ending',
    v5s: 'su ending',
    v5t: 'tsu ending',
    v5u: 'u ending',
    vk: 'kuru verb',
    vs: 'suru verb',
    'vs-c': 'su verb',
    'vs-i': 'suru verb',
    'vs-s': 'suru verb (special class)',
    vulgar: 'vulgar expression',
    vz: 'zuru verb',
};

export function formatPartOfSpeech(tags: string[] = []): string {
    const labels = tags.map(tag => POS_LABELS[tag.toLowerCase()] ?? tag).filter(Boolean);
    return [...new Set(labels)].join(', ');
}

export function formatPartOfSpeechDetails(tags: string[] = []): string {
    return tags.length ? tags.join(', ').toUpperCase() : '';
}
