import { normalizeSubtitleCues, parseSubtitleText, type SubtitleCue } from './subtitle-cues';

export interface YouTubeSubtitleTrack {
    label: string;
    kind?: string;
    language?: string;
    autoGenerated?: boolean;
    url?: string;
    youtubeTrack?: unknown;
    cues?: SubtitleCue[];
}

export interface YouTubeCaptionTrackCandidate {
    label: string;
    language?: string;
    autoGenerated?: boolean;
    url: string;
    raw: unknown;
}

export interface YouTubeTrackLoadOptions<T extends YouTubeSubtitleTrack> {
    requestText: (url: string) => Promise<string>;
    onRequestError?: (track: T, url: string, error: unknown) => void;
}

export async function loadYouTubeTrackCues<T extends YouTubeSubtitleTrack>(
    track: T,
    options: YouTubeTrackLoadOptions<T>,
): Promise<SubtitleCue[]> {
    if (!track.url) return [];
    const preferred = findPreferredYouTubeCaptionCandidate(track);
    if (preferred && shouldPreferYouTubeTrackUrl(preferred.url, track.url)) {
        track.url = preferred.url;
        track.youtubeTrack = preferred.raw;
    }
    for (const url of youtubeSubtitleRequestUrls(track.url)) {
        try {
            const cues = normalizeSubtitleCues(parseSubtitleText(await options.requestText(url), {
                smoothYouTubeFragments: true,
                youtubeAutoGenerated: isAutoGeneratedSubtitleTrack(track),
            }));
            if (cues.length) return cues;
        } catch (error) {
            options.onRequestError?.(track, url, error);
        }
    }
    return [];
}

export async function loadFirstUsableYouTubeSibling<T extends YouTubeSubtitleTrack>(
    track: T,
    tracks: T[],
    options: YouTubeTrackLoadOptions<T>,
): Promise<{ track: T; cues: SubtitleCue[] } | null> {
    const siblings = tracks.filter(candidate => candidate.kind === 'youtube'
        && candidate !== track
        && candidate.language === track.language
        && candidate.url);
    for (const sibling of siblings) {
        const cues = sibling.cues?.length ? sibling.cues : await loadYouTubeTrackCues(sibling, options);
        if (!cues.length) continue;
        sibling.cues = cues;
        return { track: sibling, cues };
    }
    return null;
}

export function getYouTubeCaptionTracks(): YouTubeCaptionTrackCandidate[] {
    const playerTracks = getYouTubePlayerCaptionTracks();
    const response = getYouTubePlayerResponse();
    const rawTracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    return uniqueYouTubeCaptionTracks([
        ...playerTracks,
        ...(Array.isArray(rawTracks) ? rawTracks : []),
    ]);
}

export function disableYouTubeNativeCaptions(): void {
    if (!isYouTubePage()) return;
    const player = document.querySelector('#movie_player') as {
        unloadModule?: (name: string) => void;
        setOption?: (module: string, option: string, value: unknown) => void;
    } | null;
    try {
        player?.setOption?.('captions', 'track', {});
        player?.unloadModule?.('captions');
    } catch {
        // YouTube's player API is private and best-effort.
    }
}

export function activateYouTubeCaptionTrack(track: YouTubeSubtitleTrack): void {
    if (!isYouTubePage()) return;
    const player = document.querySelector('#movie_player') as {
        loadModule?: (name: string) => void;
        setOption?: (module: string, option: string, value: unknown) => void;
        getOption?: (module: string, option: string) => unknown;
        getAudioTrack?: () => { captionTracks?: unknown[] };
    } | null;
    if (!player?.setOption) return;
    try {
        player.loadModule?.('captions');
        const candidate = findMatchingYouTubePlayerTrack(track, player) ?? track.youtubeTrack;
        if (candidate) player.setOption('captions', 'track', candidate);
        player.setOption('captions', 'reload', true);
    } catch {
        // YouTube's player API is private and best-effort.
    }
}

export function getYouTubeVideoId(): string {
    const url = new URL(location.href);
    return url.searchParams.get('v') ?? url.pathname.match(/\/shorts\/([^/?]+)/)?.[1] ?? '';
}

export function isYouTubePage(): boolean {
    return /(^|\.)youtube\.com$/i.test(location.hostname);
}

export function shouldPreferYouTubeTrackUrl(next: string | undefined, current: string | undefined): boolean {
    return youtubeTrackUrlScore(next) > youtubeTrackUrlScore(current);
}

export function isAutoGeneratedSubtitleTrack(track: YouTubeSubtitleTrack): boolean {
    return Boolean(track.autoGenerated)
        || /asr|auto(?:matic)?|auto-generated|自動生成|自動字幕/i.test(`${track.label} ${track.language ?? ''}`);
}

export function youtubeCaptionTrackIdentity(track: { label: string; language?: string }): string {
    return `${track.language ?? ''}:${track.label
        .replace(/\s+·\s+auto-generated$/iu, '')
        .replace(/\([^)]*\)\s*$/u, '')
        .replace(/\s+/g, ' ')
        .trim()
        .toLowerCase()}`;
}

function getYouTubePlayerCaptionTracks(): unknown[] {
    const player = document.querySelector('#movie_player') as {
        getVideoData?: () => { video_id?: string };
        getAudioTrack?: () => { captionTracks?: unknown[] };
    } | null;
    const videoId = getYouTubeVideoId();
    const playerVideoId = player?.getVideoData?.()?.video_id;
    const tracks = player?.getAudioTrack?.()?.captionTracks;
    return (!playerVideoId || !videoId || playerVideoId === videoId) && Array.isArray(tracks) ? tracks : [];
}

function uniqueYouTubeCaptionTracks(rawTracks: unknown[]): YouTubeCaptionTrackCandidate[] {
    const tracks: YouTubeCaptionTrackCandidate[] = [];
    const seen = new Set<string>();
    for (const track of rawTracks) {
        const parsed = parseYouTubeCaptionTrack(track);
        if (!parsed) continue;
        const key = youtubeCaptionTrackIdentity(parsed);
        if (seen.has(key)) continue;
        seen.add(key);
        tracks.push(parsed);
    }
    return tracks;
}

function parseYouTubeCaptionTrack(track: unknown): YouTubeCaptionTrackCandidate | null {
    const record = track as {
        url?: string;
        baseUrl?: string;
        languageCode?: string;
        displayName?: string;
        languageName?: string;
        kind?: string;
        vssId?: string;
        name?: { simpleText?: string; runs?: Array<{ text?: string }> };
    };
    const url = normalizedYouTubeCaptionUrl(record);
    if (!url) return null;
    const language = record.languageCode;
    const label = youtubeCaptionTrackLabel(record, language);
    const autoGenerated = isAutoGeneratedYouTubeCaptionTrack(record, label);
    const autoSuffix = youtubeCaptionAutoSuffix(autoGenerated, label);
    return { label: `${label}${language ? ` (${language})` : ''}${autoSuffix}`, language, autoGenerated, url: url.toString(), raw: track };
}

function normalizedYouTubeCaptionUrl(record: { url?: string; baseUrl?: string }): URL | null {
    const rawUrl = typeof record.url === 'string' ? record.url : typeof record.baseUrl === 'string' ? record.baseUrl : '';
    if (!rawUrl) return null;
    const url = new URL(rawUrl, location.href);
    url.searchParams.set('fmt', 'srv3');
    const clientName = readYouTubeClientName();
    if (clientName && !url.searchParams.has('c')) url.searchParams.set('c', clientName);
    return url;
}

function youtubeCaptionTrackLabel(record: {
    displayName?: string;
    languageName?: string;
    name?: { simpleText?: string; runs?: Array<{ text?: string }> };
}, language?: string): string {
    return record.name?.simpleText
        ?? record.name?.runs?.map(run => run.text ?? '').join('')
        ?? record.displayName
        ?? record.languageName
        ?? language
        ?? 'YouTube subtitles';
}

function youtubeCaptionAutoSuffix(autoGenerated: boolean, label: string): string {
    return autoGenerated && !/asr|auto(?:matic)?|auto-generated|自動生成|自動字幕/i.test(label)
        ? ' · auto-generated'
        : '';
}

function isAutoGeneratedYouTubeCaptionTrack(track: { kind?: string; vssId?: string; languageCode?: string }, label = ''): boolean {
    return /asr/i.test(track.kind ?? '')
        || /^a\./i.test(track.vssId ?? '')
        || /asr|auto(?:matic)?|auto-generated|自動生成|自動字幕/i.test(`${label} ${track.languageCode ?? ''}`);
}

function findMatchingYouTubePlayerTrack(track: YouTubeSubtitleTrack, player: {
    getOption?: (module: string, option: string) => unknown;
    getAudioTrack?: () => { captionTracks?: unknown[] };
}): unknown {
    const rawTracks = [
        ...extractYouTubeTrackArray(player.getAudioTrack?.()?.captionTracks),
        ...extractYouTubeTrackArray(player.getOption?.('captions', 'tracklist')),
    ];
    const targetIdentity = youtubeCaptionTrackIdentity(track);
    const exact = rawTracks.find(raw => {
        const parsed = parseYouTubeCaptionTrack(raw);
        return parsed && youtubeCaptionTrackIdentity(parsed) === targetIdentity;
    });
    if (exact) return exact;
    return rawTracks.find(raw => {
        const parsed = parseYouTubeCaptionTrack(raw);
        return parsed?.language && track.language && parsed.language.toLowerCase() === track.language.toLowerCase();
    }) ?? null;
}

function findPreferredYouTubeCaptionCandidate(track: YouTubeSubtitleTrack): YouTubeCaptionTrackCandidate | null {
    if (track.kind !== 'youtube') return null;
    const candidates = uniqueYouTubeCaptionTracks([
        ...getYouTubePlayerCaptionTracks(),
        ...(getYouTubePlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []),
    ]);
    const targetIdentity = youtubeCaptionTrackIdentity(track);
    return candidates
        .filter(candidate => youtubeCaptionTrackIdentity(candidate) === targetIdentity
            || Boolean(candidate.language && track.language && candidate.language.toLowerCase() === track.language.toLowerCase()))
        .sort((a, b) => youtubeTrackUrlScore(b.url) - youtubeTrackUrlScore(a.url))[0] ?? null;
}

function extractYouTubeTrackArray(value: unknown): unknown[] {
    if (Array.isArray(value)) return value;
    const record = value as { captionTracks?: unknown[] } | null;
    return Array.isArray(record?.captionTracks) ? record.captionTracks : [];
}

type YouTubePlayerResponse = {
    videoDetails?: { videoId?: string };
    captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: unknown[] } };
};

function getYouTubePlayerResponse(): YouTubePlayerResponse | null {
    const videoId = getYouTubeVideoId();
    const fromWindow = (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse;
    if (isMatchingYouTubePlayerResponse(fromWindow, videoId)) return fromWindow as YouTubePlayerResponse;

    const fromConfig = readYouTubePlayerResponseFromConfig(videoId);
    if (fromConfig) return fromConfig;

    return readYouTubePlayerResponseFromScripts(videoId);
}

function readYouTubePlayerResponseFromScripts(videoId: string): YouTubePlayerResponse | null {
    for (const script of Array.from(document.scripts)) {
        const parsed = readYouTubePlayerResponseFromScript(script.textContent ?? '', videoId);
        if (parsed) return parsed;
    }
    return null;
}

function readYouTubePlayerResponseFromScript(text: string, videoId: string): YouTubePlayerResponse | null {
    return readYouTubeInitialPlayerResponse(text, videoId)
        ?? readEscapedYouTubePlayerResponse(text, videoId);
}

function readYouTubeInitialPlayerResponse(text: string, videoId: string): YouTubePlayerResponse | null {
    for (const marker of ['ytInitialPlayerResponse = ', 'ytInitialPlayerResponse=', 'var ytInitialPlayerResponse = ']) {
        const parsed = parseYouTubePlayerResponseMarker(text, marker, videoId);
        if (parsed) return parsed;
    }
    return null;
}

function parseYouTubePlayerResponseMarker(text: string, marker: string, videoId: string): YouTubePlayerResponse | null {
    const start = text.indexOf(marker);
    if (start < 0) return null;
    const raw = extractJsonObject(text, start + marker.length);
    return raw ? parseMatchingYouTubePlayerResponse(raw, videoId) : null;
}

function readEscapedYouTubePlayerResponse(text: string, videoId: string): YouTubePlayerResponse | null {
    const escaped = text.match(/"playerResponse"\s*:\s*"((?:\\.|[^"\\])+)"/);
    if (!escaped?.[1]) return null;
    try {
        return parseMatchingYouTubePlayerResponse(JSON.parse(`"${escaped[1]}"`), videoId);
    } catch {
        return null;
    }
}

function parseMatchingYouTubePlayerResponse(raw: string, videoId: string): YouTubePlayerResponse | null {
    try {
        const parsed = JSON.parse(raw) as unknown;
        return isMatchingYouTubePlayerResponse(parsed, videoId) ? parsed as YouTubePlayerResponse : null;
    } catch {
        return null;
    }
}

function readYouTubePlayerResponseFromConfig(videoId: string): YouTubePlayerResponse | null {
    const ytcfg = (window as Window & { ytcfg?: { data_?: Record<string, unknown>; get?: (key: string) => unknown } }).ytcfg;
    const candidates = [
        ytcfg?.get?.('PLAYER_RESPONSE'),
        ytcfg?.get?.('PLAYER_VARS'),
        ytcfg?.data_?.PLAYER_RESPONSE,
        ytcfg?.data_?.PLAYER_VARS,
    ];
    for (const candidate of candidates) {
        const response = readYouTubePlayerResponseCandidate(candidate);
        if (isMatchingYouTubePlayerResponse(response, videoId)) return response as YouTubePlayerResponse;
    }
    return null;
}

function readYouTubePlayerResponseCandidate(candidate: unknown): unknown {
    if (!candidate) return null;
    if (typeof candidate === 'string') {
        try {
            return JSON.parse(candidate);
        } catch {
            return null;
        }
    }
    if (typeof candidate === 'object') {
        const record = candidate as { player_response?: unknown; raw_player_response?: unknown };
        return readYouTubePlayerResponseCandidate(record.player_response ?? record.raw_player_response) ?? candidate;
    }
    return null;
}

function isMatchingYouTubePlayerResponse(value: unknown, videoId: string): boolean {
    if (!value || typeof value !== 'object') return false;
    const response = value as YouTubePlayerResponse;
    const responseVideoId = response.videoDetails?.videoId;
    return Boolean(response.captions?.playerCaptionsTracklistRenderer?.captionTracks)
        && (!videoId || !responseVideoId || responseVideoId === videoId);
}

function extractJsonObject(text: string, start: number): string | null {
    const objectStart = text.indexOf('{', start);
    if (objectStart < 0) return null;

    const state = createJsonObjectScanState();
    for (let index = objectStart; index < text.length; index++) {
        if (scanJsonObjectCharacter(state, text[index])) return text.slice(objectStart, index + 1);
    }
    return null;
}

interface JsonObjectScanState {
    depth: number;
    inString: boolean;
    escaped: boolean;
}

function createJsonObjectScanState(): JsonObjectScanState {
    return { depth: 0, inString: false, escaped: false };
}

function scanJsonObjectCharacter(state: JsonObjectScanState, char: string): boolean {
    if (state.inString) {
        scanJsonStringCharacter(state, char);
        return false;
    }
    if (char === '"') {
        state.inString = true;
        return false;
    }
    if (char === '{') state.depth += 1;
    if (char !== '}') return false;
    state.depth -= 1;
    return state.depth === 0;
}

function scanJsonStringCharacter(state: JsonObjectScanState, char: string): void {
    if (state.escaped) {
        state.escaped = false;
        return;
    }
    if (char === '\\') state.escaped = true;
    if (char === '"') state.inString = false;
}

function youtubeSubtitleRequestUrls(url: string): string[] {
    return uniqueStrings([
        withYouTubeSubtitleFormat(url, 'srv3'),
        withYouTubeSubtitleFormat(url, 'json3'),
        withYouTubeSubtitleFormat(url, 'vtt'),
        url,
    ]);
}

function withYouTubeSubtitleFormat(url: string, format: 'srv3' | 'vtt' | 'json3'): string {
    const parsed = new URL(url);
    parsed.searchParams.set('fmt', format);
    const clientName = readYouTubeClientName();
    if (clientName && !parsed.searchParams.has('c')) parsed.searchParams.set('c', clientName);
    return parsed.href;
}

function readYouTubeClientName(): string {
    const ytcfg = (window as Window & { ytcfg?: { get?: (key: string) => unknown } }).ytcfg;
    const value = ytcfg?.get?.('INNERTUBE_CLIENT_NAME');
    return typeof value === 'string' && value ? value : '';
}

function youtubeTrackUrlScore(value: string | undefined): number {
    if (!value) return 0;
    try {
        const url = new URL(value, location.href);
        return [
            url.searchParams.has('pot') ? 8 : 0,
            url.searchParams.has('potc') ? 4 : 0,
            url.searchParams.has('signature') ? 2 : 0,
            url.searchParams.has('kind') ? 1 : 0,
        ].reduce((sum, item) => sum + item, 0);
    } catch {
        return 0;
    }
}

function uniqueStrings(values: string[]): string[] {
    return [...new Set(values)];
}
