import { escapeHtml, parseXmlDocument } from './dom';

export interface SubtitleWordTiming {
    text: string;
    start: number;
    end: number;
}

export interface SubtitleCue {
    start: number;
    end: number;
    text: string;
    originalText?: string;
    words?: SubtitleWordTiming[];
    wordTimingsExact?: boolean;
    transcriptEligible?: boolean;
}

export interface ParseSubtitleTextOptions {
    smoothYouTubeFragments?: boolean;
    youtubeAutoGenerated?: boolean;
}

export function normalizeSubtitleCues(cues: SubtitleCue[], options: { transcriptEligible?: boolean } = {}): SubtitleCue[] {
    const normalized: SubtitleCue[] = [];
    cues.forEach(cue => {
        const text = normalizeCaptionText(cue.text);
        if (!text || !Number.isFinite(cue.start) || !Number.isFinite(cue.end)) return;
        const words = exactSubtitleWords(cue, cue.start, Math.max(cue.end, cue.start + 0.12));
        const base = {
            ...cue,
            text,
            start: cue.start,
            end: Math.max(cue.end, cue.start + 0.12),
            originalText: cue.originalText ?? text,
            words,
            wordTimingsExact: Boolean(words?.length),
            transcriptEligible: options.transcriptEligible ?? cue.transcriptEligible ?? true,
        };
        const sentenceParts = splitCueDisplayText(text);
        if (sentenceParts.length <= 1) {
            normalized.push({ ...base, transcriptEligible: base.transcriptEligible });
            return;
        }

        const timedParts = distributeCueParts(base, sentenceParts);
        for (const part of timedParts) {
            const partWords = sliceCueWords(base, part.start, part.end);
            normalized.push({
                start: part.start,
                end: part.end,
                text: part.text,
                originalText: base.originalText,
                words: partWords,
                wordTimingsExact: Boolean(partWords?.length),
                transcriptEligible: base.transcriptEligible,
            });
        }
        if (!timedParts.length) normalized.push({ ...base, transcriptEligible: base.transcriptEligible });
    });
    return normalized.sort((a, b) => a.start - b.start);
}

function splitCueDisplayText(text: string): string[] {
    const normalized = normalizeCaptionText(text);
    if (!normalized) return [];
    const sentenceParts = splitSentencesByPunctuation(normalized);
    if (sentenceParts.length > 1) return sentenceParts;
    if (displayTextWeight(normalized) <= 38) return [normalized];
    return splitOverlongCue(normalized);
}

function splitSentencesByPunctuation(text: string): string[] {
    const parts: string[] = [];
    let start = 0;
    let offset = 0;
    for (const char of Array.from(text)) {
        offset += char.length;
        const end = subtitleSentenceBoundaryEnd(text, char, offset);
        if (end === null) continue;
        offset = end;
        pushSubtitleSentencePart(parts, text, start, offset);
        start = offset;
    }
    pushSubtitleSentencePart(parts, text, start, text.length);
    return parts.length ? parts : [text];
}

function subtitleSentenceBoundaryEnd(text: string, char: string, offset: number): number | null {
    if (!isSubtitleSentencePunctuation(char)) return null;
    return consumeClosingSubtitlePunctuation(text, offset);
}

function isSubtitleSentencePunctuation(char: string): boolean {
    return /[。！？!?]/u.test(char);
}

function consumeClosingSubtitlePunctuation(text: string, offset: number): number {
    let end = offset;
    while (end < text.length && isSubtitleSentenceCloser(text[end])) end++;
    return end;
}

function isSubtitleSentenceCloser(char: string): boolean {
    return /["'」』）\]]/u.test(char);
}

function pushSubtitleSentencePart(parts: string[], text: string, start: number, end: number): void {
    const part = text.slice(start, end).trim();
    if (part) parts.push(part);
}

function splitOverlongCue(text: string): string[] {
    const parts: string[] = [];
    const tokens = overlongCueTokens(text);
    let current = '';
    for (const token of tokens) {
        if (shouldFlushOverlongCuePart(current, token)) {
            parts.push(current.trim());
            current = token.trimStart();
        } else {
            current += token;
        }
    }
    if (current.trim()) parts.push(current.trim());
    return splitCuePartsOrOriginal(parts, text);
}

function overlongCueTokens(text: string): string[] {
    return text.includes(' ') ? text.split(/(\s+)/u).filter(Boolean) : Array.from(text);
}

function shouldFlushOverlongCuePart(current: string, token: string): boolean {
    return displayTextWeight(current + token) > 32 && Boolean(current.trim());
}

function splitCuePartsOrOriginal(parts: string[], text: string): string[] {
    return parts.length > 1 ? parts : [text];
}

function distributeCueParts(cue: SubtitleCue, parts: string[]): Array<{ text: string; start: number; end: number }> {
    const duration = Math.max(0.12, cue.end - cue.start);
    const weights = parts.map(part => Math.max(1, displayTextWeight(part)));
    const totalWeight = weights.reduce((sum, weight) => sum + weight, 0) || parts.length;
    let cursor = cue.start;
    return parts.map((part, index) => {
        const partDuration = index === parts.length - 1
            ? cue.end - cursor
            : duration * (weights[index] / totalWeight);
        const start = cursor;
        const end = index === parts.length - 1 ? cue.end : Math.min(cue.end, cursor + Math.max(0.12, partDuration));
        cursor = end;
        return { text: part, start, end: Math.max(end, start + 0.12) };
    });
}

function exactSubtitleWords(cue: SubtitleCue, start: number, end: number): SubtitleWordTiming[] | undefined {
    if (!cue.wordTimingsExact || !cue.words?.length) return undefined;
    const words = cue.words
        .filter(word => word.text.trim() && Number.isFinite(word.start) && Number.isFinite(word.end) && word.end > start && word.start < end)
        .map(word => ({ ...word, start: clampNumber(word.start, start, end), end: clampNumber(word.end, start, end) }))
        .filter(word => word.end > word.start);
    return words.length ? words : undefined;
}

function sliceCueWords(cue: SubtitleCue, start: number, end: number): SubtitleWordTiming[] | undefined {
    return exactSubtitleWords(cue, start, end);
}

export function renderKaraokeTextParts(text: string, progress: number): string {
    const chars = Array.from(text);
    const split = clampNumber(Math.round(progress), 0, chars.length);
    const past = chars.slice(0, split).join('');
    const current = chars.slice(split, split + 1).join('');
    const upcoming = chars.slice(split + 1).join('');
    return [
        past ? `<span class="jpdb-subtitle-karaoke-word jpdb-subtitle-word-spoken">${escapeHtml(past)}</span>` : '',
        current ? `<span class="jpdb-subtitle-karaoke-word jpdb-subtitle-word-current">${escapeHtml(current)}</span>` : '',
        upcoming ? `<span class="jpdb-subtitle-karaoke-word jpdb-subtitle-word-pending">${escapeHtml(upcoming)}</span>` : '',
    ].join('');
}

export function karaokeCharacterProgress(cue: SubtitleCue, words: SubtitleWordTiming[], time: number): number {
    const total = compactTextLength(cue.text);
    const edgeProgress = karaokeEdgeProgress(cue, time, total);
    if (edgeProgress !== null) return edgeProgress;
    return karaokeTimedWordProgress(sortedSubtitleWords(words), total, time);
}

function karaokeEdgeProgress(cue: SubtitleCue, time: number, total: number): number | null {
    if (!total) return 0;
    if (time <= cue.start) return 0;
    if (time >= cue.end) return total;
    return null;
}

function sortedSubtitleWords(words: SubtitleWordTiming[]): SubtitleWordTiming[] {
    return [...words].filter(hasUsableSubtitleWordTiming).sort((a, b) => a.start - b.start);
}

function hasUsableSubtitleWordTiming(word: SubtitleWordTiming): boolean {
    return Boolean(word.text.trim() && Number.isFinite(word.start) && Number.isFinite(word.end));
}

function karaokeTimedWordProgress(words: SubtitleWordTiming[], total: number, time: number): number {
    let cursor = 0;
    for (const word of words) {
        const length = compactTextLength(word.text);
        if (!length) continue;
        if (time >= word.end) { cursor += length; continue; }
        if (time <= word.start) return Math.min(total, cursor);
        return karaokeProgressInsideWord(total, cursor, length, word, time);
    }
    return Math.min(total, cursor);
}

function karaokeProgressInsideWord(total: number, cursor: number, length: number, word: SubtitleWordTiming, time: number): number {
    const ratio = clampNumber((time - word.start) / Math.max(0.04, word.end - word.start), 0, 1);
    return Math.min(total, cursor + Math.max(1, Math.floor(length * ratio)));
}

export function compactTextLength(text: string): number {
    return Array.from(text.replace(/\s+/gu, '')).length;
}

function displayTextWeight(text: string): number {
    return Array.from(text.replace(/\s+/gu, '')).length;
}

function clampNumber(value: number, min: number, max: number): number {
    return Math.min(Math.max(value, min), Math.max(min, max));
}

function parseVttCuePayload(raw: string, cueStart: number, cueEnd: number): { text: string; words?: SubtitleWordTiming[]; wordTimingsExact?: boolean } {
    const timestampPattern = /<((?:(?:\d+:)?\d{2}:)?\d{2}[,.]\d{3})>/g;
    const markers = vttTimestampMarkers(raw, timestampPattern);
    const text = vttCueTextWithoutMarkers(raw, timestampPattern);
    if (!markers.length) return { text };
    return vttCuePayloadWithMarkers(raw, timestampPattern, markers, text, cueStart, cueEnd);
}

function vttCuePayloadWithMarkers(
    raw: string,
    timestampPattern: RegExp,
    markers: Array<{ time: number; index: number; endIndex: number }>,
    text: string,
    cueStart: number,
    cueEnd: number,
): { text: string; words?: SubtitleWordTiming[]; wordTimingsExact?: boolean } {
    const words: SubtitleWordTiming[] = [];
    for (let index = 0; index < markers.length; index++) {
        const markerWord = vttMarkerWord(raw, timestampPattern, markers, index);
        if (!markerWord) continue;
        if (/\s/u.test(markerWord.text)) return { text };
        words.push(vttWordTiming(markerWord, cueStart, cueEnd));
    }
    return { text, words: words.length ? words : undefined, wordTimingsExact: Boolean(words.length) };
}

function vttTimestampMarkers(raw: string, timestampPattern: RegExp): Array<{ time: number; index: number; endIndex: number }> {
    const markers: Array<{ time: number; index: number; endIndex: number }> = [];
    raw.replace(timestampPattern, (match, rawTime: string, index: number) => {
        appendVttTimestampMarker(markers, match, rawTime, index);
        return match;
    });
    return markers;
}

function appendVttTimestampMarker(markers: Array<{ time: number; index: number; endIndex: number }>, match: string, rawTime: string, index: number): void {
    const time = parseSubtitleTime(rawTime.includes(':') ? rawTime : `00:${rawTime}`);
    if (Number.isFinite(time)) markers.push({ time, index, endIndex: index + match.length });
}

function vttCueTextWithoutMarkers(raw: string, timestampPattern: RegExp): string {
    return raw.replace(timestampPattern, '').replace(/<[^>]+>/g, '').trim();
}

function vttMarkerWord(raw: string, timestampPattern: RegExp, markers: Array<{ time: number; index: number; endIndex: number }>, index: number): { text: string; start: number; end: number } | null {
    const marker = markers[index];
    const next = markers[index + 1];
    const segmentRaw = raw.slice(marker.endIndex, next?.index ?? raw.length).replace(timestampPattern, '').replace(/<[^>]+>/g, '');
    const segmentText = segmentRaw.trim();
    return segmentText ? { text: segmentText, start: marker.time, end: next?.time ?? Number.POSITIVE_INFINITY } : null;
}

function vttWordTiming(markerWord: { text: string; start: number; end: number }, cueStart: number, cueEnd: number): SubtitleWordTiming {
    const start = clampNumber(markerWord.start, cueStart, cueEnd);
    const end = clampNumber(markerWord.end, cueStart, cueEnd);
    return { text: markerWord.text, start, end: Math.max(start + 0.04, end) };
}

export function parseSubtitleText(text: string, options: ParseSubtitleTextOptions = {}): SubtitleCue[] {
    const normalizedText = text.replace(/^\uFEFF/, '');
    return parseKnownSubtitleText(normalizedText, options)
        ?? parseVttSubtitleText(normalizedText, options);
}

function parseKnownSubtitleText(text: string, options: ParseSubtitleTextOptions): SubtitleCue[] | undefined {
    const youtubeJson = parseYouTubeJson3SubtitleText(text, options);
    if (youtubeJson.length) return youtubeJson;

    const youtubeXml = parseYouTubeXmlSubtitleText(text, options);
    if (youtubeXml.length) return youtubeXml;

    return looksLikeAssSubtitleText(text) ? parseAssSubtitleText(text) : undefined;
}

function looksLikeAssSubtitleText(text: string): boolean {
    return /^\s*\[Script Info\]/im.test(text) || /^\s*Dialogue:/im.test(text);
}

function parseVttSubtitleText(text: string, options: ParseSubtitleTextOptions): SubtitleCue[] {
    const cues = text
        .replace(/\r/g, '')
        .replace(/^WEBVTT.*?\n\n/s, '')
        .split(/\n{2,}/)
        .map(block => block.trim())
        .filter(Boolean)
        .map(readVttCueBlock)
        .filter((cue): cue is SubtitleCue => Boolean(cue));

    const sorted = cues.sort((a, b) => a.start - b.start);
    return options.smoothYouTubeFragments ? smoothFragmentedYouTubeCues(sorted) : sorted;
}

function readVttCueBlock(block: string): SubtitleCue | null {
    const lines = block.split('\n').filter(Boolean);
    const timeIndex = lines.findIndex(line => line.includes('-->'));
    if (timeIndex < 0) return null;

    const [startRaw, endRaw] = lines[timeIndex].split('-->').map(part => part.trim().split(/\s+/)[0]);
    const start = parseSubtitleTime(startRaw);
    const end = parseSubtitleTime(endRaw);
    const payload = parseVttCuePayload(lines.slice(timeIndex + 1).join('\n'), start, end);
    return Number.isFinite(start) && Number.isFinite(end) && payload.text
        ? { start, end, text: payload.text, words: payload.words, wordTimingsExact: payload.wordTimingsExact }
        : null;
}

function parseYouTubeJson3SubtitleText(text: string, options: ParseSubtitleTextOptions = {}): SubtitleCue[] {
    if (!/^\s*\{/.test(text)) return [];
    try {
        const parsed = JSON.parse(text) as {
            events?: Array<{ tStartMs?: number; dDurationMs?: number; segs?: Array<{ utf8?: string; tOffsetMs?: number }> }>;
        };
        const cues = (parsed.events ?? [])
            .map(event => {
                const start = Number(event.tStartMs ?? Number.NaN) / 1000;
                const duration = Number(event.dDurationMs ?? 0) / 1000;
                const cueText = (event.segs ?? []).map(seg => seg.utf8 ?? '').join('').replace(/\s+/g, ' ').trim();
                const end = start + Math.max(duration, 0.75);
                const words = options.youtubeAutoGenerated ? undefined : youtubeJson3WordTimings(event.segs ?? [], start, end);
                return { start, end, text: cueText, words, wordTimingsExact: Boolean(words?.length) };
            })
            .filter(cue => Number.isFinite(cue.start) && Number.isFinite(cue.end) && cue.text)
            .sort((a, b) => a.start - b.start);
        return smoothFragmentedYouTubeCues(normalizeYouTubeAutoCaptionTiming(cues, options.youtubeAutoGenerated === true));
    } catch {
        return [];
    }
}

function youtubeJson3WordTimings(segs: Array<{ utf8?: string; tOffsetMs?: number }>, cueStart: number, cueEnd: number): SubtitleWordTiming[] | undefined {
    const visible = segs
        .map(seg => ({ text: seg.utf8 ?? '', offset: Number(seg.tOffsetMs) }))
        .filter(seg => seg.text.trim());
    const timed = visible.filter(seg => Number.isFinite(seg.offset) && !/\s/u.test(seg.text.trim()));
    if (!timed.length || timed.length !== visible.length) return undefined;
    return timed.map((seg, index) => {
        const nextOffset = timed[index + 1]?.offset;
        const start = cueStart + seg.offset / 1000;
        const end = nextOffset === undefined ? cueEnd : cueStart + nextOffset / 1000;
        return { text: seg.text, start: clampNumber(start, cueStart, cueEnd), end: clampNumber(end, cueStart, cueEnd) };
    }).filter(word => word.end > word.start);
}

function parseYouTubeXmlSubtitleText(text: string, options: ParseSubtitleTextOptions = {}): SubtitleCue[] {
    if (!looksLikeYouTubeXmlSubtitleText(text)) return [];
    try {
        const document = parseXmlDocument(text, 'text/xml');
        const srv3 = parseYouTubeSrv3Rows(document, options);
        const cues = [
            ...parseYouTubeTimedTextElements(document),
            ...parseYouTubeTtmlParagraphs(document),
            ...srv3.cues,
        ];
        const sorted = cues.sort((a, b) => a.start - b.start);
        const autoGenerated = isYouTubeXmlAutoGenerated(options, srv3, sorted);
        const normalized = normalizeYouTubeAutoCaptionTiming(sorted, autoGenerated);
        return autoGenerated ? normalized : smoothFragmentedYouTubeCues(normalized);
    } catch {
        return [];
    }
}

function looksLikeYouTubeXmlSubtitleText(text: string): boolean {
    return /^\s*</.test(text) && /(<text\b|<p\b)/i.test(text);
}

function isYouTubeXmlAutoGenerated(options: ParseSubtitleTextOptions, srv3: { sawLineBoundary: boolean }, cues: SubtitleCue[]): boolean {
    return options.youtubeAutoGenerated === true
        || srv3.sawLineBoundary
        || looksLikeOverlappingAutoGeneratedCues(cues);
}

function parseYouTubeTimedTextElements(document: Document): SubtitleCue[] {
    return Array.from(document.querySelectorAll('text[start]'))
        .map(element => {
            const start = Number(element.getAttribute('start'));
            const duration = Number(element.getAttribute('dur') ?? 0);
            const cueText = normalizeCaptionText(element.textContent ?? '');
            return Number.isFinite(start) && cueText
                ? { start, end: start + Math.max(duration, 0.75), text: cueText }
                : null;
        })
        .filter((cue): cue is SubtitleCue => Boolean(cue));
}

function parseYouTubeTtmlParagraphs(document: Document): SubtitleCue[] {
    return Array.from(document.querySelectorAll('p[begin]'))
        .map(element => {
            const start = parseSubtitleClockValue(element.getAttribute('begin') ?? '');
            const end = parseSubtitleClockValue(element.getAttribute('end') ?? '');
            const cueText = normalizeCaptionText(element.textContent ?? '');
            return Number.isFinite(start) && Number.isFinite(end) && cueText
                ? { start, end, text: cueText }
                : null;
        })
        .filter((cue): cue is SubtitleCue => Boolean(cue));
}

function parseYouTubeSrv3Rows(document: Document, options: ParseSubtitleTextOptions): { cues: SubtitleCue[]; sawLineBoundary: boolean } {
    const rows = Array.from(document.querySelectorAll('p[t], p[_t]'));
    let sawLineBoundary = false;
    const cues = rows
        .map((element, index) => {
            const startMs = Number(element.getAttribute('t') ?? element.getAttribute('_t'));
            const durationMs = Number(element.getAttribute('d') ?? element.getAttribute('_d') ?? 0);
            const start = startMs / 1000;
            const nextLineBoundary = youtubeSrv3LineBoundaryTime(rows[index + 1]);
            sawLineBoundary ||= Number.isFinite(nextLineBoundary);
            const rawEnd = start + Math.max(durationMs / 1000, 0.75);
            const end = Number.isFinite(nextLineBoundary) && nextLineBoundary > start
                ? Math.min(rawEnd, nextLineBoundary)
                : rawEnd;
            const words = !options.youtubeAutoGenerated && !Number.isFinite(nextLineBoundary)
                ? parseYouTubeSrv3WordNodes(element, start, end)
                : [];
            const cueText = normalizeCaptionText(words.length ? words.map(word => word.text).join('') : element.textContent ?? '');
            if (!Number.isFinite(start) || !cueText) return null;
            const cue: SubtitleCue = { start, end, text: cueText, words: words.length ? words : undefined, wordTimingsExact: Boolean(words.length) };
            return cue;
        })
        .filter((cue): cue is SubtitleCue => Boolean(cue));
    return { cues, sawLineBoundary };
}

function youtubeSrv3LineBoundaryTime(element: Element | undefined): number {
    if (!element) return Number.NaN;
    if (!isYouTubeSrv3LineBoundaryText(element.textContent ?? '')) return Number.NaN;
    const startMs = Number(youtubeSrv3StartAttribute(element));
    return Number.isFinite(startMs) ? startMs / 1000 : Number.NaN;
}

function isYouTubeSrv3LineBoundaryText(text: string): boolean {
    return text === '\n' || !text.trim();
}

function youtubeSrv3StartAttribute(element: Element): string | null {
    return element.getAttribute('t') ?? element.getAttribute('_t');
}

function normalizeYouTubeAutoCaptionTiming(cues: SubtitleCue[], knownAutoGenerated: boolean): SubtitleCue[] {
    if (!cues.length) return cues;
    const probablyAutoGenerated = knownAutoGenerated || looksLikeOverlappingAutoGeneratedCues(cues);
    if (!probablyAutoGenerated) return cues;

    return cues.map((cue, index) => {
        const next = cues[index + 1];
        const nextStart = next?.start;
        const end = Number.isFinite(nextStart) && nextStart > cue.start
            ? Math.max(cue.start, Math.min(cue.end, nextStart - 0.001))
            : cue.end;
        return {
            ...cue,
            end,
            words: undefined,
            wordTimingsExact: false,
        };
    });
}

function looksLikeOverlappingAutoGeneratedCues(cues: SubtitleCue[]): boolean {
    const sampled = cues.slice(0, 80);
    if (sampled.length < 3) return false;
    let overlapping = 0;
    for (let index = 1; index < sampled.length; index++) {
        if (sampled[index - 1].end > sampled[index].start + 0.05) overlapping += 1;
    }
    return overlapping / sampled.length > 0.5;
}

function smoothFragmentedYouTubeCues(cues: SubtitleCue[]): SubtitleCue[] {
    if (!shouldSmoothFragmentedYouTubeCues(cues)) return cues;
    const merged: SubtitleCue[] = [];
    let current: SubtitleCue | undefined;

    for (const cue of cues) {
        current = mergeYouTubeFragmentIntoGroup(merged, current, cue);
    }
    if (current) merged.push(current);
    return merged;
}

function shouldSmoothFragmentedYouTubeCues(cues: SubtitleCue[]): boolean {
    return cues.length >= 3 && looksLikeFragmentedYouTubeCues(cues);
}

function mergeYouTubeFragmentIntoGroup(
    merged: SubtitleCue[],
    current: SubtitleCue | undefined,
    cue: SubtitleCue,
): SubtitleCue | undefined {
    const normalized = normalizeYouTubeCueFragment(cue);
    if (!normalized.text) return current;
    if (!current) {
        return pushCurrentYouTubeCueGroup(merged, current, normalized);
    }
    if (shouldBreakYouTubeLine(current, normalized)) return pushCurrentYouTubeCueGroup(merged, current, normalized);
    return mergeYouTubeCueFragments(current, normalized);
}

function normalizeYouTubeCueFragment(cue: SubtitleCue): SubtitleCue {
    const hasExactWords = cueHasExactWordTimings(cue);
    return {
        ...cue,
        text: normalizeCaptionText(cue.text),
        words: hasExactWords ? cue.words : undefined,
        wordTimingsExact: hasExactWords,
    };
}

function pushCurrentYouTubeCueGroup(
    merged: SubtitleCue[],
    current: SubtitleCue | undefined,
    next: SubtitleCue,
): SubtitleCue {
    if (current) merged.push(current);
    return next;
}

function looksLikeFragmentedYouTubeCues(cues: SubtitleCue[]): boolean {
    const sampled = cues.slice(0, 80);
    const fragments = sampled.filter(cue => displayTextWeight(cue.text) <= 14 || cue.end - cue.start <= 1.35).length;
    return fragments / sampled.length >= 0.42;
}

function shouldBreakYouTubeLine(current: SubtitleCue, next: SubtitleCue): boolean {
    const gap = next.start - current.end;
    if (isYouTubeContinuationFragment(current, next)) return false;
    return gap > 2.6
        || (gap < -0.2 && !isProgressiveYouTubeCaption(current.text, next.text))
        || hasYouTubeLineBreakText(current);
}

function hasYouTubeLineBreakText(cue: SubtitleCue): boolean {
    return /[。！？!?]$/u.test(cue.text.trim())
        || cue.end - cue.start >= 12
        || displayTextWeight(cue.text) >= 68;
}

function isYouTubeContinuationFragment(current: SubtitleCue, next: SubtitleCue): boolean {
    return isTrailingPunctuationFragment(next.text)
        || isShortYouTubeContinuationFragment(next.text)
        || hasYouTubeCaptionTextOverlap(current.text, next.text);
}

function mergeYouTubeCueFragments(current: SubtitleCue, next: SubtitleCue): SubtitleCue {
    const progressive = isProgressiveYouTubeCaption(current.text, next.text);
    const overlap = progressive ? 0 : youtubeCaptionTextOverlapLength(current.text, next.text);
    const text = progressive ? next.text : mergeYouTubeCaptionFragmentText(current.text, next.text);
    const words = mergedYouTubeCueWords(current, next, { progressive, overlap });
    return {
        ...current,
        end: Math.max(current.end, next.end),
        text,
        originalText: text,
        words,
        wordTimingsExact: Boolean(words?.length),
    };
}

function mergedYouTubeCueWords(
    current: SubtitleCue,
    next: SubtitleCue,
    merge: { progressive: boolean; overlap: number },
): SubtitleWordTiming[] | undefined {
    const words = youtubeCueMergeWords(current, next);
    if (merge.progressive) return words.next;
    if (!canMergeYouTubeCueWords(words.current, words.next, next.text)) return undefined;
    return [...words.current, ...trimmedNextYouTubeCueWords(words.next, merge.overlap)];
}

function youtubeCueMergeWords(current: SubtitleCue, next: SubtitleCue): { current: SubtitleWordTiming[] | undefined; next: SubtitleWordTiming[] | undefined } {
    return {
        current: cueHasExactWordTimings(current) ? current.words : undefined,
        next: cueHasExactWordTimings(next) ? next.words : undefined,
    };
}

function trimmedNextYouTubeCueWords(words: SubtitleWordTiming[] | undefined, overlap: number): SubtitleWordTiming[] {
    return words ? subtitleWordsAfterCompactOffset(words, overlap) : [];
}

function canMergeYouTubeCueWords(
    currentWords: SubtitleWordTiming[] | undefined,
    nextWords: SubtitleWordTiming[] | undefined,
    nextText: string,
): currentWords is SubtitleWordTiming[] {
    return Boolean(currentWords && (nextWords || isTrailingPunctuationFragment(nextText)));
}

function mergeYouTubeCaptionFragmentText(left: string, right: string): string {
    const a = left.trim();
    const b = right.trim();
    const overlap = youtubeCaptionTextOverlapLength(a, b);
    if (overlap > 0) {
        const tail = sliceByCompactOffset(b, overlap);
        return tail ? joinYouTubeCaptionFragments(a, tail) : a;
    }
    return joinYouTubeCaptionFragments(a, b);
}

function isProgressiveYouTubeCaption(current: string, next: string): boolean {
    const compactCurrent = current.replace(/\s+/gu, '');
    const compactNext = next.replace(/\s+/gu, '');
    return compactCurrent.length >= 2 && compactNext.length > compactCurrent.length && compactNext.startsWith(compactCurrent);
}

function joinYouTubeCaptionFragments(left: string, right: string): string {
    const a = left.trim();
    const b = right.trim();
    const emptyJoin = emptyYouTubeCaptionFragmentJoin(a, b);
    if (emptyJoin !== null) return emptyJoin;
    return `${a}${youtubeCaptionFragmentSeparator(a, b)}${b}`;
}

function emptyYouTubeCaptionFragmentJoin(left: string, right: string): string | null {
    if (!left) return right;
    return right ? null : left;
}

function youtubeCaptionFragmentSeparator(left: string, right: string): string {
    if (shouldJoinYouTubeCaptionFragmentsDirectly(left, right)) return '';
    return shouldSpaceYouTubeCaptionFragments(left, right) ? ' ' : '';
}

function shouldJoinYouTubeCaptionFragmentsDirectly(left: string, right: string): boolean {
    return /^[、。，．！？!?））」』\]}]/u.test(right) || /[\s「『（([{]$/u.test(left);
}

function shouldSpaceYouTubeCaptionFragments(left: string, right: string): boolean {
    return /[A-Za-z0-9]$/u.test(left) && /^[A-Za-z0-9]/u.test(right);
}

function isTrailingPunctuationFragment(text: string): boolean {
    return /^[、。，．！？!?…・]+$/u.test(text.trim());
}

function isShortYouTubeContinuationFragment(text: string): boolean {
    const compact = compactCaptionText(text);
    return compact.length <= 3 && /^[っッゃゅょぁぃぅぇぉャュョァィゥェォー〜、。，．！？!?…・んン]+$/u.test(compact);
}

function hasYouTubeCaptionTextOverlap(left: string, right: string): boolean {
    return youtubeCaptionTextOverlapLength(left, right) >= Math.min(6, compactCaptionText(right).length);
}

function youtubeCaptionTextOverlapLength(left: string, right: string): number {
    const a = compactCaptionText(left);
    const b = compactCaptionText(right);
    const max = Math.min(a.length, b.length);
    for (let length = max; length >= 2; length--) {
        if (a.endsWith(b.slice(0, length))) return length;
    }
    return 0;
}

function compactCaptionText(text: string): string {
    return text.replace(/\s+/gu, '');
}

function subtitleWordsAfterCompactOffset(words: SubtitleWordTiming[], compactOffset: number): SubtitleWordTiming[] {
    if (compactOffset <= 0) return words;
    let cursor = 0;
    return words.filter(word => {
        const start = cursor;
        cursor += compactTextLength(word.text);
        return start >= compactOffset;
    });
}

function sliceByCompactOffset(text: string, compactOffset: number): string {
    if (compactOffset <= 0) return text;
    for (const step of compactTextOffsetSteps(text)) {
        if (step.seen >= compactOffset) return text.slice(step.index);
    }
    return '';
}

function compactTextOffsetSteps(text: string): Array<{ index: number; seen: number }> {
    const steps: Array<{ index: number; seen: number }> = [];
    let index = 0;
    let seen = 0;
    for (const char of Array.from(text)) {
        index += char.length;
        if (/\s/u.test(char)) continue;
        steps.push({ index, seen: ++seen });
    }
    return steps;
}

function parseYouTubeSrv3WordNodes(element: Element, cueStart: number, cueEnd: number): SubtitleWordTiming[] {
    const nodes = Array.from(element.querySelectorAll('s'));
    if (!nodes.length) return [];
    if (nodes.some(node => /\s/u.test((node.textContent ?? '').trim()))) return [];
    const starts = nodes.map(node => {
        const raw = Number(node.getAttribute('t') ?? node.getAttribute('_t'));
        return Number.isFinite(raw) ? cueStart + raw / 1000 : Number.NaN;
    });
    return nodes.map((node, index) => {
        const text = node.textContent ?? '';
        if (!text) return null;
        const start = Number.isFinite(starts[index]) ? starts[index] : cueStart;
        const nextStart = starts.slice(index + 1).find(value => Number.isFinite(value));
        const end = typeof nextStart === 'number' && Number.isFinite(nextStart) ? nextStart : cueEnd;
        return { text, start: clampNumber(start, cueStart, cueEnd), end: clampNumber(end, cueStart, cueEnd) };
    }).filter((word): word is SubtitleWordTiming => Boolean(word?.text.trim() && word.end > word.start));
}

function parseAssSubtitleText(text: string): SubtitleCue[] {
    const state = createAssParseState();
    for (const rawLine of text.replace(/\r/g, '').split('\n')) {
        readAssSubtitleLine(rawLine.trim(), state);
    }
    return state.cues.sort((a, b) => a.start - b.start);
}

interface AssParseState {
    cues: SubtitleCue[];
    inEvents: boolean;
    format: string[];
}

function createAssParseState(): AssParseState {
    return {
        cues: [],
        inEvents: false,
        format: ['layer', 'start', 'end', 'style', 'name', 'marginl', 'marginr', 'marginv', 'effect', 'text'],
    };
}

function readAssSubtitleLine(line: string, state: AssParseState): void {
    if (!shouldParseAssCueLine(line, state)) return;
    const cue = readAssDialogueCue(line, state.format);
    if (cue) state.cues.push(cue);
}

function shouldParseAssCueLine(line: string, state: AssParseState): boolean {
    if (shouldIgnoreAssLine(line)) return false;
    if (updateAssSectionState(line, state)) return false;
    if (!shouldReadAssDialogueLine(line, state)) return false;
    return !readAssFormatLine(line, state);
}

function shouldReadAssDialogueLine(line: string, state: AssParseState): boolean {
    return state.inEvents || /^Dialogue:/i.test(line);
}

function shouldIgnoreAssLine(line: string): boolean {
    return !line || line.startsWith(';');
}

function updateAssSectionState(line: string, state: AssParseState): boolean {
    if (/^\[Events\]/i.test(line)) {
        state.inEvents = true;
        return true;
    }
    if (/^\[.+\]/.test(line)) {
        state.inEvents = false;
        return true;
    }
    return false;
}

function readAssFormatLine(line: string, state: AssParseState): boolean {
    if (!/^Format:/i.test(line)) return false;
    state.format = line.slice(line.indexOf(':') + 1).split(',').map(part => part.trim().toLowerCase());
    return true;
}

function readAssDialogueCue(line: string, format: string[]): SubtitleCue | null {
    if (!/^Dialogue:/i.test(line)) return null;
    const values = splitAssDialogue(line.slice(line.indexOf(':') + 1), format.length);
    const fields = assDialogueFields(values, format);
    const start = parseSubtitleTime(fields.start);
    const end = parseSubtitleTime(fields.end);
    const cueText = cleanAssSubtitleText(fields.text);
    return Number.isFinite(start) && Number.isFinite(end) && cueText
        ? { start, end, text: cueText }
        : null;
}

function assDialogueFields(values: string[], format: string[]): { start: string; end: string; text: string } {
    const textIndex = format.indexOf('text');
    return {
        start: values[format.indexOf('start')] ?? '',
        end: values[format.indexOf('end')] ?? '',
        text: values.slice(textIndex >= 0 ? textIndex : values.length - 1).join(','),
    };
}

function splitAssDialogue(value: string, fieldCount: number): string[] {
    const parts: string[] = [];
    let start = 0;
    const maxSplits = Math.max(0, fieldCount - 1);
    for (let index = 0; index < value.length && parts.length < maxSplits; index++) {
        if (value[index] !== ',') continue;
        parts.push(value.slice(start, index).trim());
        start = index + 1;
    }
    parts.push(value.slice(start).trim());
    return parts;
}

function cleanAssSubtitleText(value: string): string {
    return value
        .replace(/\{[^}]*}/g, '')
        .replace(/\\[Nn]/g, '\n')
        .replace(/\\h/g, ' ')
        .replace(/<[^>]+>/g, '')
        .split('\n')
        .map(line => line.replace(/\s+/g, ' ').trim())
        .filter(Boolean)
        .join('\n');
}

function parseSubtitleTime(value: string): number {
    const match = value.trim().match(/(?:(\d+):)?(\d{1,2}):(\d{2})(?:[,.](\d{1,3}))?/);
    if (!match) return Number.NaN;
    const [, hours = '0', minutes, seconds, fraction = '0'] = match;
    return Number(hours) * 3600 + Number(minutes) * 60 + Number(seconds) + Number(fraction.padEnd(3, '0')) / 1000;
}

function parseSubtitleClockValue(value: string): number {
    const trimmed = value.trim();
    if (!trimmed) return Number.NaN;
    if (/^\d+(?:\.\d+)?s$/i.test(trimmed)) return Number(trimmed.slice(0, -1));
    if (/^\d+(?:\.\d+)?ms$/i.test(trimmed)) return Number(trimmed.slice(0, -2)) / 1000;
    if (/^\d+(?:\.\d+)?$/.test(trimmed)) return Number(trimmed);
    return parseSubtitleTime(trimmed);
}

export function formatSubtitleTime(value: number): string {
    const minutes = Math.floor(value / 60);
    const seconds = Math.floor(value % 60).toString().padStart(2, '0');
    return `${minutes}:${seconds}`;
}

export function findAlignedCue(cues: SubtitleCue[], cue: SubtitleCue): SubtitleCue | undefined {
    return cues
        .map(item => ({
            item,
            overlap: Math.max(0, Math.min(cue.end, item.end) - Math.max(cue.start, item.start)),
            startDistance: Math.abs(cue.start - item.start),
        }))
        .filter(candidate => candidate.overlap > 0 || candidate.startDistance <= 0.45)
        .sort((a, b) => b.overlap - a.overlap || a.startDistance - b.startDistance)[0]?.item;
}

export function findActiveSubtitleCue(cues: SubtitleCue[], time: number): SubtitleCue | undefined {
    return cues
        .filter(cue => time >= cue.start - 0.05 && time < cue.end + 0.12)
        .sort((a, b) => b.start - a.start || b.end - a.end)[0];
}

export function subtitleCueSignature(cue: SubtitleCue): string {
    return `${cue.start.toFixed(2)}:${cue.end.toFixed(2)}:${cue.text.trim()}`;
}

export function cueHasExactWordTimings(cue: SubtitleCue | undefined): cue is SubtitleCue & { words: SubtitleWordTiming[]; wordTimingsExact: true } {
    return Boolean(cue?.wordTimingsExact && cue.words?.length);
}

export function normalizeCaptionText(value: string): string {
    return value
        .replace(/\u00a0/g, ' ')
        .split('\n')
        .map(line => line.replace(/\s+/g, ' ').trim())
        .filter(Boolean)
        .join(' ');
}

export function escapeWithBreaks(value: string): string {
    return withBreaks(escapeHtml(value));
}

export function withBreaks(value: string): string {
    return value.replace(/\n/g, '<br>');
}
