import type { SubtitleCue } from './subtitle-cues';
import { normalizeSubtitleLanguage } from './subtitle-sources';
import { isAutoGeneratedSubtitleTrack } from './subtitle-youtube';

export type SubtitleTrackKind = 'native' | 'file' | 'youtube' | 'remote';
export type SubtitleTrackLoadingState = 'idle' | 'loading' | 'ready' | 'waiting' | 'error';

export interface SubtitleTrackMetadata {
    label: string;
    kind: SubtitleTrackKind;
    language?: string;
    autoGenerated?: boolean;
    loadingState?: SubtitleTrackLoadingState;
}

export function trackStatusText(track: SubtitleTrackMetadata): string {
    if (track.loadingState === 'loading') return ' · loading';
    if (track.loadingState === 'waiting') return ' · waiting for captions';
    if (track.loadingState === 'error') return ' · failed';
    return '';
}

export function formatTrackKind(kind: SubtitleTrackKind): string {
    if (kind === 'native') return 'page track';
    if (kind === 'remote') return 'page file';
    if (kind === 'youtube') return 'YouTube captions';
    return 'loaded file';
}

export function compareSubtitleTrackOptions<T extends SubtitleTrackMetadata>(a: T, b: T): number {
    return subtitleTrackRank(a) - subtitleTrackRank(b)
        || (a.language ?? '').localeCompare(b.language ?? '', undefined, { sensitivity: 'base' })
        || a.label.localeCompare(b.label, undefined, { sensitivity: 'base' });
}

export function isJapaneseSubtitleTrack(track: SubtitleTrackMetadata): boolean {
    const language = track.language?.toLowerCase() ?? '';
    const label = track.label.toLowerCase();
    return language === 'ja' || language.startsWith('ja-') || /日本語|japanese/.test(label);
}

export function isEnglishSubtitleTrack(track: SubtitleTrackMetadata): boolean {
    return /(^|\b)(en|eng|english)(\b|$)/i.test(`${track.label} ${track.language ?? ''}`);
}

export function shouldReplaceWaitingNativeTrack(
    selected: SubtitleTrackMetadata | undefined,
    replacement: SubtitleTrackMetadata,
    cues: SubtitleCue[],
): boolean {
    return isWaitingNativeTrack(selected, cues)
        && (hasSameSubtitleRole(selected, replacement) || hasSameNormalizedSubtitleLanguage(selected, replacement));
}

function isWaitingNativeTrack(
    selected: SubtitleTrackMetadata | undefined,
    cues: SubtitleCue[],
): selected is SubtitleTrackMetadata {
    return Boolean(selected && selected.kind === 'native' && !cues.length);
}

function hasSameSubtitleRole(selected: SubtitleTrackMetadata, replacement: SubtitleTrackMetadata): boolean {
    return (isJapaneseSubtitleTrack(selected) && isJapaneseSubtitleTrack(replacement))
        || (isEnglishSubtitleTrack(selected) && isEnglishSubtitleTrack(replacement));
}

function hasSameNormalizedSubtitleLanguage(selected: SubtitleTrackMetadata, replacement: SubtitleTrackMetadata): boolean {
    const selectedLanguage = normalizeSubtitleLanguage(selected.language);
    const replacementLanguage = normalizeSubtitleLanguage(replacement.language);
    return Boolean(selectedLanguage && replacementLanguage && selectedLanguage === replacementLanguage);
}

function subtitleTrackRank(track: SubtitleTrackMetadata): number {
    return SUBTITLE_TRACK_RANKS.find(rule => rule.matches(track))?.rank ?? 5;
}

interface SubtitleTrackRankRule {
    rank: number;
    matches: (track: SubtitleTrackMetadata) => boolean;
}

const SUBTITLE_TRACK_RANKS: SubtitleTrackRankRule[] = [
    { rank: 0, matches: track => track.kind === 'file' },
    { rank: 1, matches: isManualJapaneseSubtitleTrack },
    { rank: 2, matches: isJapaneseSubtitleTrack },
    { rank: 3, matches: isAutoGeneratedSubtitleTrack },
    { rank: 4, matches: isEnglishOrNativeSubtitleTrack },
];

function isManualJapaneseSubtitleTrack(track: SubtitleTrackMetadata): boolean {
    return isJapaneseSubtitleTrack(track) && !isAutoGeneratedSubtitleTrack(track);
}

function isEnglishOrNativeSubtitleTrack(track: SubtitleTrackMetadata): boolean {
    return isEnglishSubtitleTrack(track) || track.kind === 'native';
}
