import {
    correspondingWebsiteLocaleHref,
    websiteLocale,
    websiteLocaleForPathname,
    websiteMessage,
    type WebsiteLocaleId,
} from '../locales/site-locales';

type RouteHeadEntry = readonly [
    tag: 'link' | 'meta' | 'script',
    attributes: Readonly<Record<string, string>>,
    content?: string,
];

const LOCALE_BY_MENU_LABEL: Readonly<Record<string, WebsiteLocaleId>> = {
    English: 'en',
    日本語: 'ja',
};

/**
 * Reconcile the two VitePress assumptions our reviewed-route ledger makes
 * invalid: locale routes are not universally present, and transformHead does
 * not update custom metadata during client-side navigation.
 */
export function syncWebsiteRouteLocalization(routeHead: unknown): void {
    syncDocumentLocale();
    syncPublishedLocaleLinks();
    syncDefaultThemeAccessibleCopy();
    syncRouteHead(routeHead);
}

function syncDocumentLocale(): void {
    const locale = websiteLocaleForPathname(window.location.pathname);
    const publication = websiteLocale(locale);
    if (!publication) return;
    document.documentElement.lang = publication.tag;
    document.documentElement.dir = publication.direction;
}

function syncPublishedLocaleLinks(): void {
    const containers = document.querySelectorAll(
        '.VPNavBarTranslations, .VPNavBarExtra, .VPNavScreenTranslations',
    );
    const links = new Set<HTMLAnchorElement>();
    containers.forEach(container => {
        container.querySelectorAll<HTMLAnchorElement>('a[href]').forEach(link => links.add(link));
    });
    links.forEach(link => {
        const targetLocale = LOCALE_BY_MENU_LABEL[link.textContent?.trim() ?? ''];
        if (!targetLocale) return;
        link.setAttribute(
            'href',
            correspondingWebsiteLocaleHref(window.location.pathname, targetLocale),
        );
        // Locale routes have complete reviewed SSR documents. VitePress skips
        // links with an explicit target, allowing the browser to load that
        // document atomically instead of painting the previous language after
        // its SPA router has already changed the pathname.
        link.setAttribute('target', '_self');
    });
}

function syncDefaultThemeAccessibleCopy(): void {
    const locale = websiteLocaleForPathname(window.location.pathname);
    const mainNavigation = document.getElementById('main-nav-aria-label');
    if (mainNavigation) mainNavigation.textContent = websiteMessage('docs.theme.mainNavigation', locale);
    document.querySelectorAll<HTMLElement>('.VPNavBarHamburger').forEach(element => {
        element.setAttribute('aria-label', websiteMessage('docs.theme.mobileNavigation', locale));
    });
    document.querySelectorAll<HTMLElement>('.VPNavBarExtra > button[aria-label]').forEach(element => {
        element.setAttribute('aria-label', websiteMessage('docs.theme.extraNavigation', locale));
    });
}

function syncRouteHead(value: unknown): void {
    const entries = routeHeadEntries(value);
    if (!entries) return;
    document.head.querySelectorAll('[data-yomu-route-head]').forEach(element => element.remove());
    entries.forEach(([tag, attributes, content]) => {
        const element = document.createElement(tag);
        Object.entries(attributes).forEach(([name, attributeValue]) => {
            element.setAttribute(name, attributeValue);
        });
        if (content !== undefined) element.textContent = content;
        document.head.append(element);
    });
}

function routeHeadEntries(value: unknown): RouteHeadEntry[] | undefined {
    // This value is generated by websiteRouteHead during the same VitePress
    // build, then serialized through page frontmatter. The public boundary is
    // only whether that page owns route-head data; individual tuples are not
    // user-authored input and retain their build-time RouteHeadEntry contract.
    return Array.isArray(value) ? value as RouteHeadEntry[] : undefined;
}
