import { isNonNullObject as isRecord } from '../core/object-utils';
import { normalizeSubtitleCues, parseSubtitleText, type SubtitleCue } from './subtitle-cues';
import { uniqueNonEmptyStrings as uniqueStrings } from '../core/string-utils';
import { readYouTubeConfigStringFromScripts } from './youtube-config';
import { isYouTubeAppHostname } from '../app/youtube-host';

const YOUTUBE_VIDEO_PLAYER_SELECTOR = '#movie_player, .html5-video-player';
const YOUTUBE_VIDEO_OWNER_SELECTOR = `${YOUTUBE_VIDEO_PLAYER_SELECTOR}, ytd-player, ytd-watch-flexy, #player, #player-container, #player-container-outer, .html5-video-container`;

export interface YouTubeSubtitleTrack {
    label: string;
    kind?: string;
    language?: string;
    autoGenerated?: boolean;
    url?: string;
    youtubeTrack?: unknown;
    cues?: SubtitleCue[];
    sourceType?: YouTubeCaptionTrackSourceType;
    sourceLanguage?: string;
    targetLanguage?: string;
    vssId?: string;
    youtubeIdentity?: string;
}

export type YouTubeCaptionTrackSourceType = 'manual' | 'asr' | 'translation';

export interface YouTubeCaptionTrackCandidate {
    label: string;
    language?: string;
    autoGenerated?: boolean;
    url: string;
    raw: unknown;
    sourceType: YouTubeCaptionTrackSourceType;
    sourceLanguage?: string;
    targetLanguage?: string;
    vssId?: string;
    youtubeIdentity: string;
}

interface AndroidYouTubeCaptionRequest {
    url: string;
    init: RequestInit;
    videoId: string;
}

export interface YouTubeTrackLoadOptions<T extends YouTubeSubtitleTrack> {
    requestText: (url: string) => Promise<string>;
    onRequestError?: (track: T, url: string, error: unknown) => void;
}

export interface YouTubeCaptionDiscoveryOptions {
    preferredTranslationLanguages?: readonly string[];
}

export interface CurrentYouTubeCaptionDiscoveryOptions extends YouTubeCaptionDiscoveryOptions {
    contextKey: string;
    currentContextKey: () => string;
    onVideoId: (videoId: string) => void;
}

/** One context-safe YouTube discovery transaction for the controller Adapter. */
export async function discoverCurrentYouTubeCaptionTracks(
    options: CurrentYouTubeCaptionDiscoveryOptions,
): Promise<YouTubeCaptionTrackCandidate[] | null> {
    if (!isYouTubePage()) return null;
    const videoId = getYouTubeVideoId();
    if (!videoId) return null;
    options.onVideoId(videoId);
    const tracks = await discoverYouTubeCaptionTracks(options);
    return currentYouTubeDiscoveryTracks(tracks, options);
}

function currentYouTubeDiscoveryTracks(
    tracks: YouTubeCaptionTrackCandidate[],
    options: Pick<CurrentYouTubeCaptionDiscoveryOptions, 'contextKey' | 'currentContextKey'>,
): YouTubeCaptionTrackCandidate[] | null {
    if (!tracks.length) return null;
    return options.contextKey === options.currentContextKey() ? tracks : null;
}

export async function discoverYouTubeCaptionTracks(options: YouTubeCaptionDiscoveryOptions = {}): Promise<YouTubeCaptionTrackCandidate[]> {
    const pageTracks = getYouTubeCaptionTracks(options);
    const androidTracks = await getAndroidYouTubeCaptionTracks(options.preferredTranslationLanguages);
    return uniqueYouTubeCaptionTrackCandidates([
        ...pageTracks,
        ...androidTracks,
    ]);
}

export async function loadYouTubeTrackCues<T extends YouTubeSubtitleTrack>(
    track: T,
    options: YouTubeTrackLoadOptions<T>,
): Promise<SubtitleCue[]> {
    if (!track.url) return [];
    applyPreferredYouTubeCaptionCandidate(track);
    const tried = new Set<string>();
    const primary = await loadYouTubeCueUrls(track, youtubeSubtitleRequestUrls(track.url), options, tried);
    if (primary.length) return primary;
    for (const candidate of await fallbackYouTubeCaptionCandidates(track)) {
        const cues = await loadYouTubeCueUrls(track, youtubeSubtitleRequestUrls(candidate.url), options, tried);
        if (!cues.length) continue;
        track.url = candidate.url;
        track.youtubeTrack = candidate.raw;
        return cues;
    }
    return [];
}

async function loadYouTubeCueUrls<T extends YouTubeSubtitleTrack>(
    track: T,
    urls: string[],
    options: YouTubeTrackLoadOptions<T>,
    tried: Set<string>,
): Promise<SubtitleCue[]> {
    for (const url of urls) {
        if (tried.has(url)) continue;
        tried.add(url);
        try {
            const text = await options.requestText(url);
            if (!text.trim()) throw new Error('YouTube timedtext response was empty.');
            const cues = normalizeSubtitleCues(parseSubtitleText(text, {
                smoothYouTubeFragments: true,
                youtubeAutoGenerated: isAutoGeneratedSubtitleTrack(track),
            }));
            if (cues.length) return cues;
        } catch (error) {
            options.onRequestError?.(track, url, error);
        }
    }
    return [];
}

function applyPreferredYouTubeCaptionCandidate<T extends YouTubeSubtitleTrack>(track: T): void {
    const preferred = findPreferredYouTubeCaptionCandidate(track);
    if (!preferred) return;
    if (!track.url || !shouldRefreshYouTubeTrackUrl(preferred.url, track.url)) return;
    track.url = preferred.url;
    track.youtubeTrack = preferred.raw;
}

export async function loadFirstUsableYouTubeSibling<T extends YouTubeSubtitleTrack>(
    track: T,
    tracks: T[],
    options: YouTubeTrackLoadOptions<T>,
): Promise<{ track: T; cues: SubtitleCue[] } | null> {
    const siblings = tracks.filter(candidate => candidate.kind === 'youtube'
        && candidate !== track
        && compatibleYouTubeCaptionTracks(candidate, track)
        && candidate.url);
    for (const sibling of siblings) {
        const cues = sibling.cues?.length ? sibling.cues : await loadYouTubeTrackCues(sibling, options);
        if (!cues.length) continue;
        sibling.cues = cues;
        return { track: sibling, cues };
    }
    return null;
}

export function getYouTubeCaptionTracks(options: YouTubeCaptionDiscoveryOptions = {}): YouTubeCaptionTrackCandidate[] {
    const playerTracks = getYouTubePlayerCaptionTracks();
    const response = getYouTubePlayerResponse();
    const renderer = response?.captions?.playerCaptionsTracklistRenderer;
    const rawTracks = renderer?.captionTracks;
    return uniqueYouTubeCaptionTracks([
        ...playerTracks,
        ...(Array.isArray(rawTracks) ? rawTracks : []),
    ], renderer?.translationLanguages, options.preferredTranslationLanguages);
}

export function youtubeVideoHasNativeCaptions(): boolean {
    if (getYouTubeCaptionTracks().length) return true;
    // YouTube hides/disables the CC button when the video has no caption
    // tracks at all, which also means the DOM caption fallback can never
    // produce text for it.
    const button = document.querySelector<HTMLElement>('#movie_player .ytp-subtitles-button');
    if (!button) return false;
    return button.getAttribute('aria-disabled') !== 'true' && button.style.display !== 'none';
}

async function fallbackYouTubeCaptionCandidates(track: YouTubeSubtitleTrack): Promise<YouTubeCaptionTrackCandidate[]> {
    if (track.kind !== 'youtube') return [];
    const candidates = await getAndroidYouTubeCaptionTracks([track.targetLanguage ?? '', track.language ?? '']);
    return candidates
        .filter(candidate => youtubeCaptionCandidateMatchesTrack(candidate, track))
        .sort((a, b) => youtubeTrackUrlScore(b.url) - youtubeTrackUrlScore(a.url));
}

function youtubeCaptionCandidateMatchesTrack(candidate: YouTubeCaptionTrackCandidate, track: YouTubeSubtitleTrack): boolean {
    return compatibleYouTubeCaptionTracks(candidate, track);
}

export function activateYouTubeCaptionTrack(track: YouTubeSubtitleTrack): void {
    if (!isYouTubePage()) return;
    const player = youtubeCaptionPlayer();
    if (!player?.setOption) return;
    try {
        player.loadModule?.('captions');
        setYouTubeCaptionTrack(player, findMatchingYouTubePlayerTrack(track, player) ?? track.youtubeTrack);
        player.setOption('captions', 'reload', true);
    } catch {
        // YouTube's player API is private and best-effort.
    }
}

function youtubeCaptionPlayer(): {
    loadModule?: (name: string) => void;
    setOption?: (module: string, option: string, value: unknown) => void;
    getOption?: (module: string, option: string) => unknown;
    getAudioTrack?: () => { captionTracks?: unknown[] };
} | null {
    return document.querySelector('#movie_player') as {
        loadModule?: (name: string) => void;
        setOption?: (module: string, option: string, value: unknown) => void;
        getOption?: (module: string, option: string) => unknown;
        getAudioTrack?: () => { captionTracks?: unknown[] };
    } | null;
}

function setYouTubeCaptionTrack(player: { setOption?: (module: string, option: string, value: unknown) => void }, candidate: unknown): void {
    if (candidate) player.setOption?.('captions', 'track', candidate);
}

export function getYouTubeVideoId(): string {
    const url = new URL(location.href);
    return url.searchParams.get('v') ?? url.pathname.match(/\/(?:shorts|embed)\/([^/?]+)/)?.[1] ?? '';
}

export function isYouTubePage(): boolean {
    return isYouTubeAppHostname();
}

// Feed hover-preview players (inline previews on home/subscriptions tiles and
// the moving-thumbnail variant). Deterministic container facts, no geometry:
// binding the subtitle controller to these would paint a caption box over a
// hover preview and burn per-hover discovery work.
const YOUTUBE_PREVIEW_CONTAINER_SELECTOR = 'ytd-video-preview, #inline-preview-player, ytd-moving-thumbnail-renderer, ytm-video-preview';

export function isYouTubeFeedPreviewVideo(video: HTMLVideoElement | undefined): boolean {
    return Boolean(video?.closest(YOUTUBE_PREVIEW_CONTAINER_SELECTOR));
}

export function isYouTubeOwnedVideoElement(video: HTMLVideoElement | undefined): boolean {
    if (!isYouTubePage()) return true;
    if (isYouTubeFeedPreviewVideo(video)) return false;
    const currentVideoId = getYouTubeVideoId();
    if (!video || !currentVideoId) return false;
    const player = video.closest<HTMLElement>(YOUTUBE_VIDEO_PLAYER_SELECTOR) as (HTMLElement & { getVideoData?: () => { video_id?: string } }) | null;
    const owner = video.closest<HTMLElement>(YOUTUBE_VIDEO_OWNER_SELECTOR) as (HTMLElement & { getVideoData?: () => { video_id?: string } }) | null;
    const playerVideoId = getYouTubePlayerVideoId(player ?? owner);
    if (playerVideoId && playerVideoId !== currentVideoId) {
        // During SPA navigation the player's private video id briefly lags the
        // URL; the genuine main player element (html5-main-video) is still ours
        // so the rail stays attached. A small stale element parked in the player
        // chrome is not, so it still falls through to the size/visibility check.
        if (video.classList.contains('html5-main-video')) return true;
        return isLikelyVisibleYouTubeWatchVideo(video);
    }
    return Boolean(owner) || isLikelyVisibleYouTubeWatchVideo(video);
}

export function shouldRefreshYouTubeTrackUrl(next: string | undefined, current: string | undefined): boolean {
    if (!next || next === current) return false;
    return youtubeTrackUrlScore(next) >= youtubeTrackUrlScore(current);
}

export function isAutoGeneratedSubtitleTrack(track: YouTubeSubtitleTrack): boolean {
    return track.sourceType === 'asr'
        || track.sourceType === 'translation'
        || Boolean(track.autoGenerated)
        || /asr|auto(?:matic)?|auto-generated|自動生成|自動字幕/i.test(`${track.label} ${track.language ?? ''}`);
}

export function youtubeCaptionTrackIdentity(track: {
    label: string;
    language?: string;
    autoGenerated?: boolean;
    sourceType?: YouTubeCaptionTrackSourceType;
    sourceLanguage?: string;
    targetLanguage?: string;
    vssId?: string;
    youtubeIdentity?: string;
}): string {
    if (track.youtubeIdentity) return track.youtubeIdentity;
    const language = normalizedYouTubeLanguageCode(track.language);
    const sourceType = track.sourceType ?? (track.autoGenerated ? 'asr' : 'manual');
    const sourceLanguage = normalizedYouTubeLanguageCode(track.sourceLanguage) || language;
    const targetLanguage = normalizedYouTubeLanguageCode(track.targetLanguage) || (sourceType === 'translation' ? language : '');
    return [
        sourceType,
        sourceLanguage,
        targetLanguage || language,
        track.vssId ?? '',
        track.vssId ? '' : normalizedYouTubeCaptionLabel(track.label),
    ].join(':');
}

function compatibleYouTubeCaptionTracks(candidate: YouTubeSubtitleTrack, track: YouTubeSubtitleTrack): boolean {
    if (youtubeCaptionTrackIdentity(candidate) === youtubeCaptionTrackIdentity(track)) return true;
    if (hasSpecificYouTubeCaptionIdentity(track)) return false;
    return Boolean(candidate.language && track.language
        && normalizedYouTubeLanguageCode(candidate.language) === normalizedYouTubeLanguageCode(track.language));
}

function hasSpecificYouTubeCaptionIdentity(track: YouTubeSubtitleTrack): boolean {
    return Boolean(track.youtubeIdentity || track.sourceType || track.sourceLanguage || track.targetLanguage || track.vssId);
}

function normalizedYouTubeLanguageCode(language: string | undefined): string {
    return (language ?? '').trim().toLowerCase();
}

function normalizedYouTubeCaptionLabel(label: string): string {
    return label
        .replace(/\s+·\s+auto-generated$/iu, '')
        .replace(/\s+·\s+auto-translated from .+$/iu, '')
        .replace(/\([^)]*\)\s*$/u, '')
        .replace(/\s+/g, ' ')
        .trim()
        .toLowerCase();
}

function getYouTubePlayerCaptionTracks(): unknown[] {
    const player = document.querySelector('#movie_player') as {
        getVideoData?: () => { video_id?: string };
        getAudioTrack?: () => { captionTracks?: unknown[] };
    } | null;
    const videoId = getYouTubeVideoId();
    if (!videoId) return [];
    const playerVideoId = getYouTubePlayerVideoId(player);
    const tracks = player?.getAudioTrack?.()?.captionTracks;
    if (playerVideoId && playerVideoId !== videoId) return [];
    return Array.isArray(tracks) ? tracks.filter(track => youtubeRawCaptionTrackMatchesVideo(track, videoId)) : [];
}

function getYouTubePlayerVideoId(player: { getVideoData?: () => { video_id?: string } } | null): string {
    try {
        return player?.getVideoData?.()?.video_id ?? '';
    } catch {
        return '';
    }
}

function isLikelyVisibleYouTubeWatchVideo(video: HTMLVideoElement): boolean {
    if (!video.isConnected) return false;
    if (video.closest('[data-jpdb-reader-root], [data-yomu-jpdb-addon]')) return false;
    const rect = video.getBoundingClientRect();
    const width = Math.max(rect.width, video.clientWidth);
    const height = Math.max(rect.height, video.clientHeight);
    if (width >= 240 && height >= 135) return true;
    return video.classList.contains('html5-main-video') && (video.readyState >= 1 || width > 0 || height > 0);
}

function uniqueYouTubeCaptionTracks(
    rawTracks: unknown[],
    rawTranslationLanguages: unknown[] | undefined = [],
    preferredTranslationLanguages: readonly string[] = [],
): YouTubeCaptionTrackCandidate[] {
    return uniqueYouTubeCaptionTrackCandidates(youtubeCaptionTracksWithTranslations(
        rawTracks,
        rawTranslationLanguages,
        preferredTranslationLanguages,
    ));
}

function uniqueYouTubeCaptionTrackCandidates(candidates: YouTubeCaptionTrackCandidate[]): YouTubeCaptionTrackCandidate[] {
    const tracks = new Map<string, YouTubeCaptionTrackCandidate>();
    for (const parsed of candidates) {
        const key = youtubeCaptionTrackIdentity(parsed);
        const existing = tracks.get(key);
        if (!existing || shouldRefreshYouTubeTrackUrl(parsed.url, existing.url)) tracks.set(key, parsed);
    }
    return [...tracks.values()];
}

function youtubeCaptionTracksWithTranslations(
    rawTracks: unknown[],
    rawTranslationLanguages: unknown[],
    preferredLanguages: readonly string[],
): YouTubeCaptionTrackCandidate[] {
    const baseTracks = rawTracks
        .map(parseYouTubeCaptionTrack)
        .filter((track): track is YouTubeCaptionTrackCandidate => Boolean(track));
    const translationLanguages = preferredYouTubeTranslationLanguages(rawTranslationLanguages, preferredLanguages);
    if (!translationLanguages.length) return baseTracks;
    return [
        ...baseTracks,
        ...baseTracks.flatMap(track => translationLanguages
            .filter(language => language.code !== normalizedYouTubeLanguageCode(track.language))
            .map(language => translatedYouTubeCaptionTrack(track, language))),
    ];
}

function parseYouTubeCaptionTrack(track: unknown): YouTubeCaptionTrackCandidate | null {
    const record = track as {
        url?: string;
        baseUrl?: string;
        languageCode?: string;
        displayName?: unknown;
        languageName?: unknown;
        kind?: string;
        vssId?: string;
        name?: unknown;
    };
    const url = normalizedYouTubeCaptionUrl(record);
    if (!url) return null;
    const language = record.languageCode;
    const label = youtubeCaptionTrackLabel(record, language);
    const autoGenerated = isAutoGeneratedYouTubeCaptionTrack(record, label);
    const autoSuffix = youtubeCaptionAutoSuffix(autoGenerated, label);
    const sourceType: YouTubeCaptionTrackSourceType = autoGenerated ? 'asr' : 'manual';
    const parsed = {
        label: `${label}${language ? ` (${language})` : ''}${autoSuffix}`,
        language,
        autoGenerated,
        url: url.toString(),
        raw: track,
        sourceType,
        sourceLanguage: language,
        vssId: record.vssId,
    };
    return { ...parsed, youtubeIdentity: youtubeCaptionTrackIdentity(parsed) };
}

interface YouTubeTranslationLanguage {
    code: string;
    label: string;
    raw: unknown;
}

function preferredYouTubeTranslationLanguages(
    rawLanguages: unknown[],
    preferredLanguages: readonly string[],
): YouTubeTranslationLanguage[] {
    const languages = rawLanguages
        .map(parseYouTubeTranslationLanguage)
        .filter((language): language is YouTubeTranslationLanguage => Boolean(language));
    if (!languages.length) return [];
    const byCode = new Map(languages.map(language => [language.code, language]));
    const preferred = uniqueStrings([
        ...preferredLanguages.map(language => normalizedYouTubeLanguageCode(language)),
        'ja',
        'en',
        normalizedYouTubeLanguageCode(readYouTubeConfigString('HL')),
    ]);
    return preferred.flatMap(code => {
        const language = byCode.get(code);
        return language ? [language] : [];
    });
}

function parseYouTubeTranslationLanguage(value: unknown): YouTubeTranslationLanguage | null {
    const record = value as {
        languageCode?: string;
        languageName?: unknown;
        name?: unknown;
    };
    const code = normalizedYouTubeLanguageCode(record.languageCode);
    if (!code) return null;
    return { code, label: firstYouTubeCaptionTrackLabel(record, code) || code, raw: value };
}

function translatedYouTubeCaptionTrack(source: YouTubeCaptionTrackCandidate, language: YouTubeTranslationLanguage): YouTubeCaptionTrackCandidate {
    const url = new URL(source.url, location.href);
    url.searchParams.set('tlang', language.code);
    const sourceLabel = sourceLabelForTranslation(source);
    const label = `${language.label} (${language.code}) · auto-translated from ${sourceLabel}`;
    const translated = {
        label,
        language: language.code,
        autoGenerated: true,
        url: url.toString(),
        raw: {
            source: source.raw,
            translationLanguage: language.raw,
        },
        sourceType: 'translation' as const,
        sourceLanguage: source.language,
        targetLanguage: language.code,
        vssId: `${source.vssId ?? source.language ?? 'source'}>${language.code}`,
    };
    return { ...translated, youtubeIdentity: youtubeCaptionTrackIdentity(translated) };
}

function sourceLabelForTranslation(source: YouTubeCaptionTrackCandidate): string {
    return source.label
        .replace(/\s+·\s+auto-generated$/iu, '')
        .replace(/\([^)]*\)\s*$/u, '')
        .trim()
        || source.language
        || 'source';
}

function normalizedYouTubeCaptionUrl(record: { url?: string; baseUrl?: string; languageCode?: string }): URL | null {
    const rawUrl = rawYouTubeCaptionUrl(record);
    if (!rawUrl) return null;
    const url = new URL(rawUrl, location.href);
    url.searchParams.set('fmt', 'srv3');
    if (record.languageCode && !url.searchParams.has('lang')) url.searchParams.set('lang', record.languageCode);
    applyYouTubeCaptionClientName(url, readYouTubeClientName());
    return url;
}

function rawYouTubeCaptionUrl(record: { url?: string; baseUrl?: string }): string {
    return typeof record.url === 'string' ? record.url : typeof record.baseUrl === 'string' ? record.baseUrl : '';
}

function applyYouTubeCaptionClientName(url: URL, clientName: string): void {
    if (clientName && !url.searchParams.has('c')) url.searchParams.set('c', clientName);
}

async function getAndroidYouTubeCaptionTracks(preferredTranslationLanguages: readonly string[] = []): Promise<YouTubeCaptionTrackCandidate[]> {
    const request = androidYouTubeCaptionRequest();
    if (!request) return [];
    try {
        return await fetchAndroidYouTubeCaptionTracks(request, preferredTranslationLanguages);
    } catch {
        return [];
    }
}

function androidYouTubeCaptionRequest(): AndroidYouTubeCaptionRequest | null {
    const videoId = getYouTubeVideoId();
    const apiKey = readYouTubeConfigString('INNERTUBE_API_KEY');
    if (!videoId || !apiKey) return null;
    return {
        url: `${location.origin}/youtubei/v1/player?key=${encodeURIComponent(apiKey)}`,
        init: {
            method: 'POST',
            credentials: 'include',
            headers: { 'Content-Type': 'application/json' },
            body: androidYouTubeCaptionRequestBody(videoId),
        },
        videoId,
    };
}

async function fetchAndroidYouTubeCaptionTracks(
    request: AndroidYouTubeCaptionRequest,
    preferredTranslationLanguages: readonly string[],
): Promise<YouTubeCaptionTrackCandidate[]> {
    const response = await fetch(request.url, request.init);
    if (!response.ok) return [];
    const payload = await response.json() as YouTubePlayerResponse;
    return androidYouTubeCaptionTracksFromPayload(payload, request.videoId, preferredTranslationLanguages);
}

function androidYouTubeCaptionRequestBody(videoId: string): string {
    return JSON.stringify({
        context: {
            client: {
                clientName: 'ANDROID',
                clientVersion: '20.10.38',
                hl: readYouTubeConfigString('HL') || 'en',
            },
        },
        videoId,
    });
}

function androidYouTubeCaptionTracksFromPayload(
    payload: YouTubePlayerResponse,
    videoId: string,
    preferredTranslationLanguages: readonly string[],
): YouTubeCaptionTrackCandidate[] {
    if (!isMatchingYouTubePlayerResponse(payload, videoId)) return [];
    const renderer = payload.captions?.playerCaptionsTracklistRenderer;
    const rawTracks = renderer?.captionTracks;
    return uniqueYouTubeCaptionTracks(
        Array.isArray(rawTracks) ? rawTracks : [],
        renderer?.translationLanguages,
        preferredTranslationLanguages,
    );
}

function youtubeCaptionTrackLabel(record: {
    displayName?: unknown;
    languageName?: unknown;
    name?: unknown;
}, language?: string): string {
    return firstYouTubeCaptionTrackLabel(record, language) || 'YouTube subtitles';
}

function firstYouTubeCaptionTrackLabel(record: {
    displayName?: unknown;
    languageName?: unknown;
    name?: unknown;
}, language?: string): string {
    return [
        youtubeCaptionText(record.name),
        youtubeCaptionText(record.displayName),
        youtubeCaptionText(record.languageName),
        language,
    ].find((label): label is string => Boolean(label)) ?? '';
}

function youtubeCaptionText(value: unknown): string {
    if (typeof value === 'string') return value;
    if (!value || typeof value !== 'object') return '';
    const record = value as { simpleText?: unknown; runs?: unknown };
    if (typeof record.simpleText === 'string') return record.simpleText;
    if (!Array.isArray(record.runs)) return '';
    return record.runs
        .map(run => typeof run === 'object' && run ? (run as { text?: unknown }).text : '')
        .filter((text): text is string => typeof text === 'string')
        .join('');
}

function youtubeCaptionAutoSuffix(autoGenerated: boolean, label: string): string {
    return autoGenerated && !/asr|auto(?:matic)?|auto-generated|自動生成|自動字幕/i.test(label)
        ? ' · auto-generated'
        : '';
}

function isAutoGeneratedYouTubeCaptionTrack(track: { kind?: string; vssId?: string; languageCode?: string }, label = ''): boolean {
    return youtubeAutoGeneratedSignals(track, label).some(signal => signal.matches(signal.value));
}

function youtubeAutoGeneratedSignals(track: { kind?: string; vssId?: string; languageCode?: string }, label: string): Array<{ value: string; matches: (value: string) => boolean }> {
    return [
        { value: track.kind ?? '', matches: value => /asr/i.test(value) },
        { value: track.vssId ?? '', matches: value => /^a\./i.test(value) },
        { value: `${label} ${track.languageCode ?? ''}`, matches: value => /asr|auto(?:matic)?|auto-generated|自動生成|自動字幕/i.test(value) },
    ];
}

function findMatchingYouTubePlayerTrack(track: YouTubeSubtitleTrack, player: {
    getOption?: (module: string, option: string) => unknown;
    getAudioTrack?: () => { captionTracks?: unknown[] };
}): unknown {
    const rawTracks = [
        ...extractYouTubeTrackArray(player.getAudioTrack?.()?.captionTracks),
        ...extractYouTubeTrackArray(player.getOption?.('captions', 'tracklist')),
    ];
    const targetIdentity = youtubeCaptionTrackIdentity(track);
    const exact = rawTracks.find(raw => {
        const parsed = parseYouTubeCaptionTrack(raw);
        return parsed && youtubeCaptionTrackIdentity(parsed) === targetIdentity;
    });
    if (exact) return exact;
    if (track.sourceType === 'translation') {
        const source = rawTracks.find(raw => {
            const parsed = parseYouTubeCaptionTrack(raw);
            return parsed?.language && track.sourceLanguage && normalizedYouTubeLanguageCode(parsed.language) === normalizedYouTubeLanguageCode(track.sourceLanguage);
        }) ?? youtubePlayerTranslationSource(track);
        return source ? translatedYouTubePlayerTrack(track, source) : null;
    }
    return rawTracks.find(raw => {
        const parsed = parseYouTubeCaptionTrack(raw);
        return parsed?.language && track.language && normalizedYouTubeLanguageCode(parsed.language) === normalizedYouTubeLanguageCode(track.language);
    }) ?? null;
}

function translatedYouTubePlayerTrack(track: YouTubeSubtitleTrack, source: unknown): unknown {
    const translationLanguage = youtubePlayerTranslationLanguage(track);
    if (!translationLanguage) return source;
    if (!isRecord(source)) return track.youtubeTrack ?? source;
    return {
        ...source,
        translationLanguage,
    };
}

function youtubePlayerTranslationLanguage(track: YouTubeSubtitleTrack): unknown {
    const raw = track.youtubeTrack;
    if (isRecord(raw) && raw.translationLanguage) return raw.translationLanguage;
    const languageCode = track.targetLanguage || track.language;
    if (!languageCode) return null;
    return {
        languageCode,
        languageName: { simpleText: languageCode },
    };
}

function youtubePlayerTranslationSource(track: YouTubeSubtitleTrack): unknown {
    const raw = track.youtubeTrack;
    if (!isRecord(raw)) return null;
    return raw.source ?? null;
}


function findPreferredYouTubeCaptionCandidate(track: YouTubeSubtitleTrack): YouTubeCaptionTrackCandidate | null {
    if (track.kind !== 'youtube') return null;
    const renderer = getYouTubePlayerResponse()?.captions?.playerCaptionsTracklistRenderer;
    const candidates = uniqueYouTubeCaptionTracks([
        ...getYouTubePlayerCaptionTracks(),
        ...(renderer?.captionTracks ?? []),
    ], renderer?.translationLanguages, [track.targetLanguage ?? '', track.language ?? '']);
    const targetIdentity = youtubeCaptionTrackIdentity(track);
    return candidates
        .filter(candidate => youtubeCaptionTrackIdentity(candidate) === targetIdentity)
        .sort((a, b) => youtubeTrackUrlScore(b.url) - youtubeTrackUrlScore(a.url))[0] ?? null;
}

function extractYouTubeTrackArray(value: unknown): unknown[] {
    if (Array.isArray(value)) return value;
    const record = value as { captionTracks?: unknown[] } | null;
    return Array.isArray(record?.captionTracks) ? record.captionTracks : [];
}

type YouTubePlayerResponse = {
    videoDetails?: { videoId?: string };
    captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: unknown[]; translationLanguages?: unknown[] } };
};

function getYouTubePlayerResponse(): YouTubePlayerResponse | null {
    const videoId = getYouTubeVideoId();
    if (!videoId) return null;
    const fromWindow = (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse;
    if (isMatchingYouTubePlayerResponse(fromWindow, videoId)) return fromWindow as YouTubePlayerResponse;

    const fromConfig = readYouTubePlayerResponseFromConfig(videoId);
    if (fromConfig) return fromConfig;

    return readYouTubePlayerResponseFromScripts(videoId);
}

function readYouTubePlayerResponseFromScripts(videoId: string): YouTubePlayerResponse | null {
    for (const script of Array.from(document.scripts)) {
        const parsed = readYouTubePlayerResponseFromScript(script.textContent ?? '', videoId);
        if (parsed) return parsed;
    }
    return null;
}

function readYouTubePlayerResponseFromScript(text: string, videoId: string): YouTubePlayerResponse | null {
    return readYouTubeInitialPlayerResponse(text, videoId)
        ?? readEscapedYouTubePlayerResponse(text, videoId);
}

function readYouTubeInitialPlayerResponse(text: string, videoId: string): YouTubePlayerResponse | null {
    for (const marker of ['ytInitialPlayerResponse = ', 'ytInitialPlayerResponse=', 'var ytInitialPlayerResponse = ']) {
        const parsed = parseYouTubePlayerResponseMarker(text, marker, videoId);
        if (parsed) return parsed;
    }
    return null;
}

function parseYouTubePlayerResponseMarker(text: string, marker: string, videoId: string): YouTubePlayerResponse | null {
    const start = text.indexOf(marker);
    if (start < 0) return null;
    const raw = extractJsonObject(text, start + marker.length);
    return raw ? parseMatchingYouTubePlayerResponse(raw, videoId) : null;
}

function readEscapedYouTubePlayerResponse(text: string, videoId: string): YouTubePlayerResponse | null {
    const escaped = text.match(/"playerResponse"\s*:\s*"((?:\\.|[^"\\])+)"/);
    if (!escaped?.[1]) return null;
    try {
        return parseMatchingYouTubePlayerResponse(JSON.parse(`"${escaped[1]}"`), videoId);
    } catch {
        return null;
    }
}

function parseMatchingYouTubePlayerResponse(raw: string, videoId: string): YouTubePlayerResponse | null {
    try {
        const parsed = JSON.parse(raw) as unknown;
        return isMatchingYouTubePlayerResponse(parsed, videoId) ? parsed as YouTubePlayerResponse : null;
    } catch {
        return null;
    }
}

function readYouTubePlayerResponseFromConfig(videoId: string): YouTubePlayerResponse | null {
    const ytcfg = (window as Window & { ytcfg?: { data_?: Record<string, unknown>; get?: (key: string) => unknown } }).ytcfg;
    const candidates = [
        ytcfg?.get?.('PLAYER_RESPONSE'),
        ytcfg?.get?.('PLAYER_VARS'),
        ytcfg?.data_?.PLAYER_RESPONSE,
        ytcfg?.data_?.PLAYER_VARS,
    ];
    for (const candidate of candidates) {
        const response = readYouTubePlayerResponseCandidate(candidate);
        if (isMatchingYouTubePlayerResponse(response, videoId)) return response as YouTubePlayerResponse;
    }
    return null;
}

function readYouTubePlayerResponseCandidate(candidate: unknown): unknown {
    if (!candidate) return null;
    if (typeof candidate === 'string') return parseYouTubePlayerResponseJson(candidate);
    if (typeof candidate === 'object') return readYouTubePlayerResponseObject(candidate);
    return null;
}

function parseYouTubePlayerResponseJson(candidate: string): unknown {
    try {
        return JSON.parse(candidate);
    } catch {
        return null;
    }
}

function readYouTubePlayerResponseObject(candidate: object): unknown {
    const record = candidate as { player_response?: unknown; raw_player_response?: unknown };
    return readYouTubePlayerResponseCandidate(record.player_response ?? record.raw_player_response) ?? candidate;
}

function isMatchingYouTubePlayerResponse(value: unknown, videoId: string): boolean {
    const response = youtubePlayerResponseRecord(value);
    return Boolean(response && hasYouTubeCaptionTracks(response) && youtubePlayerResponseMatchesVideo(response, videoId));
}

function youtubePlayerResponseRecord(value: unknown): YouTubePlayerResponse | null {
    return value && typeof value === 'object' ? value as YouTubePlayerResponse : null;
}

function hasYouTubeCaptionTracks(response: YouTubePlayerResponse): boolean {
    return Boolean(response.captions?.playerCaptionsTracklistRenderer?.captionTracks);
}

function youtubePlayerResponseMatchesVideo(response: YouTubePlayerResponse, videoId: string): boolean {
    if (!videoId) return false;
    const responseVideoId = response.videoDetails?.videoId;
    if (responseVideoId) return responseVideoId === videoId;
    return youtubePlayerResponseCaptionUrlsMatchVideo(response, videoId);
}

function youtubePlayerResponseCaptionUrlsMatchVideo(response: YouTubePlayerResponse, videoId: string): boolean {
    const tracks = response.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    return Array.isArray(tracks) && tracks.some(track => youtubeRawCaptionTrackMatchesVideo(track, videoId));
}

function youtubeRawCaptionTrackMatchesVideo(track: unknown, videoId: string): boolean {
    try {
        const rawUrl = rawYouTubeCaptionUrl(track as { url?: string; baseUrl?: string });
        if (!rawUrl) return false;
        return new URL(rawUrl, location.href).searchParams.get('v') === videoId;
    } catch {
        return false;
    }
}

function extractJsonObject(text: string, start: number): string | null {
    const objectStart = text.indexOf('{', start);
    if (objectStart < 0) return null;

    const state = createJsonObjectScanState();
    for (let index = objectStart; index < text.length; index++) {
        if (scanJsonObjectCharacter(state, text[index])) return text.slice(objectStart, index + 1);
    }
    return null;
}

interface JsonObjectScanState {
    depth: number;
    inString: boolean;
    escaped: boolean;
}

function createJsonObjectScanState(): JsonObjectScanState {
    return { depth: 0, inString: false, escaped: false };
}

function scanJsonObjectCharacter(state: JsonObjectScanState, char: string): boolean {
    if (state.inString) {
        scanJsonStringCharacter(state, char);
        return false;
    }
    if (char === '"') {
        state.inString = true;
        return false;
    }
    if (char === '{') state.depth += 1;
    if (char !== '}') return false;
    state.depth -= 1;
    return state.depth === 0;
}

function scanJsonStringCharacter(state: JsonObjectScanState, char: string): void {
    if (state.escaped) {
        state.escaped = false;
        return;
    }
    if (char === '\\') state.escaped = true;
    if (char === '"') state.inString = false;
}

function youtubeSubtitleRequestUrls(url: string): string[] {
    return uniqueStrings([
        withYouTubeSubtitleFormat(url, 'srv3'),
        withYouTubeSubtitleFormat(url, 'json3'),
        withYouTubeSubtitleFormat(url, 'vtt'),
        url,
    ]);
}

function withYouTubeSubtitleFormat(url: string, format: 'srv3' | 'vtt' | 'json3'): string {
    const parsed = new URL(url);
    parsed.searchParams.set('fmt', format);
    const clientName = readYouTubeClientName();
    if (clientName && !parsed.searchParams.has('c')) parsed.searchParams.set('c', clientName);
    return parsed.href;
}

function readYouTubeClientName(): string {
    return readYouTubeConfigString('INNERTUBE_CLIENT_NAME');
}

function readYouTubeConfigString(key: string): string {
    const ytcfg = (window as Window & { ytcfg?: { data_?: Record<string, unknown>; get?: (key: string) => unknown } }).ytcfg;
    const value = ytcfg?.get?.(key) ?? ytcfg?.data_?.[key];
    if (typeof value === 'string' && value) return value;
    return readYouTubeConfigStringFromScripts(key);
}

function youtubeTrackUrlScore(value: string | undefined): number {
    if (!value) return 0;
    try {
        const url = new URL(value, location.href);
        return youtubeTrackSearchParamScore(url.searchParams);
    } catch {
        return 0;
    }
}

function youtubeTrackSearchParamScore(params: URLSearchParams): number {
    return [
        params.has('pot') ? 8 : 0,
        params.has('potc') ? 4 : 0,
        params.has('signature') ? 2 : 0,
        params.has('kind') ? 1 : 0,
    ].reduce((sum, item) => sum + item, 0);
}
