import { uiText } from '../app/i18n';
import { isTargetSubtitleLanguage } from '../languages/resolve';
import type { SubtitleCue } from './subtitle-cues';
import { inferSubtitleLanguage, normalizeSubtitleLanguage } from './subtitle-language';
import { isAutoGeneratedSubtitleTrack } from './subtitle-youtube';
import type { InterfaceLanguage } from '../app/types';

export type SubtitleTrackKind = 'native' | 'file' | 'youtube' | 'remote';
export type SubtitleTrackLoadingState = 'idle' | 'loading' | 'ready' | 'waiting' | 'error';

export interface SubtitleTrackMetadata {
    label: string;
    kind: SubtitleTrackKind;
    language?: string;
    autoGenerated?: boolean;
    loadingState?: SubtitleTrackLoadingState;
    sourceLanguage?: string;
    targetLanguage?: string;
}

export function trackStatusText(track: SubtitleTrackMetadata, language: InterfaceLanguage = 'en'): string {
    if (track.loadingState === 'loading') return ` · ${uiText(language, 'trackStatusLoading')}`;
    if (track.loadingState === 'waiting') return ` · ${uiText(language, 'trackStatusWaiting')}`;
    if (track.loadingState === 'error') return ` · ${uiText(language, 'trackStatusFailed')}`;
    return '';
}

export function formatTrackKind(kind: SubtitleTrackKind, language: InterfaceLanguage = 'en'): string {
    if (kind === 'native') return uiText(language, 'trackKindPageTrack');
    if (kind === 'remote') return uiText(language, 'trackKindPageFile');
    if (kind === 'youtube') return uiText(language, 'trackKindYouTubeCaptions');
    return uiText(language, 'trackKindLoadedFile');
}

export function compareSubtitleTrackOptions<T extends SubtitleTrackMetadata>(a: T, b: T): number {
    return subtitleTrackRank(a) - subtitleTrackRank(b)
        || (a.language ?? '').localeCompare(b.language ?? '', undefined, { sensitivity: 'base' })
        || a.label.localeCompare(b.label, undefined, { sensitivity: 'base' });
}

/** Subtitle capability: "is this track in the language we are teaching?" */
export function isTargetLanguageSubtitleTrack(track: SubtitleTrackMetadata): boolean {
    const language = subtitleTrackLanguage(track);
    if (language) return isTargetSubtitleLanguage(language);
    return isTargetSubtitleLanguage(inferSubtitleLanguage(track.label, track.language));
}

export function isEnglishSubtitleTrack(track: SubtitleTrackMetadata): boolean {
    return isSubtitleTrackLanguage(track, 'en');
}

/** Metadata owns semantic language; visible labels are only its cue-aware fallback. */
export function subtitleTrackLanguage(track: SubtitleTrackMetadata | undefined): string | undefined {
    if (!track) return undefined;
    const language = track.targetLanguage ?? track.language;
    if (isLanguageCode(language)) return normalizeSubtitleLanguage(language);
    return inferSubtitleLanguage(track.label, track.language);
}

export function isSubtitleTrackLanguage(track: SubtitleTrackMetadata, expectedLanguage: string): boolean {
    const expected = normalizeSubtitleLanguage(expectedLanguage);
    return Boolean(expected && subtitleTrackLanguage(track) === expected);
}

/** A language-less “native/translation” label means the learner's OUTPUT axis. */
export function isOutputLanguageSubtitleTrack(track: SubtitleTrackMetadata, outputLanguage: string): boolean {
    return isSubtitleTrackLanguage(track, outputLanguage)
        || (!subtitleTrackLanguage(track) && isGenericOutputSubtitleLabel(track.label));
}

export function shouldReplaceWaitingNativeTrack(
    selected: SubtitleTrackMetadata | undefined,
    replacement: SubtitleTrackMetadata,
    cues: SubtitleCue[],
    expectedLanguage?: string,
    expectedRole: 'target' | 'output' = 'target',
): boolean {
    if (!isWaitingNativeTrack(selected, cues)) return false;
    return expectedLanguage
        ? tracksHaveLanguage(selected, replacement, expectedLanguage, expectedRole)
        : tracksHaveSameRoleOrLanguage(selected, replacement);
}

function tracksHaveLanguage(
    selected: SubtitleTrackMetadata,
    replacement: SubtitleTrackMetadata,
    language: string,
    role: 'target' | 'output',
): boolean {
    const matches = role === 'output' ? isOutputLanguageSubtitleTrack : isSubtitleTrackLanguage;
    return matches(selected, language) && matches(replacement, language);
}

function tracksHaveSameRoleOrLanguage(selected: SubtitleTrackMetadata, replacement: SubtitleTrackMetadata): boolean {
    return hasSameSubtitleRole(selected, replacement) || hasSameNormalizedSubtitleLanguage(selected, replacement);
}

function isWaitingNativeTrack(
    selected: SubtitleTrackMetadata | undefined,
    cues: SubtitleCue[],
): selected is SubtitleTrackMetadata {
    return Boolean(selected && selected.kind === 'native' && !cues.length);
}

function hasSameSubtitleRole(selected: SubtitleTrackMetadata, replacement: SubtitleTrackMetadata): boolean {
    return (isTargetLanguageSubtitleTrack(selected) && isTargetLanguageSubtitleTrack(replacement))
        || (isEnglishSubtitleTrack(selected) && isEnglishSubtitleTrack(replacement));
}

function hasSameNormalizedSubtitleLanguage(selected: SubtitleTrackMetadata, replacement: SubtitleTrackMetadata): boolean {
    const selectedLanguage = normalizeSubtitleLanguage(selected.language);
    const replacementLanguage = normalizeSubtitleLanguage(replacement.language);
    return Boolean(selectedLanguage && replacementLanguage && selectedLanguage === replacementLanguage);
}

function isLanguageCode(language: string | undefined): boolean {
    return Boolean(language?.trim().match(/^[a-z]{2,3}(?:[-_][a-z0-9]{2,8})*$/i));
}

function isGenericOutputSubtitleLabel(label: string): boolean {
    return /(^|[.\-_\s()[\]])(?:native|translation|translated)(?=$|[.\-_\s()[\]])/iu.test(label);
}

function subtitleTrackRank(track: SubtitleTrackMetadata): number {
    return SUBTITLE_TRACK_RANKS.find(rule => rule.matches(track))?.rank ?? 5;
}

interface SubtitleTrackRankRule {
    rank: number;
    matches: (track: SubtitleTrackMetadata) => boolean;
}

const SUBTITLE_TRACK_RANKS: SubtitleTrackRankRule[] = [
    { rank: 0, matches: track => track.kind === 'file' },
    { rank: 1, matches: isManualTargetLanguageSubtitleTrack },
    { rank: 2, matches: isTargetLanguageSubtitleTrack },
    { rank: 3, matches: isAutoGeneratedSubtitleTrack },
    { rank: 4, matches: isEnglishOrNativeSubtitleTrack },
];

function isManualTargetLanguageSubtitleTrack(track: SubtitleTrackMetadata): boolean {
    return isTargetLanguageSubtitleTrack(track) && !isAutoGeneratedSubtitleTrack(track);
}

function isEnglishOrNativeSubtitleTrack(track: SubtitleTrackMetadata): boolean {
    return isEnglishSubtitleTrack(track) || track.kind === 'native';
}
