import type { SubtitleCue } from './subtitle-cues';
import { normalizedSubtitleUrl, type PageSubtitleSource } from './subtitle-sources';
import {
    compareSubtitleTrackOptions,
    type SubtitleTrackKind,
    type SubtitleTrackLoadingState,
} from './subtitle-track-metadata';
import { isAutoGeneratedSubtitleTrack, type YouTubeCaptionTrackSourceType } from './subtitle-youtube';

export interface SubtitleTrackOption {
    id: string;
    label: string;
    kind: SubtitleTrackKind;
    language?: string;
    autoGenerated?: boolean;
    track?: TextTrack;
    cues?: SubtitleCue[];
    url?: string;
    youtubeTrack?: unknown;
    sourceType?: YouTubeCaptionTrackSourceType;
    sourceLanguage?: string;
    targetLanguage?: string;
    vssId?: string;
    youtubeIdentity?: string;
    sourceKey?: string;
    loadingState?: SubtitleTrackLoadingState;
}

export interface LoadedSubtitleTrackSelection {
    track: SubtitleTrackOption | undefined;
    trackId: string;
    cues: SubtitleCue[];
}

export type SubtitleTrackSelectionRole = 'primary' | 'secondary';

export interface SubtitleTrackSelectionLoadRequest {
    id: string;
    requestId: number;
    role: SubtitleTrackSelectionRole;
    transcriptEligible: boolean;
}

export function updatePageSubtitleTrack(track: SubtitleTrackOption, source: PageSubtitleSource): boolean {
    if (track.label === source.label && track.language === source.language && track.sourceKey === source.sourceKey) return false;
    track.label = source.label;
    track.language = source.language;
    track.sourceKey = source.sourceKey;
    return true;
}

export function isStalePageSubtitleTrack(
    track: SubtitleTrackOption,
    sourceKeys: ReadonlySet<string>,
    sourceUrls: ReadonlySet<string>,
): boolean {
    return track.kind === 'remote'
        && !sourceKeys.has(track.sourceKey ?? '')
        && !hasCurrentPageSubtitleTrackUrl(track, sourceUrls);
}

function hasCurrentPageSubtitleTrackUrl(track: SubtitleTrackOption, sourceUrls: ReadonlySet<string>): boolean {
    return Boolean(track.url && sourceUrls.has(normalizedSubtitleUrl(track.url)));
}

export function compareNativeOverlaySubtitleTrackOptions(a: SubtitleTrackOption, b: SubtitleTrackOption): number {
    return Number(isAutoGeneratedSubtitleTrack(a)) - Number(isAutoGeneratedSubtitleTrack(b))
        || compareSubtitleTrackOptions(a, b);
}

export function loadedTrackState(cues: SubtitleCue[]): SubtitleTrackLoadingState {
    return cues.length ? 'ready' : 'waiting';
}
