import { uiText } from '../app/i18n';
import type { InterfaceLanguage } from '../app/types';
import { isNonNullObject as isRecord } from '../core/object-utils';
import { googleTranslationLanguageCapability } from '../translation/google';
import type { SubtitleCue } from './subtitle-cues';
import type { SubtitleLanguageSelection } from './subtitle-language-context';
import type { PageSubtitleSource } from './subtitle-sources';
import {
    compareSubtitleTrackOptions,
    isOutputLanguageSubtitleTrack,
    isSubtitleTrackLanguage,
    subtitleTrackLanguage,
    shouldReplaceWaitingNativeTrack,
} from './subtitle-track-metadata';
import {
    compareNativeOverlaySubtitleTrackOptions,
    type SubtitleTrackOption,
} from './subtitle-track-options';

export interface HostedSubtitleFileJob {
    kind: 'primary' | 'secondary';
    file: File;
}

export interface HostedSubtitleFileLoadRequest {
    jobs: HostedSubtitleFileJob[];
    openPanel?: 'auto' | 'lines' | 'tracks' | false;
}

interface PageTrackSelectionState {
    selectedTrackId: string;
    secondaryTrackId: string;
    selected: SubtitleTrackOption | undefined;
    secondary: SubtitleTrackOption | undefined;
    cues: SubtitleCue[];
    secondaryCues: SubtitleCue[];
}

export function subtitleFilesFromHostEvent(event: Event, languages: SubtitleLanguageSelection): HostedSubtitleFileLoadRequest {
    const rawDetail = event instanceof CustomEvent ? event.detail : undefined;
    const detail = isRecord(rawDetail) ? rawDetail : {};
    const explicitJobs = [
        ...hostedSubtitleFileJobs('primary', detail.primary ?? detail.primaryFiles),
        ...hostedSubtitleFileJobs('secondary', detail.secondary ?? detail.secondaryFiles),
    ];
    return {
        jobs: explicitJobs.length ? explicitJobs : inferHostedSubtitleFileJobs(hostedFiles(detail.files), languages),
        openPanel: normalizeHostedSubtitleOpenPanel(detail.openPanel),
    };
}

export function readHostedSubtitleFileText(file: File): Promise<string> {
    if (typeof file.text === 'function') return file.text();
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.addEventListener('load', () => resolve(String(reader.result ?? '')), { once: true });
        reader.addEventListener('error', () => reject(reader.error ?? new Error('Could not read subtitle file.')), { once: true });
        reader.readAsText(file);
    });
}

export function subtitleFilePickerJobs(
    kind: 'primary' | 'secondary',
    files: File[],
    languages: SubtitleLanguageSelection,
): HostedSubtitleFileJob[] {
    if (files.length <= 1 || kind === 'secondary') return files.map(file => ({ kind, file }));
    return inferHostedSubtitleFileJobs(files, languages);
}

export function createPageSubtitleTrack(source: PageSubtitleSource, index: number): SubtitleTrackOption {
    return {
        id: `remote-${index}`,
        label: source.label,
        kind: 'remote',
        language: source.language,
        url: source.url,
        sourceKey: source.sourceKey,
    };
}

/** Add one machine-translated TARGET option from the best known source track. */
export function ensureTranslatedTargetTrack(
    tracks: SubtitleTrackOption[],
    interfaceLanguage: InterfaceLanguage,
    languages: SubtitleLanguageSelection,
): boolean {
    const source = targetTranslationSource(tracks, languages);
    if (!source) return false;
    tracks.push({
        id: `translated-${languages.targetLanguage}-${source.track.id}`,
        label: `${uiText(interfaceLanguage, 'translation')} (${source.track.label})`,
        kind: source.track.kind,
        language: languages.targetLanguage,
        autoGenerated: true,
        translatedFromTrackId: source.track.id,
        sourceLanguage: source.language,
        targetLanguage: languages.targetLanguage,
    });
    return true;
}

interface SubtitleTranslationSource {
    track: SubtitleTrackOption;
    language: string;
}

function targetTranslationSource(
    tracks: SubtitleTrackOption[],
    languages: SubtitleLanguageSelection,
): SubtitleTranslationSource | undefined {
    if (!translationTargetAvailable(tracks, languages.targetLanguage)) return undefined;
    return tracks.flatMap(track => {
        const language = translationSourceLanguage(track, languages);
        return language ? [{ track, language }] : [];
    }).sort((left, right) => compareTranslationSources(left, right, languages.outputLanguage))[0];
}

function translationTargetAvailable(tracks: SubtitleTrackOption[], targetLanguage: string): boolean {
    return !tracks.some(track => isSubtitleTrackLanguage(track, targetLanguage))
        && googleTranslationLanguageCapability(targetLanguage).supported;
}

function translationSourceLanguage(
    track: SubtitleTrackOption,
    languages: SubtitleLanguageSelection,
): string | undefined {
    const language = resolvedTranslationSourceLanguage(track, languages.outputLanguage);
    if (!language) return undefined;
    if (translationSourceMatchesTarget(language, languages.targetLanguage)) return undefined;
    return supportedTranslationSourceLanguage(language);
}

function resolvedTranslationSourceLanguage(track: SubtitleTrackOption, outputLanguage: string): string | undefined {
    const explicit = subtitleTrackLanguage(track);
    if (explicit) return explicit;
    return isOutputLanguageSubtitleTrack(track, outputLanguage) ? outputLanguage : undefined;
}

function translationSourceMatchesTarget(sourceLanguage: string, targetLanguage: string): boolean {
    return isSubtitleTrackLanguage({ label: '', kind: 'remote', language: sourceLanguage }, targetLanguage);
}

function supportedTranslationSourceLanguage(language: string): string | undefined {
    const capability = googleTranslationLanguageCapability(language);
    return capability.supported ? capability.logicalLanguage : undefined;
}

function compareTranslationSources(
    left: SubtitleTranslationSource,
    right: SubtitleTranslationSource,
    outputLanguage: string,
): number {
    return Number(right.language === outputLanguage) - Number(left.language === outputLanguage)
        || Number(right.language === 'en') - Number(left.language === 'en')
        || compareSubtitleTrackOptions(left.track, right.track);
}

function isSyntheticTranslatedSelection(tracks: SubtitleTrackOption[], selectedTrackId: string): boolean {
    return Boolean(selectedTrackId && tracks.find(track => track.id === selectedTrackId)?.translatedFromTrackId);
}

export function autoSelectablePageTrackRole(
    option: SubtitleTrackOption,
    state: PageTrackSelectionState,
    languages: SubtitleLanguageSelection,
): 'primary' | 'secondary' | null {
    if (isSubtitleTrackLanguage(option, languages.targetLanguage)
        && (!state.selectedTrackId
            || Boolean(state.selected?.translatedFromTrackId)
            || shouldReplaceWaitingNativeTrack(state.selected, option, state.cues, languages.targetLanguage))) return 'primary';
    if (languages.outputLanguage !== languages.targetLanguage
        && isOutputLanguageSubtitleTrack(option, languages.outputLanguage)
        && (!state.secondaryTrackId
            || shouldReplaceWaitingNativeTrack(state.secondary, option, state.secondaryCues, languages.outputLanguage, 'output'))) return 'secondary';
    return null;
}

export function autoSelectableNativeTrackRole(
    option: SubtitleTrackOption,
    tracks: SubtitleTrackOption[],
    selectedTrackId: string,
    secondaryTrackId: string,
    languages: SubtitleLanguageSelection,
): 'primary' | 'secondary' | null {
    if (isSubtitleTrackLanguage(option, languages.targetLanguage)
        && (!selectedTrackId || isSyntheticTranslatedSelection(tracks, selectedTrackId))) return 'primary';
    return !secondaryTrackId
        && languages.outputLanguage !== languages.targetLanguage
        && isOutputLanguageSubtitleTrack(option, languages.outputLanguage) ? 'secondary' : null;
}

export function findAutoPrimaryYouTubeTrack(
    tracks: SubtitleTrackOption[],
    selectedTrackId: string,
    autoSelectSuppressedVideoId: string,
    videoId: string,
    languages: SubtitleLanguageSelection,
): SubtitleTrackOption | undefined {
    // A synthetic translated selection stays replaceable by a real target track.
    if (selectedTrackId && !isSyntheticTranslatedSelection(tracks, selectedTrackId)) return undefined;
    if (autoSelectSuppressedVideoId && autoSelectSuppressedVideoId === videoId) return undefined;
    const candidate = [...tracks]
        .filter(track => track.kind === 'youtube' && isSubtitleTrackLanguage(track, languages.targetLanguage))
        .sort((a, b) => Number(Boolean(a.translatedFromTrackId)) - Number(Boolean(b.translatedFromTrackId))
            || compareSubtitleTrackOptions(a, b))[0];
    return candidate?.id === selectedTrackId ? undefined : candidate;
}

export function findAutoSecondaryYouTubeTrack(
    tracks: SubtitleTrackOption[],
    primaryTrackId: string,
    secondaryTrackId: string,
    languages: SubtitleLanguageSelection,
): SubtitleTrackOption | undefined {
    if (!primaryTrackId || secondaryTrackId || languages.outputLanguage === languages.targetLanguage) return undefined;
    return [...tracks]
        .filter(track => track.kind === 'youtube'
            && track.id !== primaryTrackId
            && isOutputLanguageSubtitleTrack(track, languages.outputLanguage))
        .sort(compareNativeOverlaySubtitleTrackOptions)[0];
}

export interface YouTubeTrackDiscoverySelection {
    role: 'primary' | 'secondary';
    trackId: string;
}

export interface YouTubeTrackDiscoveryPlan {
    selections: YouTubeTrackDiscoverySelection[];
    refreshPanel: boolean;
}

export function planYouTubeTrackDiscovery(options: {
    tracks: SubtitleTrackOption[];
    selectedTrackId: string;
    secondaryTrackId: string;
    autoSelectSuppressedVideoId: string;
    videoId: string;
    languages: SubtitleLanguageSelection;
    updatedSelectedTrack: boolean;
    tracksChanged: boolean;
}): YouTubeTrackDiscoveryPlan {
    const primary = findAutoPrimaryYouTubeTrack(
        options.tracks,
        options.selectedTrackId,
        options.autoSelectSuppressedVideoId,
        options.videoId,
        options.languages,
    );
    const primaryTrackId = rediscoveredPrimaryTrackId(primary, options);
    const secondary = findAutoSecondaryYouTubeTrack(
        options.tracks,
        selectedPrimaryTrackId(primary, options.selectedTrackId),
        options.secondaryTrackId,
        options.languages,
    );
    const selections = youtubeTrackDiscoverySelections(primaryTrackId, optionalSubtitleTrackId(secondary));
    return {
        selections,
        refreshPanel: shouldRefreshYouTubeTrackPanel(selections, options.tracksChanged),
    };
}

function selectedPrimaryTrackId(primary: SubtitleTrackOption | undefined, selectedTrackId: string): string {
    return primary ? primary.id : selectedTrackId;
}

function optionalSubtitleTrackId(track: SubtitleTrackOption | undefined): string {
    return track ? track.id : '';
}

function rediscoveredPrimaryTrackId(
    primary: SubtitleTrackOption | undefined,
    options: Pick<YouTubeTrackDiscoveryPlanOptions, 'updatedSelectedTrack' | 'selectedTrackId'>,
): string {
    if (primary) return primary.id;
    if (options.updatedSelectedTrack) return options.selectedTrackId;
    return '';
}

type YouTubeTrackDiscoveryPlanOptions = Parameters<typeof planYouTubeTrackDiscovery>[0];

function youtubeTrackDiscoverySelections(primaryTrackId: string, secondaryTrackId: string): YouTubeTrackDiscoverySelection[] {
    const selections: YouTubeTrackDiscoverySelection[] = [];
    if (primaryTrackId) selections.push({ role: 'primary', trackId: primaryTrackId });
    if (secondaryTrackId) selections.push({ role: 'secondary', trackId: secondaryTrackId });
    return selections;
}

function shouldRefreshYouTubeTrackPanel(
    selections: YouTubeTrackDiscoverySelection[],
    tracksChanged: boolean,
): boolean {
    return selections.length === 0 && tracksChanged;
}

function hostedSubtitleFileJobs(kind: 'primary' | 'secondary', value: unknown): HostedSubtitleFileJob[] {
    return hostedFiles(value).map(file => ({ kind, file }));
}

function hostedFiles(value: unknown): File[] {
    if (isHostedFile(value)) return [value];
    if (!value || typeof value !== 'object') return [];
    if (typeof (value as { length?: unknown }).length === 'number') {
        return Array.from(value as ArrayLike<unknown>).filter(isHostedFile);
    }
    if (Symbol.iterator in value) return Array.from(value as Iterable<unknown>).filter(isHostedFile);
    return [];
}

function isHostedFile(value: unknown): value is File {
    if (typeof File !== 'undefined' && value instanceof File) return true;
    return Boolean(value
        && typeof value === 'object'
        && typeof (value as File).name === 'string'
        && typeof (value as Blob).slice === 'function');
}

function inferHostedSubtitleFileJobs(files: File[], languages: SubtitleLanguageSelection): HostedSubtitleFileJob[] {
    const subtitleFiles = files.filter(file => /\.(?:srt|vtt|ass|ssa)$/iu.test(file.name));
    if (!subtitleFiles.length) return [];
    const primary = subtitleFiles.filter(file => isSubtitleTrackLanguage({ label: file.name, kind: 'file' }, languages.targetLanguage));
    const secondary = subtitleFiles.filter(file => !primary.includes(file)
        && isTranslationSubtitleFile(file.name, languages.outputLanguage));
    const fallback = subtitleFiles.filter(file => !primary.includes(file) && !secondary.includes(file));
    const selected = primary.shift() ?? fallback.shift() ?? secondary.shift();
    return selected ? [
        { kind: 'primary', file: selected },
        ...[...primary, ...fallback, ...secondary].map(file => ({ kind: 'secondary' as const, file })),
    ] : [];
}

function isTranslationSubtitleFile(name: string, outputLanguage: string): boolean {
    return isOutputLanguageSubtitleTrack({ label: name, kind: 'file' }, outputLanguage);
}

function normalizeHostedSubtitleOpenPanel(value: unknown): HostedSubtitleFileLoadRequest['openPanel'] {
    return value === 'lines' || value === 'tracks' || value === 'auto' || value === false ? value : 'auto';
}
