import { uiText } from '../app/i18n';
import type { InterfaceLanguage } from '../app/types';
import { isNonNullObject as isRecord } from '../core/object-utils';
import type { SubtitleCue } from './subtitle-cues';
import type { PageSubtitleSource } from './subtitle-sources';
import {
    compareSubtitleTrackOptions,
    isEnglishSubtitleTrack,
    isJapaneseSubtitleTrack,
    shouldReplaceWaitingNativeTrack,
} from './subtitle-track-metadata';
import {
    compareNativeOverlaySubtitleTrackOptions,
    type SubtitleTrackOption,
} from './subtitle-track-options';

export interface HostedSubtitleFileJob {
    kind: 'primary' | 'secondary';
    file: File;
}

export interface HostedSubtitleFileLoadRequest {
    jobs: HostedSubtitleFileJob[];
    openPanel?: 'auto' | 'lines' | 'tracks' | false;
}

interface PageTrackSelectionState {
    selectedTrackId: string;
    secondaryTrackId: string;
    selected: SubtitleTrackOption | undefined;
    secondary: SubtitleTrackOption | undefined;
    cues: SubtitleCue[];
    secondaryCues: SubtitleCue[];
}

export function subtitleFilesFromHostEvent(event: Event): HostedSubtitleFileLoadRequest {
    const rawDetail = event instanceof CustomEvent ? event.detail : undefined;
    const detail = isRecord(rawDetail) ? rawDetail : {};
    const explicitJobs = [
        ...hostedSubtitleFileJobs('primary', detail.primary ?? detail.primaryFiles),
        ...hostedSubtitleFileJobs('secondary', detail.secondary ?? detail.secondaryFiles),
    ];
    return {
        jobs: explicitJobs.length ? explicitJobs : inferHostedSubtitleFileJobs(hostedFiles(detail.files)),
        openPanel: normalizeHostedSubtitleOpenPanel(detail.openPanel),
    };
}

export function readHostedSubtitleFileText(file: File): Promise<string> {
    if (typeof file.text === 'function') return file.text();
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(String(reader.result ?? ''));
        reader.onerror = () => reject(reader.error ?? new Error('Could not read subtitle file.'));
        reader.readAsText(file);
    });
}

export function subtitleFilePickerJobs(kind: 'primary' | 'secondary', files: File[]): HostedSubtitleFileJob[] {
    if (files.length <= 1 || kind === 'secondary') return files.map(file => ({ kind, file }));
    return inferHostedSubtitleFileJobs(files);
}

export function createPageSubtitleTrack(source: PageSubtitleSource, index: number): SubtitleTrackOption {
    return {
        id: `remote-${index}`,
        label: source.label,
        kind: 'remote',
        language: source.language,
        url: source.url,
        sourceKey: source.sourceKey,
    };
}

/** Add the one machine-translated Japanese option an English-only track list needs. */
export function ensureTranslatedJapaneseTrack(
    tracks: SubtitleTrackOption[],
    interfaceLanguage: InterfaceLanguage,
): boolean {
    if (tracks.some(track => isJapaneseSubtitleTrack(track))) return false;
    const source = tracks.filter(track => isEnglishSubtitleTrack(track)).sort(compareSubtitleTrackOptions)[0];
    if (!source || tracks.some(track => track.translatedFromTrackId === source.id)) return false;
    tracks.push({
        id: `translated-${source.id}`,
        label: `${uiText(interfaceLanguage, 'translation')} (${source.label})`,
        kind: source.kind,
        language: 'ja',
        autoGenerated: true,
        translatedFromTrackId: source.id,
    });
    return true;
}

function isSyntheticTranslatedSelection(tracks: SubtitleTrackOption[], selectedTrackId: string): boolean {
    return Boolean(selectedTrackId && tracks.find(track => track.id === selectedTrackId)?.translatedFromTrackId);
}

export function autoSelectablePageTrackRole(
    option: SubtitleTrackOption,
    state: PageTrackSelectionState,
): 'primary' | 'secondary' | null {
    if (isJapaneseSubtitleTrack(option)
        && (!state.selectedTrackId
            || Boolean(state.selected?.translatedFromTrackId)
            || shouldReplaceWaitingNativeTrack(state.selected, option, state.cues))) return 'primary';
    if (isEnglishSubtitleTrack(option)
        && (!state.secondaryTrackId
            || shouldReplaceWaitingNativeTrack(state.secondary, option, state.secondaryCues))) return 'secondary';
    return null;
}

export function autoSelectableNativeTrackRole(
    option: SubtitleTrackOption,
    tracks: SubtitleTrackOption[],
    selectedTrackId: string,
    secondaryTrackId: string,
): 'primary' | 'secondary' | null {
    if (isJapaneseSubtitleTrack(option)
        && (!selectedTrackId || isSyntheticTranslatedSelection(tracks, selectedTrackId))) return 'primary';
    return !secondaryTrackId && isEnglishSubtitleTrack(option) ? 'secondary' : null;
}

export function findAutoPrimaryYouTubeTrack(
    tracks: SubtitleTrackOption[],
    selectedTrackId: string,
    autoSelectSuppressedVideoId: string,
    videoId: string,
): SubtitleTrackOption | undefined {
    // A synthetic translated selection stays replaceable by a real target track.
    if (selectedTrackId && !isSyntheticTranslatedSelection(tracks, selectedTrackId)) return undefined;
    if (autoSelectSuppressedVideoId && autoSelectSuppressedVideoId === videoId) return undefined;
    const candidate = [...tracks]
        .filter(track => track.kind === 'youtube' && isJapaneseSubtitleTrack(track))
        .sort((a, b) => Number(Boolean(a.translatedFromTrackId)) - Number(Boolean(b.translatedFromTrackId))
            || compareSubtitleTrackOptions(a, b))[0];
    return candidate?.id === selectedTrackId ? undefined : candidate;
}

export function findAutoSecondaryYouTubeTrack(
    tracks: SubtitleTrackOption[],
    primaryTrackId: string,
    secondaryTrackId: string,
): SubtitleTrackOption | undefined {
    if (!primaryTrackId || secondaryTrackId) return undefined;
    return [...tracks]
        .filter(track => track.kind === 'youtube' && track.id !== primaryTrackId && isEnglishSubtitleTrack(track))
        .sort(compareNativeOverlaySubtitleTrackOptions)[0];
}

function hostedSubtitleFileJobs(kind: 'primary' | 'secondary', value: unknown): HostedSubtitleFileJob[] {
    return hostedFiles(value).map(file => ({ kind, file }));
}

function hostedFiles(value: unknown): File[] {
    if (isHostedFile(value)) return [value];
    if (!value || typeof value !== 'object') return [];
    if (typeof (value as { length?: unknown }).length === 'number') {
        return Array.from(value as ArrayLike<unknown>).filter(isHostedFile);
    }
    if (Symbol.iterator in value) return Array.from(value as Iterable<unknown>).filter(isHostedFile);
    return [];
}

function isHostedFile(value: unknown): value is File {
    if (typeof File !== 'undefined' && value instanceof File) return true;
    return Boolean(value
        && typeof value === 'object'
        && typeof (value as File).name === 'string'
        && typeof (value as Blob).slice === 'function');
}

function inferHostedSubtitleFileJobs(files: File[]): HostedSubtitleFileJob[] {
    const subtitleFiles = files.filter(file => /\.(?:srt|vtt|ass|ssa)$/iu.test(file.name));
    if (!subtitleFiles.length) return [];
    const primary = subtitleFiles.filter(file => isJapaneseSubtitleFile(file.name));
    const secondary = subtitleFiles.filter(file => isTranslationSubtitleFile(file.name));
    const fallback = subtitleFiles.filter(file => !primary.includes(file) && !secondary.includes(file));
    const selected = primary.shift() ?? fallback.shift() ?? secondary.shift();
    return selected ? [
        { kind: 'primary', file: selected },
        ...[...primary, ...fallback, ...secondary].map(file => ({ kind: 'secondary' as const, file })),
    ] : [];
}

function isTranslationSubtitleFile(name: string): boolean {
    return isEnglishSubtitleTrack({ label: name, kind: 'file' })
        || /(^|[.\-_\s()[\]])(?:translation|translated)(?=$|[.\-_\s()[\]])/iu.test(name);
}

function isJapaneseSubtitleFile(name: string): boolean {
    return /(^|[.\-_\s()[\]])(?:ja|jp|jpn|japanese|日本語)(?=$|[.\-_\s()[\]])/iu.test(name);
}

function normalizeHostedSubtitleOpenPanel(value: unknown): HostedSubtitleFileLoadRequest['openPanel'] {
    return value === 'lines' || value === 'tracks' || value === 'auto' || value === false ? value : 'auto';
}
