import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
    publishedWebsiteRouteDefinitions,
    websiteRoutePublication,
    type WebsiteRouteDefinition,
} from '../docs/.vitepress/locales/route-catalog.ts';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = path.join(ROOT, 'docs');
const CHECK = process.argv.includes('--check');
const failures: string[] = [];

const reviewedJapaneseRoutes = publishedWebsiteRouteDefinitions('ja');

for (const definition of reviewedJapaneseRoutes) {
    const target = path.join(DOCS, 'ja', localizedSource(definition.route));
    const expected = renderLocalizedRoute(definition, target);
    if (CHECK) {
        if (!existsSync(target) || readFileSync(target, 'utf8') !== expected) failures.push(relative(target));
        continue;
    }
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, expected);
}

if (failures.length) {
    console.error(`Reviewed locale route drift: ${failures.join(', ')}`);
    console.error('Run: npm run docs:locales:generate');
    process.exitCode = 1;
} else {
    console.log(`${CHECK ? 'Checked' : 'Generated'} ${reviewedJapaneseRoutes.length} reviewed Japanese routes.`);
}

function renderLocalizedRoute(definition: WebsiteRouteDefinition, target: string): string {
    const publication = websiteRoutePublication(definition, 'ja');
    if (!publication) throw new Error(`Japanese route is not reviewed: ${definition.route || '/'}`);
    const source = path.join(DOCS, definition.source);
    const frontmatter = sourceFrontmatter(readFileSync(source, 'utf8'));
    const extra = frontmatter
        .filter(line => !/^\s*(title|description):/.test(line))
        .join('\n');
    const metadata = [
        '---',
        ...(extra ? [extra] : []),
        `title: ${JSON.stringify(publication.title)}`,
        `description: ${JSON.stringify(publication.description)}`,
        '---',
    ].join('\n');
    return `${metadata}\n\n<!-- Generated by scripts/generate-reviewed-docs-locale-routes.mts. -->\n\n${localizedBody(definition, target)}\n`;
}

function localizedBody(definition: WebsiteRouteDefinition, target: string): string {
    if (definition.route === 'api/') {
        return `<script setup>\nimport ApiReference from '../../.vitepress/theme/ApiReference.vue'\n</script>\n\n<ApiReference />`;
    }
    if (definition.route === 'changelog') return '<!--@include: ../../CHANGELOG.md-->';
    const source = path.join(DOCS, definition.source);
    const include = path.relative(path.dirname(target), source).replaceAll(path.sep, '/');
    return `<!--@include: ${include.startsWith('.') ? include : `./${include}`}-->`;
}

function sourceFrontmatter(source: string): string[] {
    if (!source.startsWith('---\n')) return [];
    const end = source.indexOf('\n---\n', 4);
    if (end < 0) throw new Error('Unterminated docs frontmatter');
    return source.slice(4, end).split('\n');
}

function localizedSource(route: string): string {
    if (!route || route.endsWith('/')) return `${route}index.md`;
    return `${route}.md`;
}

function relative(file: string): string {
    return path.relative(ROOT, file).replaceAll(path.sep, '/');
}
