/** Copy owned by the Study grammar surface, kept outside the shared i18n catalogue. */
export const GRAMMAR_UI_COPY = {
    en: {
        findingGrammar: 'Finding grammar...',
        grammarNoLocalMatch: 'No built-in {language} grammar patterns matched this sentence.',
        grammarDetectionPending: 'Built-in {language} grammar detection is still being prepared.',
        grammarReferenceOnly: 'Built-in {language} grammar detection is still being prepared. Use the reference below.',
        grammarCheckUnavailable: 'Grammar could not be checked.',
        grammarReference: 'Open grammar reference',
        grammarKnown: 'Known',
        grammarReview: 'Review',
        grammarDetails: 'Details',
        grammarFoundIn: 'Found in',
        grammarExample: 'Example',
        grammarGuide: 'Guide',
        grammarHideKnown: 'Hide known',
        grammarShowKnown: 'Show known',
        allDetectedGrammarKnown: 'All detected grammar is marked known.',
        grammarShown: 'shown',
        grammarKnownHidden: 'known hidden',
        grammarGenericShort: 'Grammar point: {name}',
        grammarGenericDetail: 'Uses {name} in 「{match}」.',
        grammarLevelCore: 'Core',
    },
    ja: {
        findingGrammar: '文法を検索中...',
        grammarNoLocalMatch: '内蔵の{language}文法パターンはこの文に一致しませんでした。',
        grammarDetectionPending: '内蔵の{language}文法検出は準備中です。',
        grammarReferenceOnly: '内蔵の{language}文法検出は準備中です。下のリファレンスを利用できます。',
        grammarCheckUnavailable: '文法を確認できませんでした。',
        grammarReference: '文法リファレンスを開く',
        grammarKnown: '既知',
        grammarReview: '復習',
        grammarDetails: '詳細',
        grammarFoundIn: '検出箇所',
        grammarExample: '例',
        grammarGuide: 'ガイド',
        grammarHideKnown: '既知を隠す',
        grammarShowKnown: '既知を表示',
        allDetectedGrammarKnown: '検出文法はすべて既知です。',
        grammarShown: '件表示',
        grammarKnownHidden: '件の既知を非表示',
        grammarGenericShort: '文法項目: {name}',
        grammarGenericDetail: '「{match}」に「{name}」。',
        grammarLevelCore: '基本',
    },
} as const;
