import type { ActivityController, ActivityEvaluation, ActivityHost } from '../../domain/activity-runtime';
import { localizedNodes, setPending, showEvaluation, statusRegion } from '../activity-kit/shared';
import { renderInspectableSourceVisual } from '../source-visual';
import type { PlainStyleMatrixModel, PlainStyleMatrixResponse, PlainStyleMatrixSourceVisual } from './manifest';

export function renderPlainStyleMatrix(model: PlainStyleMatrixModel, host: ActivityHost, submit: (response: PlainStyleMatrixResponse) => Promise<ActivityEvaluation>): ActivityController {
    const lifecycle = new AbortController(); const root = document.createElement('section'); root.className = 'academy-activity academy-plain-style-matrix'; root.dataset.activityId = model.id;
    const heading = document.createElement('h2'); heading.id = `${model.id}-prompt`; heading.tabIndex = -1; heading.append(...localizedNodes(model.prompt));
    const teaching = document.createElement('section'); teaching.className = 'academy-plain-style-teaching'; teaching.dataset.lessonPhase = 'teaching';
    model.payload.teaching.forEach(step => { const article = document.createElement('article'); const title = document.createElement('h3'); title.append(...localizedNodes(step.title)); const pattern = document.createElement('p'); pattern.className = 'academy-plain-style-pattern academy-japanese'; pattern.lang = 'ja'; pattern.textContent = step.pattern; const instruction = document.createElement('p'); instruction.append(...localizedNodes(step.instruction)); article.append(title, pattern, instruction); teaching.append(article); });
    const sources = document.createElement('section'); sources.className = 'academy-plain-style-sources'; sources.dataset.lessonPhase = 'source-reference'; sources.append(renderVisual(model.provenance.moodle.vocabularySheet, host.language), renderVisual(model.provenance.moodle.grammarSheet, host.language));
    const form = document.createElement('form'); form.className = 'academy-plain-style-form'; form.setAttribute('aria-labelledby', heading.id); const board = document.createElement('ol'); board.className = 'academy-plain-style-board'; model.payload.prompts.forEach(prompt => board.append(renderRow(model, prompt, host.language))); const check = document.createElement('button'); check.type = 'submit'; check.className = 'academy-button academy-button-primary academy-plain-style-check'; check.textContent = host.language === 'ja' ? '四つの行を確認する' : 'Check the four rows'; form.append(board, check);
    const key = renderAnswerKey(model, host.language); const status = statusRegion('academy-kit-feedback academy-plain-style-feedback'); root.append(heading, teaching, sources, form, key, status); host.replace(root);
    form.addEventListener('submit', event => { event.preventDefault(); const response = responseFromForm(model, form); if (!response) { const message = host.language === 'ja' ? '四つの行すべてで形を一つ選んでください。' : 'Choose one form for each of the four rows.'; status.textContent = message; host.announce(message); return; } setPending(root, true); void submit(response).then(evaluation => { root.dataset.outcome = evaluation.result.outcome; key.hidden = false; showEvaluation(status, evaluation, host); if (evaluation.result.outcome === 'lapse') setPending(root, false); }).catch(error => { setPending(root, false); status.textContent = error instanceof Error ? error.message : String(error); }); }, { signal: lifecycle.signal });
    return { focus() { form.querySelector<HTMLInputElement>('input')?.focus(); }, dispose() { lifecycle.abort(); root.remove(); } };
}

function renderVisual(visual: PlainStyleMatrixSourceVisual, language: 'ja' | 'en' | undefined): HTMLElement { return renderInspectableSourceVisual(visual, language, 'academy-plain-style-source'); }
function renderRow(model: PlainStyleMatrixModel, prompt: PlainStyleMatrixModel['payload']['prompts'][number], language: 'ja' | 'en' | undefined): HTMLElement { const item = document.createElement('li'); item.className = 'academy-plain-style-row'; item.dataset.sourceQuestionId = prompt.sourceQuestionId; const fieldset = document.createElement('fieldset'); const legend = document.createElement('legend'); const column = hostColumn(prompt.targetColumn, language); legend.textContent = language === 'ja' ? `${prompt.sourceOrder}. ${prompt.politeForm} → ${column}` : `${prompt.sourceOrder}. ${prompt.politeForm} → ${column}`; fieldset.append(legend); prompt.options.forEach(option => { const label = document.createElement('label'); const input = document.createElement('input'); input.type = 'radio'; input.name = `${model.id}:${prompt.id}`; input.value = option.id; input.required = true; const value = document.createElement('span'); value.className = 'academy-japanese'; value.lang = 'ja'; value.textContent = option.label; label.append(input, value); fieldset.append(label); }); item.append(fieldset); return item; }
function renderAnswerKey(model: PlainStyleMatrixModel, language: 'ja' | 'en' | undefined): HTMLElement { const section = document.createElement('section'); section.className = 'academy-plain-style-key'; section.dataset.answerVisibility = 'after-attempt'; section.hidden = true; const heading = document.createElement('h3'); heading.textContent = language === 'ja' ? '試したあとの形' : 'Forms after your attempt'; const list = document.createElement('ol'); model.payload.prompts.forEach(prompt => { const item = document.createElement('li'); item.textContent = `${prompt.politeForm} → ${prompt.reviewExpression}`; list.append(item); }); section.append(heading, list); return section; }
function responseFromForm(model: PlainStyleMatrixModel, form: HTMLFormElement): PlainStyleMatrixResponse | null { const answers = model.payload.prompts.map(prompt => { const value = new FormData(form).get(`${model.id}:${prompt.id}`); return typeof value === 'string' && ['a', 'b', 'c'].includes(value) ? { promptId: prompt.id, optionId: value as 'a' | 'b' | 'c' } : null; }); return answers.every((answer): answer is PlainStyleMatrixResponse['answers'][number] => answer !== null) ? { answers } : null; }
function hostColumn(column: PlainStyleMatrixModel['payload']['prompts'][number]['targetColumn'], language: 'ja' | 'en' | undefined): string { const labels = language === 'ja' ? { dictionary: '辞書形', negative: 'ない形', 'past-negative': 'なかった形' } : { dictionary: 'dictionary form', negative: 'negative form', 'past-negative': 'past negative form' }; return labels[column]; }
